// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class AllocationController : Controller
{
    // App: Receipt Budget | Module: Allocation
    public IActionResult AssestRegisterAllocation()
    {
        ViewData["Title"] = "Assest Register Allocation";
        ViewData["Breadcrumb"] = "Receipt Budget / Allocation / Assest Register Allocation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
