// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class DashboardController : Controller
{
    // App: Receipt Budget | Module: Dashboard
    public IActionResult ListofCirculars()
    {
        ViewData["Title"] = "List of Circulars";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / List of Circulars";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult Circular()
    {
        ViewData["Title"] = "Circular";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Circular";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult CombinedDashboard()
    {
        ViewData["Title"] = "Combined Dashboard";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Combined Dashboard";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult SelectDemand()
    {
        ViewData["Title"] = "Select Demand";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Select Demand";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult SelectDemandSectionWise()
    {
        ViewData["Title"] = "Select  Demand Section Wise";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Select  Demand Section Wise";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult FileSharing()
    {
        ViewData["Title"] = "File Sharing";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / File Sharing";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult ViewFileSharing()
    {
        ViewData["Title"] = "View File Sharing";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / View File Sharing";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult SectionWiseDemandReport()
    {
        ViewData["Title"] = "Section Wise Demand Report";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Section Wise Demand Report";
        return View();
    }

    // App: Receipt Budget | Module: Dashboard
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register";
        ViewData["Breadcrumb"] = "Receipt Budget / Dashboard / Asset Register";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
