// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class NSMastersController : Controller
{
    // App: Receipt Budget | Module: NS Masters
    public IActionResult AddGroup()
    {
        ViewData["Title"] = "Add Group";
        ViewData["Breadcrumb"] = "Receipt Budget / NS Masters / Add Group";
        return View();
    }

    // App: Receipt Budget | Module: NS Masters
    public IActionResult AddScheme()
    {
        ViewData["Title"] = "Add Scheme";
        ViewData["Breadcrumb"] = "Receipt Budget / NS Masters / Add Scheme";
        return View();
    }

    // App: Receipt Budget | Module: NS Masters
    public IActionResult AddSubScheme()
    {
        ViewData["Title"] = "Add SubScheme";
        ViewData["Breadcrumb"] = "Receipt Budget / NS Masters / Add SubScheme";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
