// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class RBudgetController : Controller
{
    // App: Receipt Budget | Module: R Budget
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register";
        ViewData["Breadcrumb"] = "Receipt Budget / R Budget / Asset Register";
        return View();
    }

    // App: Receipt Budget | Module: R Budget
    public IActionResult ArrearsofNTR()
    {
        ViewData["Title"] = "Arrears of NTR";
        ViewData["Breadcrumb"] = "Receipt Budget / R Budget / Arrears of NTR";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
