// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class ReportsController : Controller
{
    // App: Receipt Budget | Module: Reports
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Asset Register";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult GenerateDG()
    {
        ViewData["Title"] = "Generate DG";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Generate DG";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult ArrearsOfNTR()
    {
        ViewData["Title"] = "Arrears Of NTR";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Arrears Of NTR";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult GenerateSBEUserWise()
    {
        ViewData["Title"] = "Generate SBE UserWise";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Generate SBE UserWise";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult InvestmentInPSEReport()
    {
        ViewData["Title"] = "Investment In PSE Report";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Investment In PSE Report";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult ReceiptRecoveryChargedReport()
    {
        ViewData["Title"] = "Receipt/Recovery/Charged Report";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Receipt/Recovery/Charged Report";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult SBEReportWithoutData()
    {
        ViewData["Title"] = "SBE Report Without Data";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / SBE Report Without Data";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult NTR()
    {
        ViewData["Title"] = "NTR";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / NTR";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult VoteonAccount()
    {
        ViewData["Title"] = "Vote on Account";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Vote on Account";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult DemandCeilingValidationsChecklist()
    {
        ViewData["Title"] = "Demand Ceiling Validations Checklist";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Demand Ceiling Validations Checklist";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult REandNBEsummismatchfortransferringdata()
    {
        ViewData["Title"] = "RE and NBE sum mismatch for transferring data";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / RE and NBE sum mismatch for transferring data";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult AssetRegisterAnalytics()
    {
        ViewData["Title"] = "Asset Register Analytics";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Asset Register Analytics";
        return View();
    }

    // App: Receipt Budget | Module: Reports
    public IActionResult ArrearsOfNTRAnalyticsReport()
    {
        ViewData["Title"] = "Arrears Of NTR Analytics Report";
        ViewData["Breadcrumb"] = "Receipt Budget / Reports / Arrears Of NTR Analytics Report";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
