// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class RMasterController : Controller
{
    // App: Receipt Budget | Module: R Master
    public IActionResult Group()
    {
        ViewData["Title"] = "Group";
        ViewData["Breadcrumb"] = "Receipt Budget / R Master / Group";
        return View();
    }

    // App: Receipt Budget | Module: R Master
    public IActionResult Scheme()
    {
        ViewData["Title"] = "Scheme";
        ViewData["Breadcrumb"] = "Receipt Budget / R Master / Scheme";
        return View();
    }

    // App: Receipt Budget | Module: R Master
    public IActionResult SubScheme()
    {
        ViewData["Title"] = "Sub Scheme";
        ViewData["Breadcrumb"] = "Receipt Budget / R Master / Sub Scheme";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
