// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ReceiptBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ReceiptBudget")]
[Authorize]
public class RStatementController : Controller
{
    // App: Receipt Budget | Module: R Statement
    public IActionResult ReceiptNTRLayout()
    {
        ViewData["Title"] = "Receipt NTR Layout";
        ViewData["Breadcrumb"] = "Receipt Budget / R Statement / Receipt NTR Layout";
        return View();
    }

    // App: Receipt Budget | Module: R Statement
    public IActionResult ReceiptLayout()
    {
        ViewData["Title"] = "Receipt Layout";
        ViewData["Breadcrumb"] = "Receipt Budget / R Statement / Receipt Layout";
        return View();
    }

    // App: Receipt Budget | Module: R Statement
    public IActionResult AssetNotes()
    {
        ViewData["Title"] = "Asset Notes";
        ViewData["Breadcrumb"] = "Receipt Budget / R Statement / Asset Notes";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
