// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.PreBudgetMeeting.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UBIS.Web.Areas.PreBudgetMeeting.Models;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("PreBudgetMeeting")]
[Authorize]
public class AllocationController : Controller
{
    private readonly IPreBudgetClient _preBudgetClient;
    private readonly IAimClient _aimClient;

    public AllocationController(IPreBudgetClient preBudgetClient, IAimClient aimClient)
    {
        _preBudgetClient = preBudgetClient;
        _aimClient = aimClient;
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult StatementAllocation()
    {
        ViewData["Title"] = "Statement Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Statement Allocation";
        return View();
    }

    /// <summary>
    /// "Add Allocation" screen (FunctionId 528, "Pre-budget - Add Allocation") - ABO-DS-Director/
    /// Section User pick an Appendix (or "All", the default) + a set of Demands + a Target Date,
    /// which opens those Demands' appendix entry screens until that date (see
    /// AppendixBaseViewModel.IsEntryLocked). Access is menu-driven only (M_RoleFunctionMapping for
    /// FunctionId 528) - no extra server-side role check here, per client decision 2026-08-14.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> REMeetingAllocation(int? appendixId, int page = 1, CancellationToken ct = default)
    {
        ViewData["Title"] = "Pre-budget - Add Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Add Allocation";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var model = await BuildAllocationViewModelAsync(session, appendixId, page, ct);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SubmitAllocation(AllocationSubmitRequest request, CancellationToken ct)
    {
        // Bug report 2026-08-31: this POST redisplays REMeetingAllocation's own view under a
        // different action name, which BreadcrumbFilter can't match against the menu tree (it's
        // not itself a menu Function) - tells it to breadcrumb as if this were that GET action
        // instead. See BreadcrumbFilter's own comment for the full explanation.
        HttpContext.Items["BreadcrumbAction"] = nameof(REMeetingAllocation);

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        // Client requirement 2026-08-28: "Target Date Validation: Greater than and Equal to Todays
        // Date" - server-side enforcement, not just the <input min="..."> HTML5 hint (per this
        // repo's "server-side enforcement always, never UI-hiding alone" convention).
        if (request.TargetDate.Date < DateTime.Today)
        {
            var invalidModel = await BuildAllocationViewModelAsync(session, request.AppendixId, 1, ct);
            invalidModel.StatusIsError = true;
            invalidModel.StatusMessage = "Target Date must be today or a future date.";
            ViewData["Title"] = "Pre-budget - Add Allocation";
            ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Add Allocation";
            return View("REMeetingAllocation", invalidModel);
        }

        var allocateRequest = new AllocateAppendixDto
        {
            FinancialYear = session.FinancialYear,
            TargetDate = request.TargetDate,
            AppendixId = request.AppendixId,
            DemandIds = request.DemandIds,
            NotifyDemandBudgetOfficer = new NotificationChannelFlags { Email = request.NotifyDemandBudgetOfficerEmail, Sms = request.NotifyDemandBudgetOfficerSms },
            NotifyDemandCca = new NotificationChannelFlags { Email = request.NotifyDemandCcaEmail, Sms = request.NotifyDemandCcaSms },
            NotifyDemandFa = new NotificationChannelFlags { Email = request.NotifyDemandFaEmail, Sms = request.NotifyDemandFaSms },
            NotifyBudgetDivisionOfficer = new NotificationChannelFlags { Email = request.NotifyBudgetDivisionOfficerEmail, Sms = request.NotifyBudgetDivisionOfficerSms },
            NotifySectionUser = new NotificationChannelFlags { Email = request.NotifySectionUserEmail, Sms = request.NotifySectionUserSms }
        };

        var result = await _preBudgetClient.AllocateAsync(session.Token, allocateRequest, ct);

        var model = await BuildAllocationViewModelAsync(session, request.AppendixId, 1, ct);
        model.StatusIsError = !result.IsSuccess;
        if (!result.IsSuccess)
        {
            model.StatusMessage = result.Error?.Message ?? "Could not save the allocation.";
        }
        else
        {
            var data = result.Data!;
            model.StatusMessage = data.SkippedFrozenDemandIds.Count == 0
                ? $"Allocated {data.DemandsAllocated} Demand(s) x {data.AppendixesAllocated} Appendix(es)."
                : $"Allocated {data.DemandsAllocated} Demand(s) x {data.AppendixesAllocated} Appendix(es). {data.SkippedFrozenDemandIds.Count} Demand(s) skipped (already frozen).";
        }

        ViewData["Title"] = "Pre-budget - Add Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Add Allocation";
        return View("REMeetingAllocation", model);
    }

    /// <summary>Row-level edit (client requirement 2026-08-28: an Edit icon per grid row lets the
    /// Target Date/Frozen/Nil Data be corrected for one Demand directly). AppendixId mirrors
    /// whatever the page's own "Select Appendix" filter currently is, so the edit applies to the
    /// same aggregate set the grid row itself represents (see UpdateAllocationDto's doc comment).</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateAllocation(int demandId, int? appendixId, DateTime? targetDate, bool isFrozen, bool isNilSubmitted, CancellationToken ct)
    {
        // See SubmitAllocation's matching comment / BreadcrumbFilter for why this is needed.
        HttpContext.Items["BreadcrumbAction"] = nameof(REMeetingAllocation);

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (targetDate.HasValue && targetDate.Value.Date < DateTime.Today)
        {
            var invalidModel = await BuildAllocationViewModelAsync(session, appendixId, 1, ct);
            invalidModel.StatusIsError = true;
            invalidModel.StatusMessage = "Target Date must be today or a future date.";
            ViewData["Title"] = "Pre-budget - Add Allocation";
            ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Add Allocation";
            return View("REMeetingAllocation", invalidModel);
        }

        var result = await _preBudgetClient.UpdateAllocationAsync(session.Token, new UpdateAllocationDto
        {
            DemandId = demandId,
            AppendixId = appendixId,
            FinancialYear = session.FinancialYear,
            TargetDate = targetDate,
            IsFrozen = isFrozen,
            IsNilSubmitted = isNilSubmitted
        }, ct);

        var model = await BuildAllocationViewModelAsync(session, appendixId, 1, ct);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? "Allocation updated successfully."
            : (result.Error?.Message ?? "Could not update the allocation.");

        ViewData["Title"] = "Pre-budget - Add Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Add Allocation";
        return View("REMeetingAllocation", model);
    }

    private async Task<AllocationViewModel> BuildAllocationViewModelAsync(UbisSessionData session, int? appendixId, int page, CancellationToken ct)
    {
        var model = new AllocationViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedAppendixId = appendixId,
            Page = page < 1 ? 1 : page
        };

        // Client requirement 2026-08-28: "took too much time to load" - these 3 calls (2 different
        // microservices) are fully independent of each other (none reads another's result), but
        // were being awaited one at a time, so the page's real load time was the SUM of all 3
        // round-trips instead of the slowest one. Fired together via Task.WhenAll instead.
        var appendixesTask = _preBudgetClient.GetAppendicesAsync(session.Token, session.FinancialYear, ct);
        var demandsTask = _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        var allocationsTask = _preBudgetClient.GetAllocationsAsync(session.Token, appendixId, session.FinancialYear, ct);
        await Task.WhenAll(appendixesTask, demandsTask, allocationsTask);

        var appendixesResult = await appendixesTask;
        if (appendixesResult.IsSuccess && appendixesResult.Data != null)
        {
            model.Appendixes = appendixesResult.Data;
        }

        var demandsResult = await demandsTask;
        if (demandsResult.IsSuccess && demandsResult.Data != null)
        {
            model.Demands = demandsResult.Data.Demands;
        }

        var allocationsResult = await allocationsTask;
        if (allocationsResult.IsSuccess && allocationsResult.Data != null)
        {
            // Client requirement 2026-08-28: "add 15 record pagination to grid, sort by
            // DemandSrNo" - sorted here (not left to whatever order GetAllocationsAsync's own
            // GroupBy happened to return), then sliced to just the requested page.
            var sorted = allocationsResult.Data.OrderBy(a => a.DemandNo).ToList();
            model.TotalAllocationCount = sorted.Count;
            if (model.Page > model.TotalPages)
            {
                model.Page = model.TotalPages;
            }
            model.ExistingAllocations = sorted
                .Skip((model.Page - 1) * AllocationViewModel.PageSize)
                .Take(AllocationViewModel.PageSize)
                .ToList();
        }

        return model;
    }

    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult UserAllocation()
    {
        ViewData["Title"] = "User  Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / User  Allocation";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult RailwayAllocation()
    {
        ViewData["Title"] = "Railway Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Railway Allocation";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult ActualsBECategoryChangePermission()
    {
        ViewData["Title"] = "Actuals/BE/Category Change Permission";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Actuals/BE/Category Change Permission";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult ApproveIPAddresses()
    {
        ViewData["Title"] = "Approve IP Addresses";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Approve IP Addresses";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult PermissionReport()
    {
        ViewData["Title"] = "Permission Report";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Permission Report";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult FreezeUnfreezeSBE()
    {
        ViewData["Title"] = "Freeze/Unfreeze SBE";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Freeze/Unfreeze SBE";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult FreezeUnfreezeDemandStatementWise()
    {
        ViewData["Title"] = "Freeze/ Unfreeze Demand Statement Wise";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Freeze/ Unfreeze Demand Statement Wise";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult EnableBEEditPermission()
    {
        ViewData["Title"] = "Enable BE Edit Permission";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / Enable BE Edit Permission";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Pre Budget Meeting | Module: Allocation
    public IActionResult VoAAllocation()
    {
        ViewData["Title"] = "VoA Allocation";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Allocation / VoA Allocation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
