// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
//
// The "auto-generated" text above is intentional (see above) but also matches Roslyn's
// auto-generated-file heuristic, which stops this file from implicitly inheriting the
// project's <Nullable>enable</Nullable> setting - explicit directive below instead
// (fixes CS8669 on every nullable-annotated signature in this file).
#nullable enable
namespace UBIS.Web.Areas.PreBudgetMeeting.Controllers;

using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using UBIS.Web.Areas.PreBudgetMeeting.Models;
using UBIS.Web.Services.Caching;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("PreBudgetMeeting")]
[Authorize]
public partial class PreBudgetMeetingController : Controller
{
    private readonly IPreBudgetClient _preBudgetClient;
    private readonly IAimClient _aimClient;
    private readonly IAppCacheService _cache;
    private readonly IReportingClient _reportingClient;

    public PreBudgetMeetingController(IPreBudgetClient preBudgetClient, IAimClient aimClient, IAppCacheService cache, IReportingClient reportingClient)
    {
        _preBudgetClient = preBudgetClient;
        _aimClient = aimClient;
        _cache = cache;
        _reportingClient = reportingClient;
    }

    /// <summary>
    /// The Pre-Budget Data and Report page fetches demand/appendix screens via AJAX (fetch with
    /// X-Requested-With: XMLHttpRequest) and injects the returned HTML into a container on the
    /// page, instead of a full page navigation per dropdown change. Every action on this
    /// controller that returns a View - AppendixEntry itself and every SaveAppendixX/
    /// FreezeAppendixX/DeleteAppendixX action, whether it renders directly or redirects back to
    /// AppendixEntry - needs to come back as a bare fragment (no sidebar/header) in that case, so
    /// this is handled once, centrally, instead of touching every one of those ~90 actions
    /// individually. See Areas/PreBudgetMeeting/Views/_ViewStart.cshtml for the other half.
    /// </summary>
    public override void OnActionExecuted(ActionExecutedContext context)
    {
        if (IsAjaxRequest() && context.Result is ViewResult viewResult)
        {
            viewResult.ViewData["Layout"] = string.Empty;
        }

        base.OnActionExecuted(context);
    }

    private bool IsAjaxRequest() =>
        string.Equals(Request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.OrdinalIgnoreCase);

    // App: Pre Budget Meeting | Module: Pre Budget Meeting
    // Select-Demand-and-Appendix screen (replaces the old app's SelectAppendix.aspx / sp_Select_Demands_Template).
    [HttpGet]
    public async Task<IActionResult> PreBudgetDataandReport(int? demandId, CancellationToken ct)
    {
        ViewData["Title"] = "Pre-Budget Data and Report";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Data Entry / Pre-Budget Data and Report";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var model = new PreBudgetSelectorViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedDemandId = demandId
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        if (demandsResult.IsSuccess && demandsResult.Data != null)
        {
            model.Demands = demandsResult.Data.Demands;

            // Client report 2026-09-10 ("Demand dropdown showing 3 entries per demand"): AIM's
            // GetMyDemands only checks role-based visibility (M_MapUserRole) - it has no idea
            // whether PreBudget's own Appendix Allocation workflow has actually been set up for a
            // given Demand, and returns every Demand the user may see regardless. Narrow that list
            // down to only Demands with a real dbo.M_DemandAppendixAllocation row for this year -
            // see IAppendixService.GetAllocatedDemandIdsAsync's own doc comment for the exact fan-
            // out bug this replaces (a naive INNER JOIN there would have reproduced the same "N
            // entries per demand" symptom for any Demand with N allocated Appendixes). Fails open
            // (keeps AIM's full list) if this call itself fails, rather than showing no Demands at
            // all over a transient PreBudget-service hiccup.
            if (model.Demands.Count > 0)
            {
                var allocatedResult = await _preBudgetClient.GetAllocatedDemandIdsAsync(
                    session.Token, model.Demands.Select(d => d.DemandId), session.FinancialYear, ct);
                if (allocatedResult.IsSuccess && allocatedResult.Data != null)
                {
                    var allocatedIds = allocatedResult.Data.ToHashSet();
                    model.Demands = model.Demands.Where(d => allocatedIds.Contains(d.DemandId)).ToList();
                }
            }
        }
        else
        {
            model.StatusIsError = true;
            model.StatusMessage = demandsResult.Error?.Message ?? "Could not load your Demands. Please try again shortly.";
        }

        // Appendix list/status for a pre-selected demandId (e.g. a bookmarked URL) is fetched
        // client-side via GetAppendixOptions instead of here - the view no longer renders
        // Model.Appendices directly (see pre-budget-meeting.js), so fetching it twice (once here,
        // unused, and once via AJAX on page load) would just be wasted work.

        return View(model);
    }

    /// <summary>
    /// AJAX-only: populates the Appendix dropdown once a Demand is picked, without a full page
    /// reload. Returns the Code/Name/IsFrozen/IsTargetDateExpired/TargetDate shape.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> GetAppendixOptions(int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        var statusResult = await _preBudgetClient.GetAppendicesWithStatusAsync(session.Token, demandId, session.FinancialYear, ct);
        if (!statusResult.IsSuccess || statusResult.Data == null)
        {
            return Json(new { success = false, message = statusResult.Error?.Message ?? "Could not load appendices for the selected Demand." });
        }

        return Json(new
        {
            success = true,
            appendices = statusResult.Data.Select(a => new
            {
                code = a.Code,
                name = a.Name,
                isFrozen = a.IsFrozen,
                isNilSubmitted = a.IsNilSubmitted,
                isTargetDateExpired = a.IsTargetDateExpired,
                targetDate = a.TargetDate
            })
        });
    }

    /// <summary>
    /// Nil button (client meeting 2026-08-06): "this button appear only if no data is there, it
    /// disable all fields. You can contact the concerned department." Scoped to Appendix I/I-A
    /// (AppendixI.cshtml/AppendixIA.cshtml only render the button when Records.Count == 0). Returns
    /// the entry view directly rather than RedirectToAction, for the same reason as
    /// FreezeAppendixTemplate above - OnActionExecuted only fragment-izes a ViewResult.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SetNilSubmission(int demandId, int appendixId, string code, string? nilRemarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.SetNilSubmissionAsync(session.Token, new SetNilSubmissionDto
        {
            DemandId = demandId,
            AppendixId = appendixId,
            FinancialYear = session.FinancialYear,
            NilRemarks = nilRemarks
        }, ct);

        return await AppendixEntry(code, demandId, ct);
    }

    /// <summary>
    /// Central dispatcher for "Go to Entry Screen" — mirrors the old app's per-appendix .aspx
    /// pages, but as one action keyed by the FRS Roman-numeral Code instead of 22 separate routes.
    /// Only I/II/III-A have a real form built so far (see design doc §10/§11) — every other code
    /// gets the ComingSoon view rather than a broken/half-wired page.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> AppendixEntry(string code, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var appendix = await FindAppendixByCodeAsync(session.Token, session.FinancialYear, code, ct);
        var demandName = await ResolveDemandNameAsync(session, demandId, ct);

        ViewData["Breadcrumb"] = $"Pre Budget Meeting / Pre Budget Meeting / {appendix?.Name ?? code}";
        ViewData["Title"] = appendix?.Name ?? code;

        switch (code)
        {
            case "I":
                return View("AppendixI", await BuildAppendixIViewModelAsync(session, demandId, demandName, ct));
            case "I-A":
                return View("AppendixIA", await BuildAppendixIAViewModelAsync(session, demandId, demandName, ct));
            case "II":
                return View("AppendixII", await BuildAppendixIIViewModelAsync(session, demandId, demandName, ct));
            case "III":
                return View("AppendixIII", await BuildAppendixIIIViewModelAsync(session, demandId, demandName, ct));
            case "III-A":
                return View("AppendixIIIA", await BuildAppendixIIIAViewModelAsync(session, demandId, demandName, ct));
            case "III-B":
                return View("AppendixIIIB", await BuildAppendixIIIBViewModelAsync(session, demandId, demandName, ct));
            case "IV":
                return View("AppendixIV", await BuildAppendixIVViewModelAsync(session, demandId, demandName, ct));
            case "IV-A":
                return View("AppendixIVA", await BuildAppendixIVAViewModelAsync(session, demandId, demandName, ct));
            case "IV-B":
                return View("AppendixIVB", await BuildAppendixIVBViewModelAsync(session, demandId, demandName, ct));
            case "V":
                return View("AppendixVSummary", await BuildAppendixVSummaryViewModelAsync(session, demandId, demandName, ct));
            case "V-A":
                return View("AppendixVA", await BuildAppendixVAViewModelAsync(session, demandId, demandName, ct));
            case "V-B":
                return View("AppendixVB", await BuildAppendixVBViewModelAsync(session, demandId, demandName, ct));
            case "V-C":
                return View("AppendixVC", await BuildAppendixVCViewModelAsync(session, demandId, demandName, ct));
            case "VI":
                return View("AppendixVI", await BuildAppendixVIViewModelAsync(session, demandId, demandName, ct));
            case "VI-A":
                return View("AppendixVIA", await BuildAppendixVIAViewModelAsync(session, demandId, demandName, ct));
            case "VI-B":
                return View("AppendixVIB", await BuildAppendixVIBViewModelAsync(session, demandId, demandName, ct));
            case "VI-C":
                return View("AppendixVIC", await BuildAppendixVICViewModelAsync(session, demandId, demandName, ct));
            case "VI-D":
                return View("AppendixVID", await BuildAppendixVIDViewModelAsync(session, demandId, demandName, ct));
            case "VI-E":
                return View("AppendixVIE", await BuildAppendixVIEViewModelAsync(session, demandId, demandName, ct));
            case "VI-F":
                return View("AppendixVIF", await BuildAppendixVIFViewModelAsync(session, demandId, demandName, ct));
            case "VI-G":
                return View("AppendixVIG", await BuildAppendixVIGViewModelAsync(session, demandId, demandName, ct));
            case "VII-A":
                return View("AppendixVIIA", await BuildAppendixVIIAViewModelAsync(session, demandId, demandName, ct));
            case "VII-B":
                return View("AppendixVIIB", await BuildAppendixVIIBViewModelAsync(session, demandId, demandName, ct));
            // Client data correction 2026-09-10: dbo.M_Appendix.Code for this appendix changed
            // from "XI" to "X" ("X - Loan to Government Servants, etc."). 2026-09-14: completed
            // the rename across every C#/file/view/JS identifier and the DB table itself
            // (dbo.Appendix_X_LoansToGovtServants, was Appendix_XI_LoansToGovtServants) - no more
            // "XI"-named code anywhere for this appendix.
            case "X":
                return View("AppendixX", await BuildAppendixXViewModelAsync(session, demandId, demandName, ct));
            case "PA-ReceiptPayment":
                return View("AppendixPA", await BuildAppendixPAViewModelAsync(session, demandId, demandName, ct));
            default:
                ViewData["ComingSoonCode"] = code;
                ViewData["ComingSoonName"] = appendix?.Name ?? code;
                return View("AppendixComingSoon");
        }
    }

    /// <summary>
    /// Template-level Freeze button (client review 2026-08-05, item 3): freezes this Demand+Appendix
    /// for the session's financial year via dbo.PreBudgetSubmissionStatus, distinct from any
    /// row-level freeze an individual appendix's own records may separately support.
    /// </summary>
    /// <summary>
    /// Generic export for any appendix grid (added 2026-09-15, client instruction: "export
    /// functionality should depend on columns of grid being export, not hard-code... any update on
    /// grid columns should not change export functionality... if grid has colspan or rowspan for
    /// headers, export to excel and PDF should support it"). Every per-appendix ExportAppendixX
    /// action before this hand-maintained its own Columns/Rows list in C#, which drifts out of sync
    /// with the actual grid the moment someone edits the view without also updating the export code
    /// (exactly the bug fixed for Appendix III's export headers a few commits back) - this endpoint
    /// takes whatever wwwroot/js/grid-export.js scraped directly off the live &lt;table&gt; DOM
    /// (headers including any colspan/rowspan grouping, visible data rows respecting the Columns
    /// menu's current show/hide state and current sort, and which columns are right-aligned) and
    /// forwards it to the Reporting service completely unchanged - there is no appendix-specific
    /// code in this action at all, so it never needs touching again as any appendix's grid evolves.
    /// New appendixes should wire their Export button to grid-export.js instead of writing a new
    /// ExportAppendixX action; existing ones migrate opportunistically.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ExportGrid([FromBody] GridExportRequestDto request, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();

        var report = new TabularReportDto
        {
            Title = request.Title,
            Subtitle = request.Subtitle,
            ColumnGroups = request.ColumnGroups?.Select(g => new ReportColumnGroupDto { Label = g.Label, ColumnSpan = g.ColumnSpan }).ToList(),
            Columns = request.Columns,
            RightAlignedColumns = request.RightAlignedColumns,
            Groups = new List<ReportGroupDto> { new() { Rows = request.Rows } },
            FileName = request.FileName
        };

        var exportResult = request.Format?.ToLowerInvariant() switch
        {
            "excel" => await _reportingClient.ExportExcelAsync(session.Token, report, ct),
            "csv" => await _reportingClient.ExportCsvAsync(session.Token, report, ct),
            _ => await _reportingClient.ExportPdfAsync(session.Token, report, ct)
        };

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            return StatusCode(500, new { message = exportResult.Error?.Message ?? "Could not generate the export. Please try again." });
        }

        var (contentType, extension) = request.Format?.ToLowerInvariant() switch
        {
            "excel" => ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
            "csv" => ("text/csv", "csv"),
            _ => ("application/pdf", "pdf")
        };
        return File(exportResult.Data, contentType, $"{report.FileName}.{extension}");
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixTemplate(int demandId, string code, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();

        var appendix = await FindAppendixByCodeAsync(session.Token, session.FinancialYear, code, ct);
        if (appendix != null)
        {
            await _preBudgetClient.FreezeSubmissionAsync(session.Token, appendix.AppendixId, demandId, session.FinancialYear, ct);
        }

        // Bug fix 2026-08-06: was RedirectToAction, which meant a second round trip whose response
        // OnActionExecuted never saw (it only fragment-izes a ViewResult, not a RedirectResult) -
        // fetch() then rendered the FULL page (header/sidebar included) into #partialViewContainer,
        // which is what made the Demand/Appendix dropdowns above it look like they'd been wiped.
        // Every other Save/Freeze action in this file already returns the View directly for exactly
        // this reason - matching that here instead of redirecting.
        return await AppendixEntry(code, demandId, ct);
    }

    // ---------------------------------------------------------------------------------------
    // Appendix I: Budget and Expenditure Trends
    // ---------------------------------------------------------------------------------------

    /// <summary>
    /// Approved design (2026-07-29): a fixed 5-year grid (session FY's 5 preceding years) saved as
    /// one batch instead of one ad-hoc record at a time. Each row with an existing Id is updated;
    /// each row with no Id but at least one non-empty field is created; rows with no Id and
    /// nothing entered, or that are already frozen, are skipped.
    /// </summary>
    /// <summary>
    /// Rewritten 2026-09-09 for the drawer/grid redesign - previously posted the whole 5-year
    /// matrix (List&lt;AppendixIYearRowViewModel&gt;) in one submit; now posts a single record like
    /// every other redesigned appendix. FinancialYear is always forced to ActualYear server-side
    /// (never trusted from the client) since that's the only year this screen ever permits
    /// Add/Edit on - see AppendixIViewModel.ActualYear's own doc comment.
    /// </summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveAppendixI(int demandId, SaveAppendixBudgetExpenditureTrendDto newRecord, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);
        var actualYear = GetPrecedingFinancialYears(session.FinancialYear, 3).FirstOrDefault() ?? session.FinancialYear;
        newRecord.DemandId = demandId;
        newRecord.FinancialYear = actualYear;

        var result = newRecord.Id.HasValue && newRecord.Id.Value > 0
            ? await _preBudgetClient.UpdateAppendixIAsync(session.Token, newRecord.Id.Value, newRecord, ct)
            : await _preBudgetClient.CreateAppendixIAsync(session.Token, newRecord, ct);

        var model = await BuildAppendixIViewModelAsync(session, demandId, demandName, ct);
        // "Input grid still not blank after Submit" (client testing feedback, 2026-08-24) - asp-for
        // renders from ModelState before the model; see AppendixIV.cs's matching comment. Only on
        // success - keep the user's typed values on the page if the save itself failed.
        if (result.IsSuccess)
        {
            ModelState.Clear();
        }
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? (newRecord.Id.HasValue && newRecord.Id.Value > 0 ? "Record modified successfully." : "Record saved successfully.")
            : (result.Error?.Code == "DUPLICATE_ENTRY" ? $"Data for Financial Year {actualYear} already exists." : result.Error?.Message ?? "Could not save the record.");

        ViewData["Title"] = "Appendix I - Budget and Expenditure Trends";
        return View("AppendixI", model);
    }

    /// <summary>Bulk-freezes every saved, not-yet-frozen row in the 5-year grid in one action
    /// (the "Freeze Data" button) - distinct from the per-row Freeze in the history table below,
    /// which still freezes a single record at a time.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixIBulk(int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);
        var model = await BuildAppendixIViewModelAsync(session, demandId, demandName, ct);

        foreach (var row in model.Rows.Where(r => r.Id.HasValue && !r.IsFrozen))
        {
            await _preBudgetClient.FreezeAppendixIAsync(session.Token, row.Id!.Value, ct);
        }

        model = await BuildAppendixIViewModelAsync(session, demandId, demandName, ct);
        model.StatusMessage = "Budget and Expenditure Trends data frozen.";

        ViewData["Title"] = "Appendix I - Budget and Expenditure Trends";
        return View("AppendixI", model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixI(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.FreezeAppendixIAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see FreezeAppendixTemplate's matching comment
        // above.
        return await AppendixEntry("I", demandId, ct);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteAppendixI(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.DeleteAppendixIAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see DeleteAppendixIA's matching comment.
        return await AppendixEntry("I", demandId, ct);
    }

    /// <summary>
    /// Client requirement 2026-09-02: the on-screen read-only records grid on AppendixI.cshtml was
    /// hidden in favor of an on-demand Export button - this reuses the exact same
    /// BuildAppendixIViewModelAsync/Records source that grid used to render, so the exported file's
    /// data always matches what the (now-hidden) grid would have shown. Merged header ("Revenue"/
    /// "Capital" each spanning 4 sub-columns) is expressed via TabularReportDto.ColumnGroups, which
    /// both the PDF (MigraDoc) and Excel (ClosedXML) generators render as a real merged cell, not
    /// just visually - matching the client's "if merged cells heading then same format" ask.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> ExportAppendixI(int demandId, string format, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);
        var model = await BuildAppendixIViewModelAsync(session, demandId, demandName, ct);

        // Client requirement 2026-09-17: export header reverted to the standard "Appendix {Code} -
        // {Name}" / "Demand: {No} - {Name} | Financial Year: {FY}" format every other appendix
        // export already uses (screenshot supplied) - Name is looked up live rather than hardcoded
        // so it always matches whatever the application's own Appendix dropdown/page shows, and
        // FinancialYear is the session's own current year, same source the on-screen page uses.
        // Drops the earlier circular-only "(See Para X)"/Remarks-footer pieces, but the "(₹ in
        // crore)" unit note stays (client flagged it missing 2026-09-18, comparing against I-A's
        // export which already has it).
        var appendix = await FindAppendixByCodeAsync(session.Token, session.FinancialYear, "I", ct);

        // The export must match the government circular's own Appendix-I table structure - Year /
        // Revenue(BE,RE,Actuals) / Capital(BE,RE,Actuals) / Total(BE,RE,Actuals,Actuals upto Sept),
        // no S.No./Status columns (those are this app's own UI convenience, not part of the
        // approved format). Total columns are Revenue+Capital sums, computed here rather than
        // trusted from any stored field.
        // Client requirement 2026-09-18: a raw Revenue/Capital cell with no underlying data (as
        // opposed to a genuine computed zero) is passed as null rather than "" - the shared report
        // generators render a null cell as "0.00" in Excel/CSV and "..." in PDF (see
        // ReportGroup.Rows' own doc comment). The Total columns stay real computed sums (missing
        // treated as 0 for summation purposes), never null.
        var dataRows = model.Records.Select(r => new[]
        {
            FormatFinancialYearShort(r.FinancialYear),
            r.RevenueBE?.ToString("F2")!,
            r.RevenueRE?.ToString("F2")!,
            r.RevenueActuals?.ToString("F2")!,
            r.CapitalBE?.ToString("F2")!,
            r.CapitalRE?.ToString("F2")!,
            r.CapitalActuals?.ToString("F2")!,
            ((r.RevenueBE ?? 0) + (r.CapitalBE ?? 0)).ToString("F2"),
            ((r.RevenueRE ?? 0) + (r.CapitalRE ?? 0)).ToString("F2"),
            ((r.RevenueActuals ?? 0) + (r.CapitalActuals ?? 0)).ToString("F2"),
            ((r.RevenueActualsUptoSept ?? 0) + (r.CapitalActualsUptoSept ?? 0)).ToString("F2")
        }).ToList();

        var report = new TabularReportDto
        {
            Title = $"Appendix {appendix?.Code ?? "I"} - {appendix?.Name ?? "Budget and Expenditure Trends"}",
            Subtitle = $"Demand: {demandName} | Financial Year: {session.FinancialYear}",
            UnitNote = "(₹ in crore)",
            Remarks = model.Remarks,
            ColumnGroups = new List<ReportColumnGroupDto>
            {
                new() { Label = null, ColumnSpan = 1 }, // Year
                new() { Label = "Revenue", ColumnSpan = 3 },
                new() { Label = "Capital", ColumnSpan = 3 },
                new() { Label = "Total", ColumnSpan = 4 }
            },
            Columns = new List<string> { "Year", "BE", "RE", "Actuals", "BE", "RE", "Actuals", "BE", "RE", "Actuals", "Actuals upto Sept" },
            // Client requirement 2026-09-17: every column header centered, matching the government
            // circular's own table exactly - but every numeric figure (every column except Year)
            // stays right-aligned per the standard accounting convention (RightAlignedColumns wins
            // over CenterAlignedColumns for DATA cells specifically - see TabularReport's own
            // doc comment). Year itself has no RightAlignedColumns entry, so its data stays centered.
            CenterAlignedColumns = new List<int> { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 },
            RightAlignedColumns = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 },
            Groups = new List<ReportGroupDto> { new() { Rows = dataRows } },
            // Client requirement: "AppendixName-username-DateInMMDDYYYYhhminss" - 24-hour clock
            // used for the timestamp component (unambiguous, no AM/PM marker needed).
            FileName = $"AppendixI-{session.UserName}-{DateTime.Now:MMddyyyyHHmmss}"
        };

        var exportResult = format?.ToLowerInvariant() switch
        {
            "excel" => await _reportingClient.ExportExcelAsync(session.Token, report, ct),
            "csv" => await _reportingClient.ExportCsvAsync(session.Token, report, ct),
            _ => await _reportingClient.ExportPdfAsync(session.Token, report, ct)
        };

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            TempData["ErrorMessage"] = exportResult.Error?.Message ?? "Could not generate the export. Please try again.";
            return await AppendixEntry("I", demandId, ct);
        }

        var (contentType, extension) = format?.ToLowerInvariant() switch
        {
            "excel" => ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
            "csv" => ("text/csv", "csv"),
            _ => ("application/pdf", "pdf")
        };
        return File(exportResult.Data, contentType, $"{report.FileName}.{extension}");
    }

    // ---------------------------------------------------------------------------------------
    // Appendix II: Quarterly Expenditure Plan (QEP)
    // ---------------------------------------------------------------------------------------

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveAppendixII(int demandId, SaveAppendixQuarterlyExpenditurePlanDto newRecord, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        newRecord.DemandId = demandId;
        newRecord.FinancialYear = session.FinancialYear;

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);

        // FRS Deviation Validations (§4.2.3): mandatory Remarks when a deviation is indicated —
        // mirrored client-side too (see AppendixII.cshtml), but enforced here as the authoritative
        // check since this is a real state change, same rule PreBudget's own API also enforces.
        string? validationError = null;
        if (newRecord.Q1HasDeviation && string.IsNullOrWhiteSpace(newRecord.RemarksQ1))
        {
            validationError = "Remarks (Q1) are required when a deviation from MEP/QEP is indicated.";
        }
        else if (newRecord.Q2HasDeviation && string.IsNullOrWhiteSpace(newRecord.RemarksQ2))
        {
            validationError = "Remarks (Q2) are required when a deviation from MEP/QEP is indicated.";
        }

        AppendixIIViewModel model;
        if (validationError != null)
        {
            model = await BuildAppendixIIViewModelAsync(session, demandId, demandName, ct);
            model.NewRecord = newRecord;
            model.StatusIsError = true;
            model.StatusMessage = validationError;
        }
        else
        {
            var result = newRecord.Id.HasValue && newRecord.Id.Value > 0
                ? await _preBudgetClient.UpdateAppendixIIAsync(session.Token, newRecord.Id.Value, newRecord, ct)
                : await _preBudgetClient.CreateAppendixIIAsync(session.Token, newRecord, ct);
            model = await BuildAppendixIIViewModelAsync(session, demandId, demandName, ct);
            // "Input grid still not blank after Submit" (client testing feedback, 2026-08-24) - asp-for
            // renders from ModelState before the model; see AppendixIV.cs's matching comment. Only
            // when the save itself succeeded - the validation-error branch above and a failed save
            // both deliberately keep ModelState (and NewRecord) so the user sees what they typed.
            if (result.IsSuccess)
            {
                ModelState.Clear();
            }
            model.StatusIsError = !result.IsSuccess;
            model.StatusMessage = result.IsSuccess
                ? (newRecord.Id.HasValue && newRecord.Id.Value > 0 ? "Record modified successfully." : "Record saved successfully.")
                // Same DUPLICATE_ENTRY enrichment as SaveAppendixIA - see its matching comment.
                : (result.Error?.Code == "DUPLICATE_ENTRY" ? $"Data for Demand {demandName} already exists." : result.Error?.Message ?? "Could not save the record.");
        }

        ViewData["Title"] = "Appendix II - Quarterly Expenditure Plan";
        return View("AppendixII", model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteAppendixII(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.DeleteAppendixIIAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see DeleteAppendixIA's matching comment.
        return await AppendixEntry("II", demandId, ct);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixII(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.FreezeAppendixIIAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see FreezeAppendixTemplate's matching comment
        // above.
        return await AppendixEntry("II", demandId, ct);
    }

    /// <summary>
    /// Export dropdown (2026-09-08, extended to Appendix II from the VI-A..E design) - PDF/Excel/
    /// CSV, same TabularReportDto/_reportingClient shape as ExportAppendixVIA.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> ExportAppendixII(int demandId, string format, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var (demandNo, demandName) = await ResolveDemandNoAndNameAsync(session, demandId, ct);
        var model = await BuildAppendixIIViewModelAsync(session, demandId, demandName, ct);

        // Client requirement 2026-09-18: export must match the government circular's own
        // Appendix-II layout exactly (screenshot supplied) - a bordered 3-line header block
        // ("{DemandNo}. {DemandName}" / "Appendix II" / "{Appendix full name}") instead of the
        // Title+Subtitle theme every other appendix export uses, "(In crore of Rupees)" instead of
        // "(₹ in crore)", "As per approved QEP" instead of "As per QEP stipulated by MoF", and no
        // ParaNo/Remarks footer lines at all (this screenshot supersedes the 2026-09-17 circular
        // build's header/footer choices for this appendix specifically). The Year column stays
        // short-form ("2024-25") like every other appendix's circular export, fixing a mismatch
        // where this column previously rendered the raw "2026-2027" session value unshortened.
        var appendix = await FindAppendixByCodeAsync(session.Token, session.FinancialYear, "II", ct);

        // Client requirement 2026-09-18: a cell with no underlying data (as opposed to a genuine
        // computed zero/percentage) is passed as null rather than "" - the shared report generators
        // render a null cell as "0.00" in Excel/CSV and "..." in PDF (see ReportGroup.Rows' own doc
        // comment).
        static string? PercentOf(decimal? actuals, decimal? qep)
        {
            if (actuals == null || qep is null or 0m)
            {
                return null;
            }
            return (actuals.Value / qep.Value * 100m).ToString("F2") + "%";
        }

        var r = model.Records.FirstOrDefault();
        var dataRows = new List<string[]>
        {
            new[] { "1st Quarter", r?.Q1ApprovedQep?.ToString("F2")!, r?.Q1Actuals?.ToString("F2")!, PercentOf(r?.Q1Actuals, r?.Q1ApprovedQep)! },
            new[] { "2nd Quarter", r?.Q2ApprovedQep?.ToString("F2")!, r?.Q2Actuals?.ToString("F2")!, PercentOf(r?.Q2Actuals, r?.Q2ApprovedQep)! }
        };
        var totalRow = new ReportTotalRowDto
        {
            Cells = new[] { "Total", (r != null ? r.TotalApprovedQep.ToString("F2") : null)!, (r != null ? r.TotalActuals.ToString("F2") : null)!, PercentOf(r?.TotalActuals, r?.TotalApprovedQep)! }
        };

        var report = new TabularReportDto
        {
            Title = demandNo.HasValue ? $"{demandNo}. {demandName}" : demandName,
            TitleBoxLines = new List<string> { "Appendix II", appendix?.Name ?? "Quarterly Expenditure Plan Progress (on Gross Basis)" },
            UnitNote = "(In crore of Rupees)",
            Columns = new List<string> { FormatFinancialYearShort(model.PriorFinancialYear), "As per approved QEP", "Actuals", "Actuals as % of QEP" },
            CenterAlignedColumns = new List<int> { 0, 1, 2, 3 },
            RightAlignedColumns = new List<int> { 1, 2, 3 },
            Groups = new List<ReportGroupDto> { new() { Rows = dataRows, Totals = new List<ReportTotalRowDto> { totalRow } } },
            FileName = $"AppendixII-{session.UserName}-{DateTime.Now:MMddyyyyHHmmss}"
        };

        var exportResult = format?.ToLowerInvariant() switch
        {
            "excel" => await _reportingClient.ExportExcelAsync(session.Token, report, ct),
            "csv" => await _reportingClient.ExportCsvAsync(session.Token, report, ct),
            _ => await _reportingClient.ExportPdfAsync(session.Token, report, ct)
        };

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            TempData["ErrorMessage"] = exportResult.Error?.Message ?? "Could not generate the export. Please try again.";
            return await AppendixEntry("II", demandId, ct);
        }

        var (contentType, extension) = format?.ToLowerInvariant() switch
        {
            "excel" => ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
            "csv" => ("text/csv", "csv"),
            _ => ("application/pdf", "pdf")
        };
        return File(exportResult.Data, contentType, $"{report.FileName}.{extension}");
    }

    // ---------------------------------------------------------------------------------------
    // Appendix III-A: TSA Assignment and Expenditure
    // ---------------------------------------------------------------------------------------

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveAppendixIIIA(int demandId, SaveAppendixTsaAssignmentDto newRecord, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);

        newRecord.DemandId = demandId;
        newRecord.FinancialYear = session.FinancialYear;

        ApiCallResult<AppendixTsaAssignmentDto>? result = null;
        if (!string.IsNullOrWhiteSpace(newRecord.EntityName))
        {
            result = newRecord.Id.HasValue && newRecord.Id.Value > 0
                ? await _preBudgetClient.UpdateAppendixIIIAAsync(session.Token, newRecord.Id.Value, newRecord, ct)
                : await _preBudgetClient.CreateAppendixIIIAAsync(session.Token, newRecord, ct);
        }

        var model = await BuildAppendixIIIAViewModelAsync(session, demandId, demandName, ct);
        // "Input grid still not blank after Submit" (client testing feedback, 2026-08-24) - asp-for
        // renders from ModelState before the model; see AppendixIV.cs's matching comment. Only when
        // a save was actually attempted and succeeded.
        if (result is { IsSuccess: true })
        {
            ModelState.Clear();
        }
        model.StatusIsError = result != null && !result.IsSuccess;
        model.StatusMessage = result == null
            ? "Enter the Name of the Entity to save a record."
            : (result.IsSuccess ? (newRecord.Id.HasValue && newRecord.Id.Value > 0 ? "Record modified successfully." : "Record saved successfully.") : (result.Error?.Message ?? "Could not save the record."));

        ViewData["Title"] = "Appendix III-A : TSA Assignment and Expenditure";
        return View("AppendixIIIA", model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixIIIA(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.FreezeAppendixIIIAAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see FreezeAppendixTemplate's matching comment
        // above.
        return await AppendixEntry("III-A", demandId, ct);
    }

    // "Freeze Data" on the entry form isn't scoped to one row (the form holds 2 blank entry slots,
    // not a specific record id) - it freezes every not-yet-frozen record for this demand/year,
    // same bulk pattern as FreezeAppendixIBulk/FreezeAppendixIIIBulk.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> FreezeAppendixIIIABulk(int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);
        var model = await BuildAppendixIIIAViewModelAsync(session, demandId, demandName, ct);

        foreach (var record in model.Records.Where(r => !r.IsFrozen))
        {
            await _preBudgetClient.FreezeAppendixIIIAAsync(session.Token, record.Id, ct);
        }

        model = await BuildAppendixIIIAViewModelAsync(session, demandId, demandName, ct);
        model.StatusMessage = "TSA Assignment and Expenditure data frozen.";

        ViewData["Title"] = "Appendix III-A : TSA Assignment and Expenditure";
        return View("AppendixIIIA", model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteAppendixIIIA(int id, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        await _preBudgetClient.DeleteAppendixIIIAAsync(session.Token, id, ct);
        // Fragment-return, not RedirectToAction - see DeleteAppendixIA's matching comment.
        return await AppendixEntry("III-A", demandId, ct);
    }

    /// <summary>
    /// Export dropdown (2026-09-09, extended to Appendix III-A from the VI-A..E/III design) -
    /// PDF/Excel/CSV, same TabularReportDto/_reportingClient shape as ExportAppendixIII.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> ExportAppendixIIIA(int demandId, string format, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var demandName = await ResolveDemandNameAsync(session, demandId, ct);
        var model = await BuildAppendixIIIAViewModelAsync(session, demandId, demandName, ct);
        var priorYearStart = model.PriorFinancialYear.Split('-')[0];

        // Client requirement 2026-09-18: export must match the government circular's own
        // Appendix-III-A table exactly (screenshot supplied) - "Sl No / Name of the Entity / BE /
        // TSA assignment as on 30th Sept / Actual Expenditure upto Sept / Unspent Assignment /
        // Date of last assignment / Amount of last assignment", no Status column (this app's own
        // UI convenience, not part of the approved format). Header theme (Title/Subtitle/ParaNo/
        // UnitNote) matches Appendix I's and Appendix III's export.
        // Client requirement 2026-09-18: a numeric cell with no underlying data (as opposed to a
        // genuine computed zero) is passed as null rather than "0.00" - the shared report
        // generators render a null cell as "0.00" in Excel/CSV and "..." in PDF (see
        // ReportGroup.Rows' own doc comment). The date column keeps its own "-" placeholder, unrelated
        // to this numeric convention.
        var dataRows = model.Records.Select((r, i) => new[]
        {
            (i + 1).ToString(),
            r.EntityName,
            r.BE?.ToString("0.00")!,
            r.TsaAssignmentAsOnSept?.ToString("0.00")!,
            r.ActualExpenditureUptoSept?.ToString("0.00")!,
            r.UnspentAssignment?.ToString("0.00")!,
            r.DateOfLastAssignment?.ToString("dd-MMM-yyyy") ?? "-",
            r.AmountOfLastAssignment?.ToString("0.00")!
        }).ToList();

        var report = new TabularReportDto
        {
            Title = "Appendix-III-A: TSA Assignment and Expenditure",
            Subtitle = $"Demand: {demandName} | Financial Year: {session.FinancialYear}",
            ParaNo = model.ParaNo,
            UnitNote = "(₹ in crore)",
            Remarks = model.Remarks,
            Columns = new List<string>
            {
                "Sl No.", "Name of the Entity", $"BE {model.PriorFinancialYear}", $"TSA assignment as on 30th Sept., {priorYearStart}",
                $"Actual Expenditure upto Sept., {priorYearStart}", "Unspent Assignment", "Date of last assignment", "Amount of last assignment"
            },
            CenterAlignedColumns = new List<int> { 0, 1, 2, 3, 4, 5, 6, 7 },
            RightAlignedColumns = new List<int> { 2, 3, 4, 5, 7 },
            Groups = new List<ReportGroupDto> { new() { Rows = dataRows } },
            FileName = $"AppendixIIIA-{session.UserName}-{DateTime.Now:MMddyyyyHHmmss}"
        };

        var exportResult = format?.ToLowerInvariant() switch
        {
            "excel" => await _reportingClient.ExportExcelAsync(session.Token, report, ct),
            "csv" => await _reportingClient.ExportCsvAsync(session.Token, report, ct),
            _ => await _reportingClient.ExportPdfAsync(session.Token, report, ct)
        };

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            TempData["ErrorMessage"] = exportResult.Error?.Message ?? "Could not generate the export. Please try again.";
            return await AppendixEntry("III-A", demandId, ct);
        }

        var (contentType, extension) = format?.ToLowerInvariant() switch
        {
            "excel" => ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
            "csv" => ("text/csv", "csv"),
            _ => ("application/pdf", "pdf")
        };
        return File(exportResult.Data, contentType, $"{report.FileName}.{extension}");
    }

    // ---------------------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------------------

    /// <summary>Government-circular abbreviation for the two known M_Category rows shared by
    /// Appendix III/III-B/IV's Category grouping ("Central Sector Schemes/Projects" -> "CS",
    /// "Centrally Sponsored Schemes" -> "CSS") - added 2026-09-18. The live CategoryName text has
    /// no abbreviation of its own (confirmed against the actual M_Category rows), and the circular
    /// always shows the group heading/Total-row label suffixed with it (e.g. "Centrally Sponsored
    /// Schemes (CSS)", "Total (CS)"). Falls back to the full category name for anything else,
    /// rather than guessing an abbreviation for a category this mapping doesn't know about.</summary>
    private static string CategoryAbbreviation(string? categoryName) => categoryName switch
    {
        "Centrally Sponsored Schemes" => "CSS",
        "Central Sector Schemes/Projects" or "Central Sector Schemes" => "CS",
        _ => categoryName ?? "Uncategorized"
    };

    /// <summary>Full group-heading text for a report section grouped by Category - "{Name} ({Abbrev})"
    /// when a known abbreviation exists, otherwise just the plain category name (never a
    /// redundant "Foo (Foo)" for an unmapped category).</summary>
    private static string CategoryHeading(string? categoryName)
    {
        var abbreviation = CategoryAbbreviation(categoryName);
        var name = categoryName ?? "Uncategorized";
        return abbreviation == name ? name : $"{name} ({abbreviation})";
    }

    private async Task<string> ResolveDemandNameAsync(UbisSessionData session, int demandId, CancellationToken ct)
    {
        var (demandNo, demandName) = await ResolveDemandNoAndNameAsync(session, demandId, ct);
        return demandNo.HasValue ? $"{demandNo} - {demandName}" : demandName;
    }

    /// <summary>Raw DemandNo/DemandName pieces (via vw_Demand, same source ResolveDemandNameAsync
    /// itself uses) for export headers that need a different join than the standard "{No} -
    /// {Name}" - added 2026-09-18 for Appendix II's circular format, which uses "{No}. {Name}".</summary>
    private async Task<(int? DemandNo, string DemandName)> ResolveDemandNoAndNameAsync(UbisSessionData session, int demandId, CancellationToken ct)
    {
        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        var match = demandsResult.Data?.Demands.FirstOrDefault(d => d.DemandId == demandId);
        return match != null ? (match.DemandNo, match.DemandName) : (null, $"Demand {demandId}");
    }

    private async Task<PreBudgetAppendixDto?> FindAppendixByCodeAsync(string bearerToken, string financialYear, string code, CancellationToken ct)
    {
        var result = await _preBudgetClient.GetAppendicesAsync(bearerToken, financialYear, ct);
        return result.Data?.FirstOrDefault(a => string.Equals(a.Code, code, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Populates the shared freeze/target-date-expiry fields on any AppendixBaseViewModel-derived
    /// model (client review 2026-08-05, items 2/3/8): looks up this Demand+Appendix+FY's row from
    /// the Select-Demand-and-Appendix status list and copies its IsFrozen/IsTargetDateExpired flags
    /// across. Every appendix builder should call this right before returning its view model.
    /// </summary>
    private async Task ApplyFreezeStatusAsync(AppendixBaseViewModel model, UbisSessionData session, int demandId, string code, CancellationToken ct)
    {
        model.AppendixCode = code;

        var statusResult = await _preBudgetClient.GetAppendicesWithStatusAsync(session.Token, demandId, session.FinancialYear, ct);
        var match = statusResult.Data?.FirstOrDefault(a => string.Equals(a.Code, code, StringComparison.OrdinalIgnoreCase));
        if (match == null)
        {
            return;
        }

        model.IsAppendixFrozen = match.IsFrozen;
        model.IsTargetDateExpired = match.IsTargetDateExpired;
        model.IsNilSubmitted = match.IsNilSubmitted;
        model.AppendixId = match.AppendixId;
        model.Remarks = match.Remarks;
        model.ParaNo = match.ParaNo;
    }

    /// <summary>Returns <paramref name="count"/> financial-year strings ending at (and including)
    /// <paramref name="currentFinancialYear"/>, oldest first - e.g. for "2026-2027" and count 5:
    /// "2022-2023", "2023-2024", "2024-2025", "2025-2026", "2026-2027". Includes the current year
    /// deliberately - standard FRS "Budget and Expenditure Trends" practice shows the current
    /// year's BE/RE alongside the preceding years' actuals, and (2026-07-29) excluding it made
    /// every existing real record - which was naturally entered under the current year - invisible
    /// in both the entry grid and the history table below it.</summary>
    private static List<string> GetPrecedingFinancialYears(string currentFinancialYear, int count)
    {
        var years = new List<string>();
        var parts = currentFinancialYear?.Split('-');
        if (parts == null || parts.Length != 2 || !int.TryParse(parts[0], out var startYear))
        {
            return years;
        }

        for (var i = count - 1; i >= 0; i--)
        {
            years.Add($"{startYear - i}-{startYear - i + 1}");
        }

        return years;
    }

    /// <summary>"2026-2027" -&gt; "2026-27", matching the government circular's own short year
    /// format (client requirement 2026-09-17, Appendix I export). Falls back to the input
    /// unchanged if it isn't in the expected "YYYY-YYYY" shape.</summary>
    private static string FormatFinancialYearShort(string financialYear)
    {
        var parts = financialYear?.Split('-');
        if (parts == null || parts.Length != 2 || parts[1].Length != 4)
        {
            return financialYear ?? string.Empty;
        }

        return $"{parts[0]}-{parts[1][2..]}";
    }

    /// <summary>Fetches each of the 5 preceding-years' records individually (the PreBudget API
    /// filters strictly by exact FinancialYear per call, so there's no single "all years" query)
    /// and builds both the editable 5-year grid and the read-only history table from the same
    /// data - this is deliberately scoped to just those 5 years per the approved design, not full
    /// all-time history.</summary>
    private async Task<AppendixIViewModel> BuildAppendixIViewModelAsync(UbisSessionData session, int demandId, string demandName, CancellationToken ct)
    {
        var rows = new List<AppendixIYearRowViewModel>();
        var records = new List<AppendixBudgetExpenditureTrendDto>();

        // Client review 2026-08-06 ("Actual Year" terminology): Appendix I's 5-year grid runs
        // Actual Year-4..Actual Year, where Actual Year = Current FY - 2 (e.g. session FY
        // 2026-2027 -> Actual Year 2024-2025 -> grid 2020-2021..2024-2025) - not the session's
        // own current/budget FY. GetPrecedingFinancialYears(cur, 3).First() = cur-2 = Actual Year.
        var actualYear = GetPrecedingFinancialYears(session.FinancialYear, 3).FirstOrDefault() ?? session.FinancialYear;

        foreach (var year in GetPrecedingFinancialYears(actualYear, 5))
        {
            var result = await _preBudgetClient.GetAppendixIAsync(session.Token, demandId, year, ct);
            // Client requirement 2026-09-18: if a Demand somehow has more than one Appendix I row
            // for the same year (data-quality artifact, not a normal flow - CreateRecord blocks a
            // second row per Demand+FinancialYear going forward), show the last-entered one
            // (max Id), not whatever order the API happens to return. A year with no row at all
            // still falls through to the "no data" branch below, which already renders "0.00" for
            // every column via each cell's own ?? "0.00" fallback - no separate change needed there.
            var existing = result.Data?.OrderByDescending(r => r.Id).FirstOrDefault();

            if (existing != null)
            {
                records.Add(existing);

                // Reverted 2026-08-04 (client requirement): every year's entry boxes always show
                // that year's saved values now - only the current filing year's row stays editable
                // (AppendixI.cshtml disables the other 4 rows' inputs based on IsCurrentYear
                // below). Disabled inputs don't post back, so SaveAppendixI's existing
                // "skip a row with no submitted values" check already leaves locked rows alone on
                // submit with no further backend change needed.
                rows.Add(new AppendixIYearRowViewModel
                {
                    FinancialYear = year,
                    Id = existing.Id,
                    IsFrozen = existing.IsFrozen,
                    IsCurrentYear = year == actualYear,
                    RevenueBE = existing.RevenueBE,
                    RevenueRE = existing.RevenueRE,
                    RevenueActuals = existing.RevenueActuals,
                    RevenueActualsUptoSept = existing.RevenueActualsUptoSept,
                    CapitalBE = existing.CapitalBE,
                    CapitalRE = existing.CapitalRE,
                    CapitalActuals = existing.CapitalActuals,
                    CapitalActualsUptoSept = existing.CapitalActualsUptoSept
                });
            }
            else
            {
                // Fixed 2026-09-09 (found while wiring the new Add-gating check): this branch
                // compared against session.FinancialYear instead of actualYear, so a blank
                // not-yet-saved ActualYear row was wrongly flagged IsCurrentYear=false (the "else"
                // branch above already got this right). Harmless in practice so far - ActualYear is
                // 2 years behind the session's filing year, so by the time a cycle reaches that
                // year it already has a saved (often frozen) record and hits the "existing != null"
                // branch instead - but the new single-source-of-truth Add-gating check below needs
                // this to be correct in every case, not just the common one.
                rows.Add(new AppendixIYearRowViewModel { FinancialYear = year, IsCurrentYear = year == actualYear });
            }
        }

        var model = new AppendixIViewModel
        {
            DemandId = demandId,
            DemandName = demandName,
            FinancialYear = session.FinancialYear,
            Records = records,
            Rows = rows,
            ActualYear = actualYear
        };
        model.NewRecord.FinancialYear = actualYear;
        await ApplyFreezeStatusAsync(model, session, demandId, "I", ct);
        return model;
    }

    private async Task<AppendixIIViewModel> BuildAppendixIIViewModelAsync(UbisSessionData session, int demandId, string demandName, CancellationToken ct)
    {
        var result = await _preBudgetClient.GetAppendixIIAsync(session.Token, demandId, session.FinancialYear, ct);
        var appendixIIModel = new AppendixIIViewModel
        {
            DemandId = demandId,
            DemandName = demandName,
            FinancialYear = session.FinancialYear,
            Records = result.Data ?? new List<AppendixQuarterlyExpenditurePlanDto>()
        };
        await ApplyFreezeStatusAsync(appendixIIModel, session, demandId, "II", ct);
        return appendixIIModel;
    }

    private async Task<AppendixIIIAViewModel> BuildAppendixIIIAViewModelAsync(UbisSessionData session, int demandId, string demandName, CancellationToken ct)
    {
        var result = await _preBudgetClient.GetAppendixIIIAAsync(session.Token, demandId, session.FinancialYear, ct);
        var model = new AppendixIIIAViewModel
        {
            DemandId = demandId,
            DemandName = demandName,
            FinancialYear = session.FinancialYear,
            Records = result.Data ?? new List<AppendixTsaAssignmentDto>()
        };
        await ApplyFreezeStatusAsync(model, session, demandId, "III-A", ct);
        return model;
    }

    // "Page sometimes automatically refreshes and I lose my Demand/Appendix selection" (client
    // report, 2026-08-25) - root cause: this page never does a real page navigation, every
    // Submit/Save/cascade round trip is a fetch() into #partialViewContainer (see OnActionExecuted's
    // own doc comment above). A RedirectToAction here was silently followed by fetch() (redirects
    // are followed transparently by default) all the way to the full Login page's HTML - including
    // its own header/sidebar - which then got stuffed into that small container, looking exactly
    // like an unexplained "page refresh" that wiped whatever was on screen. Same bug class as the
    // FreezeAppendixIA fix noted elsewhere in this file ("OnActionExecuted only fragment-izes a
    // ViewResult, not a RedirectResult"), just triggered by session expiry instead of a Freeze
    // action. For an AJAX request, return 401 instead so the client JS can do a REAL, visible
    // `window.location.href` navigation to Login (see pre-budget-meeting.js's response handling).
    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (IsAjaxRequest())
        {
            return Unauthorized();
        }
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // FR-004: Autonomous Master for Appendix VI-C/VI-E. Access is restricted to exactly two roles
    // (client requirement, 2026-08-10): Administrator (creates/maintains the master directly, via
    // the Add form below) and "Single Demand Users" (this system's Ministry User equivalent - the
    // FRS's generic "Ministry User"/"Budget Division User"/"ABO/DS/Director User" wording doesn't
    // match any literal role name here, and the client narrowed access to just these two, tighter
    // than the FRS's three). Both the menu (RoleFunctionMappingSeedConfiguration, FunctionId 347)
    // and this action must independently enforce this - menu visibility alone doesn't stop direct
    // URL access. AutonomousBodiesController's own admin checks (AutonomousBodyAdminRoleOptions)
    // remain the authoritative server-side gate on the actual write actions; the checks here are
    // this MVC layer's independent enforcement of page-level access, not a UI-only convenience.
    private static readonly string[] AutonomousBodyAdminRoleNames = { "Administrator", "Super Admin" };
    private static readonly string[] AutonomousMasterPageRoleNames = { "Administrator", "Super Admin", "Single Demand Users" };

    private static readonly TimeSpan AutonomousBodiesCacheTtl = TimeSpan.FromMinutes(15);

    private static string AutonomousBodiesCacheKey(int demandId, string financialYear) =>
        $"ubis:autonomous-bodies:{demandId}:{financialYear}";

    [HttpGet]
    public async Task<IActionResult> AutonomousMasterforAppendixVICandVIE(int? demandId, CancellationToken ct)
    {
        ViewData["Title"] = "Autonomous Master for Appendix VI C and VI E";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Pre Budget Meeting / Autonomous Master for Appendix VI C and VI E";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!AutonomousMasterPageRoleNames.Contains(session.RoleName, StringComparer.OrdinalIgnoreCase))
        {
            return Forbid();
        }

        var model = new AutonomousMasterViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedDemandId = demandId,
            CanReview = AutonomousBodyAdminRoleNames.Contains(session.RoleName, StringComparer.OrdinalIgnoreCase)
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        if (demandsResult.IsSuccess && demandsResult.Data != null)
        {
            model.Demands = demandsResult.Data.Demands;
        }

        // Client requirement 2026-08-31: "For Single Demand User, there is only single demand so
        // show in label not in dropdown ... and its associated grid show during page load" - same
        // Demands.Count == 1 condition PreBudgetDataandReport.cshtml already uses for its own
        // Single-Demand-User label. Auto-selects the sole Demand server-side (this page is a plain
        // full-page GET, not the AJAX cascade PreBudgetDataandReport uses, so there's no client-side
        // bootstrap to mirror - selecting it here is what makes the grid/forms below render
        // immediately on page load instead of needing an explicit pick first).
        if (!demandId.HasValue && model.Demands.Count == 1)
        {
            demandId = model.Demands[0].DemandId;
            model.SelectedDemandId = demandId;
        }

        if (demandId.HasValue)
        {
            var bodiesResult = await _preBudgetClient.GetAutonomousBodiesAsync(session.Token, demandId.Value, session.FinancialYear, ct);
            if (bodiesResult.IsSuccess && bodiesResult.Data != null)
            {
                model.AutonomousBodies = bodiesResult.Data;

                // Client requirement 2026-08-10: every existing Autonomous Body for this Demand is
                // cached in Redis on page load, so the Add/Request forms' duplicate-name check
                // (CheckAutonomousBodyNameExists below) can be answered from cache instead of a DB
                // round trip on every keystroke.
                await _cache.SetAsync(AutonomousBodiesCacheKey(demandId.Value, session.FinancialYear), model.AutonomousBodies, AutonomousBodiesCacheTtl, ct);
            }
        }

        if (model.CanReview)
        {
            var pendingResult = await _preBudgetClient.GetPendingAutonomousBodyRequestsAsync(session.Token, ct);
            if (pendingResult.IsSuccess && pendingResult.Data != null)
            {
                model.PendingRequests = pendingResult.Data;
            }
        }

        return View(model);
    }

    /// <summary>Direct add - matches the legacy "Add Autonomous/Grantee Name" form. Originally
    /// Administrator-only; opened up to every AutonomousMasterPageRoleNames role (client
    /// requirement, 2026-08-31: "it should not request Autonomous Body, it should add it" - Single
    /// Demand Users now save directly through this same action instead of the old Request flow).
    /// Server-side role check is authoritative in AutonomousBodiesController
    /// (AutonomousBodyCreatorRoleOptions); this MVC-layer check just avoids a pointless round trip
    /// for a role that would be rejected anyway.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAutonomousBody(int demandId, string name, string? hName, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!AutonomousMasterPageRoleNames.Contains(session.RoleName, StringComparer.OrdinalIgnoreCase))
        {
            return Forbid();
        }

        var result = await _preBudgetClient.CreateAutonomousBodyAsync(session.Token, new CreateAutonomousBodyDto
        {
            DemandId = demandId,
            FinancialYear = session.FinancialYear,
            Name = name,
            HName = hName
        }, ct);

        if (result.IsSuccess && result.Data != null)
        {
            // Client requirement 2026-08-10: the new entry is added to the Redis cache immediately,
            // not just left to the next page load's re-fetch, so the duplicate-name check reflects
            // it right away (e.g. a second admin browsing the same Demand in another tab).
            var cacheKey = AutonomousBodiesCacheKey(demandId, session.FinancialYear);
            var cached = await _cache.GetAsync<List<AutonomousBodyDto>>(cacheKey, ct) ?? new List<AutonomousBodyDto>();
            cached.Add(result.Data);
            await _cache.SetAsync(cacheKey, cached, AutonomousBodiesCacheTtl, ct);
        }

        // Client requirement 2026-08-31: "show MessageBox in Dialog: Title: Save Record. Text:
        // 'Autonomous Body Name is Saved Successfully'" - exact wording, rendered as the standard
        // dialogs.js modal by the view (see autonomous-master.js) instead of the old inline banner.
        TempData["AutonomousMasterStatus"] = result.IsSuccess
            ? "Autonomous Body Name is Saved Successfully"
            : (result.Error?.Message ?? "Could not add the Autonomous Body.");
        TempData["AutonomousMasterStatusIsError"] = !result.IsSuccess;
        TempData["AutonomousMasterFocusName"] = true;

        return RedirectToAction(nameof(AutonomousMasterforAppendixVICandVIE), new { demandId });
    }

    /// <summary>
    /// AJAX-only, client requirement 2026-08-10: the Add/Request forms call this on the Name and
    /// HName fields to warn about a duplicate before submitting, answered from the Redis cache
    /// AutonomousMasterforAppendixVICandVIE populated on page load (falls back to a live fetch -
    /// and re-caches - on a cache miss, e.g. if the page has been open longer than the cache TTL).
    /// Case-insensitive, trimmed - matches how a human would judge "the same name". `field` selects
    /// which of the existing bodies' columns to compare against - "Name" (English, default) or
    /// "HName" (Hindi) - since the two are independent duplicate checks, not one combined check.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> CheckAutonomousBodyNameExists(int demandId, string name, string? field, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        var trimmedName = (name ?? string.Empty).Trim();
        if (trimmedName.Length == 0)
        {
            return Json(new { exists = false });
        }

        var checkHindi = string.Equals(field, "HName", StringComparison.OrdinalIgnoreCase);

        var cacheKey = AutonomousBodiesCacheKey(demandId, session.FinancialYear);
        var cached = await _cache.GetAsync<List<AutonomousBodyDto>>(cacheKey, ct);
        if (cached == null)
        {
            var bodiesResult = await _preBudgetClient.GetAutonomousBodiesAsync(session.Token, demandId, session.FinancialYear, ct);
            cached = bodiesResult.Data ?? new List<AutonomousBodyDto>();
            await _cache.SetAsync(cacheKey, cached, AutonomousBodiesCacheTtl, ct);
        }

        var exists = checkHindi
            ? cached.Any(b => !string.IsNullOrEmpty(b.HName) && string.Equals(b.HName.Trim(), trimmedName, StringComparison.OrdinalIgnoreCase))
            : cached.Any(b => string.Equals(b.Name?.Trim(), trimmedName, StringComparison.OrdinalIgnoreCase));
        return Json(new { exists });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RequestAutonomousBody(int demandId, string requestedName, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var result = await _preBudgetClient.RequestNewAutonomousBodyAsync(session.Token, new CreateAutonomousBodyRequestDto
        {
            DemandId = demandId,
            FinancialYear = session.FinancialYear,
            RequestedName = requestedName
        }, ct);

        TempData["AutonomousMasterStatus"] = result.IsSuccess
            ? "Request submitted — an Administrator will review it."
            : (result.Error?.Message ?? "Could not submit the request.");
        TempData["AutonomousMasterStatusIsError"] = !result.IsSuccess;

        return RedirectToAction(nameof(AutonomousMasterforAppendixVICandVIE), new { demandId });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ReviewAutonomousBodyRequest(int requestId, int demandId, bool approve, string? code, string? reviewRemarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var result = await _preBudgetClient.ReviewAutonomousBodyRequestAsync(session.Token, requestId, new ReviewAutonomousBodyRequestDto
        {
            Approve = approve,
            Code = code,
            ReviewRemarks = reviewRemarks
        }, ct);

        if (result.IsSuccess && approve)
        {
            // Approving also creates a real AutonomousBody row (in PreBudget, via AIM's/PreBudget's
            // own ReviewRequestAsync) - but the response here is the request DTO, not the created
            // body's full shape (Id/Code), so invalidate rather than reconstruct a partial cache
            // entry. The GET action re-fetches and re-caches on next load.
            await _cache.RemoveAsync(AutonomousBodiesCacheKey(demandId, session.FinancialYear), ct);
        }

        TempData["AutonomousMasterStatus"] = result.IsSuccess
            ? (approve ? "Request approved." : "Request rejected.")
            : (result.Error?.Message ?? "Could not review the request.");
        TempData["AutonomousMasterStatusIsError"] = !result.IsSuccess;

        return RedirectToAction(nameof(AutonomousMasterforAppendixVICandVIE), new { demandId });
    }

    // FR-003: RE Data Remarks. Read/write are both role-gated server-side (RemarksController via
    // RemarkRoleOptions) — CanPostRemark here just hides the composer for everyone else.
    private static readonly string[] RemarkAllowedRoleNames = { "Budget Division", "ABO-DS-Director", "Administrator" };

    // Client instruction 2026-09-21: on the Appendix IV/IV-A/IV-B grids and edit drawers, "Single
    // Demand Users" (Ministry side) only need to see Remarks (Ministry); "ABO-DS-Director" has the
    // same access as Budget Division and Section User for this purpose, so all three only need to
    // see Remarks (Budget Div) - none of the three should see the other side's internal remarks.
    // Distinct from RemarkAllowedRoleNames above (that one gates FR-003's separate RE Data Remarks
    // composer and includes Administrator; this one is grid-column visibility on a different
    // feature and deliberately does not restrict Administrator/other roles, who keep seeing both
    // columns per ResolveRemarksColumnVisibility's own default-true fallback).
    private static readonly string[] BudgetSideRemarksRoleNames = { "Budget Division", "ABO-DS-Director", "Section User" };

    private static void ApplyRemarksColumnVisibility(AppendixBaseViewModel model, string? roleName)
    {
        if (string.Equals(roleName, "Single Demand Users", StringComparison.OrdinalIgnoreCase))
        {
            model.ShowRemarksBudgetColumn = false;
        }
        else if (BudgetSideRemarksRoleNames.Contains(roleName, StringComparer.OrdinalIgnoreCase))
        {
            model.ShowRemarksMinistryColumn = false;
        }
    }

    [HttpGet]
    public async Task<IActionResult> REDataRemarks(int? demandId, int? appendixId, CancellationToken ct)
    {
        ViewData["Title"] = "RE Data Remarks";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Pre Budget Meeting / RE Data Remarks";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var model = new REDataRemarksViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedDemandId = demandId,
            SelectedAppendixId = appendixId,
            CanPostRemark = RemarkAllowedRoleNames.Contains(session.RoleName, StringComparer.OrdinalIgnoreCase)
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        if (demandsResult.IsSuccess && demandsResult.Data != null)
        {
            model.Demands = demandsResult.Data.Demands;
        }

        if (demandId.HasValue)
        {
            var appendicesResult = await _preBudgetClient.GetAppendicesAsync(session.Token, session.FinancialYear, ct);
            if (appendicesResult.IsSuccess && appendicesResult.Data != null)
            {
                model.Appendices = appendicesResult.Data;
            }
        }

        if (demandId.HasValue && appendixId.HasValue)
        {
            var remarksResult = await _preBudgetClient.GetRemarksAsync(session.Token, demandId.Value, appendixId.Value, session.FinancialYear, ct);
            if (remarksResult.IsSuccess && remarksResult.Data != null)
            {
                model.Remarks = remarksResult.Data;
            }
            else
            {
                model.StatusIsError = true;
                model.StatusMessage = remarksResult.Error?.Message ?? "Could not load remarks for the selected Appendix.";
            }
        }

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddRemark(int demandId, int appendixId, string remarkText, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!string.IsNullOrWhiteSpace(remarkText))
        {
            await _preBudgetClient.CreateRemarkAsync(session.Token, new CreatePreBudgetRemarkDto
            {
                DemandId = demandId,
                AppendixId = appendixId,
                FinancialYear = session.FinancialYear,
                RemarkText = remarkText
            }, ct);
        }

        return RedirectToAction(nameof(REDataRemarks), new { demandId, appendixId });
    }

    // App: Pre Budget Meeting | Module: Pre Budget Meeting
    public IActionResult REConsolidated()
    {
        ViewData["Title"] = "RE Consolidated";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Pre Budget Meeting / RE Consolidated";
        return View();
    }

    // App: Pre Budget Meeting | Module: Pre Budget Meeting
    public IActionResult REReportForAllDemand()
    {
        ViewData["Title"] = "RE Report For All Demand ";
        ViewData["Breadcrumb"] = "Pre Budget Meeting / Pre Budget Meeting / RE Report For All Demand ";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}

/// <summary>Wire shape for ExportGrid above - mirrors wwwroot/js/grid-export.js's scraped payload
/// exactly (columns/columnGroups/rows/rightAlignedColumns straight off the live grid DOM, plus the
/// title/subtitle/fileName/format the caller already knows). See TabularReportDto's own doc
/// comments for what each field means once mapped through.</summary>
public class GridExportRequestDto
{
    public string Title { get; set; } = string.Empty;
    public string? Subtitle { get; set; }
    public string? Format { get; set; }
    public string FileName { get; set; } = "report";
    public List<string> Columns { get; set; } = new();
    public List<GridExportColumnGroupDto>? ColumnGroups { get; set; }
    public List<int>? RightAlignedColumns { get; set; }
    public List<string[]> Rows { get; set; } = new();
}

public class GridExportColumnGroupDto
{
    public string? Label { get; set; }
    public int ColumnSpan { get; set; } = 1;
}
