// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class AdhocQueriesController : Controller
{
    // App: Exp Budget(SBE) | Module: Adhoc Queries
    public IActionResult AdhocQueriesReport()
    {
        ViewData["Title"] = "Adhoc Queries Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Adhoc Queries / Adhoc Queries Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Adhoc Queries
    public IActionResult AdhocQueriesStatement18TransferofResources()
    {
        ViewData["Title"] = "Adhoc Queries Statement 18/Transfer of Resources";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Adhoc Queries / Adhoc Queries Statement 18/Transfer of Resources";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Adhoc Queries
    public IActionResult AdhocQueriesforBAAGDetails()
    {
        ViewData["Title"] = "Adhoc Queries for BAAG Details";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Adhoc Queries / Adhoc Queries for BAAG Details";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
