// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class AFSController : Controller
{
    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddAFSForUT()
    {
        ViewData["Title"] = "Add AFS For UT";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add AFS For UT";
        return View();
    }

    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddGroup()
    {
        ViewData["Title"] = "Add Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddScheme()
    {
        ViewData["Title"] = "Add Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddSubScheme()
    {
        ViewData["Title"] = "Add SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddDataforPublicAccount()
    {
        ViewData["Title"] = "Add  Data for Public Account";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add  Data for Public Account";
        return View();
    }

    // App: Exp Budget(SBE) | Module: AFS
    public IActionResult AddCalculatedCashforPublicAccount()
    {
        ViewData["Title"] = "Add Calculated Cash for Public Account";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / AFS / Add Calculated Cash for Public Account";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
