// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class AnnexController : Controller
{
    // App: Exp Budget(SBE) | Module: Annex
    public IActionResult StateMaster()
    {
        ViewData["Title"] = "State Master";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Annex / State Master";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Annex
    public IActionResult TaxValue()
    {
        ViewData["Title"] = "Tax Value";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Annex / Tax Value";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Annex
    public IActionResult StateValue()
    {
        ViewData["Title"] = "State Value";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Annex / State Value";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Annex
    public IActionResult EditAnnexData()
    {
        ViewData["Title"] = "Edit Annex Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Annex / Edit Annex Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Annex
    public IActionResult EditSanctionData()
    {
        ViewData["Title"] = "Edit Sanction Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Annex / Edit Sanction Data";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
