// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class AuditLogController : Controller
{
    // App: Exp Budget(SBE) | Module: Audit Log
    public IActionResult AuditLog()
    {
        ViewData["Title"] = "Audit Log";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Audit Log / Audit Log";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Audit Log
    public IActionResult DeleteAuditErrorLogData()
    {
        ViewData["Title"] = "Delete Audit/Error Log Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Audit Log / Delete Audit/Error Log Data";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
