// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class BAGController : Controller
{
    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult BudgetataGlanceValues()
    {
        ViewData["Title"] = "Budget at a Glance Values";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Budget at a Glance Values";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult TrendOfCapitalExpenditure()
    {
        ViewData["Title"] = "Trend Of Capital Expenditure";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Trend Of Capital Expenditure";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult EconomicParameterfor15to18ofBAAG()
    {
        ViewData["Title"] = "Economic Parameter for 15 to 18 of BAAG ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Economic Parameter for 15 to 18 of BAAG ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult MappingforMajorItems()
    {
        ViewData["Title"] = "Mapping for Major Items";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Mapping for Major Items";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult CompositionOfExpenditure()
    {
        ViewData["Title"] = "Composition Of Expenditure";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Composition Of Expenditure";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult DeficitTrends()
    {
        ViewData["Title"] = "Deficit Trends";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Deficit Trends";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult NetReceiptOfCentre()
    {
        ViewData["Title"] = "Net Receipt Of Centre";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Net Receipt Of Centre";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult RupeesChart()
    {
        ViewData["Title"] = "Rupees Chart";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Rupees Chart";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult TotalTransfersToStates()
    {
        ViewData["Title"] = "Total Transfers To States";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Total Transfers To States";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult TrendInTaxReceipts()
    {
        ViewData["Title"] = "TrendIn Tax Receipts";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / TrendIn Tax Receipts";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult SourcesofDeficitFinancing()
    {
        ViewData["Title"] = "Sources of Deficit Financing";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Sources of Deficit Financing";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult Sector()
    {
        ViewData["Title"] = "Sector";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Sector";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult SubSector()
    {
        ViewData["Title"] = "SubSector";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / SubSector";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult SectorwiseMapping()
    {
        ViewData["Title"] = "Sector wise Mapping";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Sector wise Mapping";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult MajorSchemeMapping()
    {
        ViewData["Title"] = "Major Scheme Mapping";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Major Scheme Mapping";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult AddNotes()
    {
        ViewData["Title"] = "Add Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Add Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: BAG
    public IActionResult EditUnit()
    {
        ViewData["Title"] = "Edit Unit";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / BAG / Edit Unit";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
