// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class DataExchangeController : Controller
{
    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult DGMHwisebeforetransfertoPFMS()
    {
        ViewData["Title"] = "DG MH wise  before transfer to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / DG MH wise  before transfer to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult DGSummarybeforetransfertoPFMS()
    {
        ViewData["Title"] = "DG Summary before transfer to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / DG Summary before transfer to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult DDGDatabeforetransfertoPFMS()
    {
        ViewData["Title"] = "DDG Data before transfer to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / DDG Data before transfer to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ImportActualsFromCGA()
    {
        ViewData["Title"] = "Import Actuals From CGA";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Import Actuals From CGA";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ImportAccountCodeDirectorytoUBIS()
    {
        ViewData["Title"] = "Import Account Code Directory to UBIS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Import Account Code Directory to UBIS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ExportDGMajorHeadWisetoPFMS()
    {
        ViewData["Title"] = "Export DG MajorHead Wise to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Export DG MajorHead Wise to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ExportDGSummarytoPFMS()
    {
        ViewData["Title"] = "Export DG Summary to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Export DG Summary to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ExportDDGDatatoPFMS()
    {
        ViewData["Title"] = "Export DDG Data to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Export DDG Data to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ExportReappropriationtoPFMS()
    {
        ViewData["Title"] = "Export Reappropriation to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Export Reappropriation to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult REandNBEmismatchfortransferringdata()
    {
        ViewData["Title"] = "RE and NBE mismatch for transferring data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / RE and NBE mismatch for transferring data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult FileSharing()
    {
        ViewData["Title"] = "File Sharing";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / File Sharing";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult DirectoryMismatchBeforePushingtoPFMS()
    {
        ViewData["Title"] = "Directory Mismatch Before Pushing  to  PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Directory Mismatch Before Pushing  to  PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult SumMismatchofDDGwithDG()
    {
        ViewData["Title"] = "Sum Mismatch of DDG with DG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Sum Mismatch of DDG with DG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult UpdateConsumedStatus()
    {
        ViewData["Title"] = "Update Consumed Status";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Update Consumed Status";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Exchange
    public IActionResult ExportSupplementaryDatatoPFMS()
    {
        ViewData["Title"] = "Export Supplementary Data to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Exchange / Export Supplementary Data to PFMS";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
