// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class DataEntryController : Controller
{
    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult AddSBE()
    {
        ViewData["Title"] = "Add SBE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Add SBE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult ReAppropriationNew()
    {
        ViewData["Title"] = "ReAppropriation New";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / ReAppropriation New";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult ContingencyAdvanceProposal()
    {
        ViewData["Title"] = "Contingency Advance Proposal";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Contingency Advance Proposal";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult CFINewMinorHead()
    {
        ViewData["Title"] = "CFI New Minor Head";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / CFI New Minor Head";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult SBENotes()
    {
        ViewData["Title"] = "SBE Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / SBE Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult AddChargedRecoveries()
    {
        ViewData["Title"] = "Add Charged/Recoveries";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Add Charged/Recoveries";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult AddPSECategory()
    {
        ViewData["Title"] = "Add PSE Category";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Add PSE Category";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult InvestmentinPSE()
    {
        ViewData["Title"] = "Investment in PSE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Investment in PSE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult ImportActualsFromDDG()
    {
        ViewData["Title"] = "Import Actuals From DDG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Import Actuals From DDG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RenumberSchemeSrNo()
    {
        ViewData["Title"] = "Renumber Scheme SrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Renumber Scheme SrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RenumberSubSchemeSrNo()
    {
        ViewData["Title"] = "Renumber SubScheme SrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Renumber SubScheme SrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RenumberSBENotes()
    {
        ViewData["Title"] = "Renumber SBE Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Renumber SBE Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RenumberPSESrNo()
    {
        ViewData["Title"] = "Renumber PSE SrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Renumber PSE SrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult ReceiptBudgetNTR()
    {
        ViewData["Title"] = "Receipt Budget NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Receipt Budget NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult NotesforNTR()
    {
        ViewData["Title"] = "Notes for NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Notes for NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RequestforIPChange()
    {
        ViewData["Title"] = "Request for IP Change";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Request for IP Change";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult SBEFreeze()
    {
        ViewData["Title"] = "SBE Freeze";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / SBE Freeze";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult CFIInitialization()
    {
        ViewData["Title"] = "CFI Initialization";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / CFI Initialization";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult PendingReappropriations()
    {
        ViewData["Title"] = "Pending Reappropriations";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Pending Reappropriations";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult PrepareDataforPushingtoPFMS()
    {
        ViewData["Title"] = "Prepare Data  for Pushing to PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Prepare Data  for Pushing to PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult CFIDataforSurrenderAmount()
    {
        ViewData["Title"] = "CFI Data for Surrender Amount";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / CFI Data for Surrender Amount";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult RejectSelfApprovedReappropriation()
    {
        ViewData["Title"] = "Reject Self Approved Reappropriation";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Reject Self Approved Reappropriation";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult CancellationofROsFromPFMS()
    {
        ViewData["Title"] = "Cancellation of ROs From PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Cancellation of ROs From PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult SBEPageBreak()
    {
        ViewData["Title"] = "SBE Page Break";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / SBE Page Break";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult DemandSchemeCeilingAllocation()
    {
        ViewData["Title"] = "Demand Scheme Ceiling Allocation";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Demand Scheme Ceiling Allocation";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult DemandSchemeCeilingRelaxation()
    {
        ViewData["Title"] = "Demand Scheme Ceiling Relaxation";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Demand Scheme Ceiling Relaxation";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Data Entry
    public IActionResult ChangePreviousYearBE()
    {
        ViewData["Title"] = "Change Previous Year BE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Data Entry / Change Previous Year BE";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
