// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class IntrimInitializationController : Controller
{
    // App: Exp Budget(SBE) | Module: Intrim Initialization
    public IActionResult SBE()
    {
        ViewData["Title"] = "SBE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Intrim Initialization / SBE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Intrim Initialization
    public IActionResult Statement()
    {
        ViewData["Title"] = "Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Intrim Initialization / Statement";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Intrim Initialization
    public IActionResult RevisedSBEDemandNo()
    {
        ViewData["Title"] = "Revised SBE Demand No";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Intrim Initialization / Revised SBE Demand No";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Intrim Initialization
    public IActionResult RevisedSTMTDemandNo()
    {
        ViewData["Title"] = "Revised STMT Demand No";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Intrim Initialization / Revised STMT Demand No";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
