// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class MachineReadableController : Controller
{
    // App: Exp Budget(SBE) | Module: Machine Readable
    public IActionResult MachineReadableData()
    {
        ViewData["Title"] = "Machine Readable Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Machine Readable / Machine Readable Data";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
