// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class MasterEntryController : Controller
{
    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult Role()
    {
        ViewData["Title"] = "Role";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Role";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult Module()
    {
        ViewData["Title"] = "Module";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Module";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult Function()
    {
        ViewData["Title"] = "Function";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Function";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult RoleModuleMapping()
    {
        ViewData["Title"] = "Role Module Mapping";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Role Module Mapping";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult RoleFunctionMapping()
    {
        ViewData["Title"] = "Role Function Mapping";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Role Function Mapping";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult FinancialYear()
    {
        ViewData["Title"] = "Financial Year";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Financial Year";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult AddMinistry()
    {
        ViewData["Title"] = "Add Ministry";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Add Ministry";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult RenumberMinistry()
    {
        ViewData["Title"] = "Renumber Ministry";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Renumber Ministry";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult AddDepartment()
    {
        ViewData["Title"] = "Add Department";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Add Department";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult RenumberDepartment()
    {
        ViewData["Title"] = "Renumber Department";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Renumber Department";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult AddDemand()
    {
        ViewData["Title"] = "Add Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Add Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult RenumberDemandNo()
    {
        ViewData["Title"] = "Renumber DemandNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Renumber DemandNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult MergeDemandNo()
    {
        ViewData["Title"] = "Merge Demand No";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Merge Demand No";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult DemandSplit()
    {
        ViewData["Title"] = "Demand Split";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Demand Split";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult FAQ()
    {
        ViewData["Title"] = "FAQ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / FAQ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult SonataTemplate()
    {
        ViewData["Title"] = "Sonata Template";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Sonata Template";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Master Entry
    public IActionResult DateTimeStampforSBEReport()
    {
        ViewData["Title"] = "Date Time Stamp for SBE Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Master Entry / Date Time Stamp for SBE Report";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
