// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class MastersController : Controller
{
    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult DebtLiability()
    {
        ViewData["Title"] = "Debt   Liability";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Debt   Liability";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult SBELayout()
    {
        ViewData["Title"] = "SBE Layout";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / SBE Layout";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult PublicDebt()
    {
        ViewData["Title"] = "Public Debt";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Public Debt";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult Securities()
    {
        ViewData["Title"] = "Securities";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Securities";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddCategory()
    {
        ViewData["Title"] = "Add Category";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add Category";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddSubCategory()
    {
        ViewData["Title"] = "Add SubCategory";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add SubCategory";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddSchemes()
    {
        ViewData["Title"] = "Add Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddSubSchemes()
    {
        ViewData["Title"] = "Add Sub Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add Sub Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddUmbrellaSchemes()
    {
        ViewData["Title"] = "Add Umbrella Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add Umbrella Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult AddMajorHead()
    {
        ViewData["Title"] = "Add Major Head";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Add Major Head";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult DemandMajorHeadMapping()
    {
        ViewData["Title"] = "Demand MajorHead Mapping";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Demand MajorHead Mapping";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Masters
    public IActionResult DemandContactDetails()
    {
        ViewData["Title"] = "Demand Contact Details";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Masters / Demand Contact Details";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
