// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class NTRDataEntryController : Controller
{
    // App: Exp Budget(SBE) | Module: NTR Data Entry
    public IActionResult ReceiptBudgetNTRGroupWise()
    {
        ViewData["Title"] = "Receipt Budget NTR Group Wise";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / NTR Data Entry / Receipt Budget NTR Group Wise";
        return View();
    }

    // App: Exp Budget(SBE) | Module: NTR Data Entry
    public IActionResult AddNotesNTR()
    {
        ViewData["Title"] = "Add Notes NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / NTR Data Entry / Add Notes NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: NTR Data Entry
    public IActionResult ReceiptBudgetNTRMHWise()
    {
        ViewData["Title"] = "Receipt Budget NTR MH Wise";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / NTR Data Entry / Receipt Budget NTR MH Wise";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
