// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReceiptBudgetController : Controller
{
    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddGroup()
    {
        ViewData["Title"] = "Add Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddScheme()
    {
        ViewData["Title"] = "Add Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddSubScheme()
    {
        ViewData["Title"] = "Add SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddProgram()
    {
        ViewData["Title"] = "Add Program";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add Program";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddReceiptBudget()
    {
        ViewData["Title"] = "Add Receipt Budget";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add Receipt Budget";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult AddReceiptBudgetNote()
    {
        ViewData["Title"] = "Add Receipt Budget Note";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Add Receipt Budget Note";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult RenumberSchemeSrNo()
    {
        ViewData["Title"] = "Renumber SchemeSrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Renumber SchemeSrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult RenumberSubSchemeSrNo()
    {
        ViewData["Title"] = "Renumber SubScheme SrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Renumber SubScheme SrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult RenumberProgramSrNo()
    {
        ViewData["Title"] = "Renumber Program SrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Renumber Program SrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult RenumberSubProgramSrNo()
    {
        ViewData["Title"] = "Renumber SubProgramSrNo";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Renumber SubProgramSrNo";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Receipt Budget
    public IActionResult RenumberReceiptNotes()
    {
        ViewData["Title"] = "Renumber Receipt Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Receipt Budget / Renumber Receipt Notes";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
