// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsREController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports RE
    public IActionResult REDataandReport()
    {
        ViewData["Title"] = "RE Data and Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports RE / RE Data and Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports RE
    public IActionResult REConsolidated()
    {
        ViewData["Title"] = "RE Consolidated";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports RE / RE Consolidated";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports RE
    public IActionResult REReportForAllDemand()
    {
        ViewData["Title"] = "RE Report For All Demand ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports RE / RE Report For All Demand ";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
