// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsBAGController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports BAG
    public IActionResult AllBudgetataGlanceReport()
    {
        ViewData["Title"] = "All Budget at a Glance Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports BAG / All Budget at a Glance Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports BAG
    public IActionResult GraphicalChart()
    {
        ViewData["Title"] = "Graphical Chart";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports BAG / Graphical Chart";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
