// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsVOAController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports VOA
    public IActionResult VoteonAccountInterim()
    {
        ViewData["Title"] = "Vote on Account (Interim)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports VOA / Vote on Account (Interim)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports VOA
    public IActionResult VoteonAccountRegular()
    {
        ViewData["Title"] = "Vote on Account (Regular)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports VOA / Vote on Account (Regular)";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
