// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsECLController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports ECL
    public IActionResult DataAnalysis()
    {
        ViewData["Title"] = "Data Analysis";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports ECL / Data Analysis";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports ECL
    public IActionResult DemandWiseECLStatus()
    {
        ViewData["Title"] = "Demand Wise ECL Status ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports ECL / Demand Wise ECL Status ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports ECL
    public IActionResult PendingDemand()
    {
        ViewData["Title"] = "Pending Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports ECL / Pending Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports ECL
    public IActionResult DemandWiseECLStatusTopLine()
    {
        ViewData["Title"] = "Demand Wise ECL Status Top Line";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports ECL / Demand Wise ECL Status Top Line";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
