// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsStatementController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult StatementReport()
    {
        ViewData["Title"] = "Statement Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Statement Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult CheckBEDifferenceforStatement()
    {
        ViewData["Title"] = "Check BE Difference  for Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Check BE Difference  for Statement";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult AdhocQueriesforStatement18()
    {
        ViewData["Title"] = "Adhoc Queries for Statement 18";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Adhoc Queries for Statement 18";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult AllStatementReports()
    {
        ViewData["Title"] = "All Statement Reports";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / All Statement Reports";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult StatementReportsDirectlyGeneratedFromDDG()
    {
        ViewData["Title"] = "Statement Reports Directly Generated From DDG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Statement Reports Directly Generated From DDG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult RailwayStatementsReport()
    {
        ViewData["Title"] = "Railway Statements Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Railway Statements Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Statement
    public IActionResult GenerateZipforAllStatement()
    {
        ViewData["Title"] = "Generate Zip for All Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Statement / Generate Zip for All Statement";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
