// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Asset Register";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult GenerateDG()
    {
        ViewData["Title"] = "Generate DG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Generate DG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult ArrearsOfNTR()
    {
        ViewData["Title"] = "Arrears Of NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Arrears Of NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult GenerateSBEUserWise()
    {
        ViewData["Title"] = "Generate SBE UserWise";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Generate SBE UserWise";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult InvestmentInPSEReport()
    {
        ViewData["Title"] = "Investment In PSE Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Investment In PSE Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult ReceiptRecoveryChargedReport()
    {
        ViewData["Title"] = "Receipt/Recovery/Charged Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Receipt/Recovery/Charged Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult SBEReportWithoutData()
    {
        ViewData["Title"] = "SBE Report Without Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / SBE Report Without Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult NTR()
    {
        ViewData["Title"] = "NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult VoteonAccount()
    {
        ViewData["Title"] = "Vote on Account";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Vote on Account";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult DemandCeilingValidationsChecklist()
    {
        ViewData["Title"] = "Demand Ceiling Validations Checklist";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Demand Ceiling Validations Checklist";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult REandNBEsummismatchfortransferringdata()
    {
        ViewData["Title"] = "RE and NBE sum mismatch for transferring data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / RE and NBE sum mismatch for transferring data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult GenerateSBE()
    {
        ViewData["Title"] = "Generate SBE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Generate SBE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult GenerateSBESSRS()
    {
        ViewData["Title"] = "Generate SBE (SSRS)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Generate SBE (SSRS)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult DGSummary()
    {
        ViewData["Title"] = "DG Summary";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / DG Summary";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult CombinedAPartTopLines()
    {
        ViewData["Title"] = "Combined A Part Top Lines";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Combined A Part Top Lines";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult MajorHeadDemandCategoryWiseSchemeSubScheme()
    {
        ViewData["Title"] = "	MajorHead/Demand/Category Wise Scheme/SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / 	MajorHead/Demand/Category Wise Scheme/SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult SBEBEDifference()
    {
        ViewData["Title"] = "SBE BE Difference ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / SBE BE Difference ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult InvestmentInPSE()
    {
        ViewData["Title"] = "Investment In PSE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Investment In PSE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult GenerateSBEfromOtherSource()
    {
        ViewData["Title"] = "Generate SBE from Other Source";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Generate SBE from Other Source";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult DemandSchemeCeillingAllocation()
    {
        ViewData["Title"] = "Demand Scheme Ceilling Allocation";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Demand Scheme Ceilling Allocation";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult RelaxedSchemesUnderECL()
    {
        ViewData["Title"] = "Relaxed Schemes Under ECL ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Relaxed Schemes Under ECL ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult CategoryWiseSchemes()
    {
        ViewData["Title"] = "Category Wise Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Category Wise Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult SBEReportInExcel()
    {
        ViewData["Title"] = "SBE Report In Excel";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / SBE Report In Excel";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult AFS()
    {
        ViewData["Title"] = "AFS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / AFS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult Receipts()
    {
        ViewData["Title"] = "Receipts";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Receipts";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult ReceiptsSSRS()
    {
        ViewData["Title"] = "Receipts(SSRS)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Receipts(SSRS)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult VoteonAccountInterim()
    {
        ViewData["Title"] = "Vote on Account (Interim)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Vote on Account (Interim)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult VoteonAccountRegular()
    {
        ViewData["Title"] = "Vote on Account (Regular)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Vote on Account (Regular)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult ReceiptNTR()
    {
        ViewData["Title"] = "Receipt NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Receipt NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult AnnexReport()
    {
        ViewData["Title"] = "Annex Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Annex Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult SanctionReport()
    {
        ViewData["Title"] = "Sanction Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Sanction Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports
    public IActionResult CumalativeSanctionDevolutionReport()
    {
        ViewData["Title"] = "Cumalative Sanction Devolution Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports / Cumalative Sanction Devolution Report";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
