// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsAFSController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports AFS
    public IActionResult AFS()
    {
        ViewData["Title"] = "AFS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports AFS / AFS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports AFS
    public IActionResult Receipts()
    {
        ViewData["Title"] = "Receipts";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports AFS / Receipts";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports AFS
    public IActionResult ReceiptsSSRS()
    {
        ViewData["Title"] = "Receipts(SSRS)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports AFS / Receipts(SSRS)";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
