// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsReceiptController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / Asset Register";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult AssetRegisterAnalytics()
    {
        ViewData["Title"] = "Asset Register Analytics";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / Asset Register Analytics";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult ArrearsOfNTR()
    {
        ViewData["Title"] = "Arrears Of NTR";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / Arrears Of NTR";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult ArrearsOfNTRAnalyticsReport()
    {
        ViewData["Title"] = "Arrears Of NTR Analytics Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / Arrears Of NTR Analytics Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult NSSFStmtNoThreeReport()
    {
        ViewData["Title"] = "NSSF(Stmt No Three) Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / NSSF(Stmt No Three) Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Receipt
    public IActionResult NSSFAnnexVIIISSRS()
    {
        ViewData["Title"] = "NSSF Annex VIII(SSRS)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Receipt / NSSF Annex VIII(SSRS)";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
