// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsDDGController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult GenerateDDG()
    {
        ViewData["Title"] = "Generate DDG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / Generate DDG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult StatusofDDGDemand()
    {
        ViewData["Title"] = "Status of DDG Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / Status of DDG Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult MismatchSummaryofDDGwithSBE()
    {
        ViewData["Title"] = "Mismatch Summary of DDG with SBE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / Mismatch Summary of DDG with SBE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult SBESchemesnotmapped()
    {
        ViewData["Title"] = "SBE Schemes not mapped";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / SBE Schemes not mapped";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult DDGHeadofAccountsnotmapped()
    {
        ViewData["Title"] = "DDG Head of Accounts not mapped";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / DDG Head of Accounts not mapped";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult HOAnotInDDG()
    {
        ViewData["Title"] = "HOA not In DDG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / HOA not In DDG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult HOAnotInPFMS()
    {
        ViewData["Title"] = "HOA not In PFMS";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / HOA not In PFMS";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult DemandCeilingValidationsChecklist()
    {
        ViewData["Title"] = "Demand Ceiling Validations Checklist";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / Demand Ceiling Validations Checklist";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult REandNBEsummismatchfortransferringdata()
    {
        ViewData["Title"] = "RE and NBE sum mismatch for transferring data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / RE and NBE sum mismatch for transferring data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports DDG
    public IActionResult SumMismatchofDDGwithDG()
    {
        ViewData["Title"] = "Sum Mismatch of DDG with DG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports DDG / Sum Mismatch of DDG with DG";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
