// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsSupplementaryController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult GenerateSupplementaryApprovedbySD()
    {
        ViewData["Title"] = "Generate Supplementary (Approved by SD)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Generate Supplementary (Approved by SD)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult GenerateSupplementaryWithLineBreak()
    {
        ViewData["Title"] = "Generate Supplementary With Line Break";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Generate Supplementary With Line Break";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult SupplementaryReportsMiscellaneous()
    {
        ViewData["Title"] = "Supplementary Reports (Miscellaneous)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Supplementary Reports (Miscellaneous)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult CheckSheet()
    {
        ViewData["Title"] = "Check Sheet";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Check Sheet";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult ReporttoParliamentAnnexure()
    {
        ViewData["Title"] = "Report to Parliament Annexure";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Report to Parliament Annexure";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports Supplementary
    public IActionResult PreviousSupplementaryDemandWise()
    {
        ViewData["Title"] = "Previous Supplementary DemandWise";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports Supplementary / Previous Supplementary DemandWise";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
