// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class ReportsUBISController : Controller
{
    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateSBE()
    {
        ViewData["Title"] = "Generate SBE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate SBE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult CombinedAPartTopLines()
    {
        ViewData["Title"] = "Combined A Part Top Lines";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Combined A Part Top Lines";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult ReceiptReport()
    {
        ViewData["Title"] = "Receipt Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Receipt Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult RecoveryReport()
    {
        ViewData["Title"] = "Recovery Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Recovery Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult DemandWiseSchemeSubScheme()
    {
        ViewData["Title"] = "Demand Wise Scheme/SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Demand Wise Scheme/SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult CategoryWiseSchemeSubscheme()
    {
        ViewData["Title"] = "Category Wise Scheme/Subscheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Category Wise Scheme/Subscheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult DGSummary()
    {
        ViewData["Title"] = "DG Summary";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / DG Summary";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateDG()
    {
        ViewData["Title"] = "Generate DG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate DG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult ChargedReport()
    {
        ViewData["Title"] = "Charged Report";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Charged Report";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult MajorHeadWiseSchemeSubScheme()
    {
        ViewData["Title"] = "MajorHeadWise Scheme/SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / MajorHeadWise Scheme/SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateSBESSRS()
    {
        ViewData["Title"] = "Generate SBE (SSRS)";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate SBE (SSRS)";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult SBEBEDifference()
    {
        ViewData["Title"] = "SBE BE Difference ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / SBE BE Difference ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult SBEReportWithoutData()
    {
        ViewData["Title"] = "SBE Report Without Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / SBE Report Without Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult InvestmentInPSE()
    {
        ViewData["Title"] = "Investment In PSE";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Investment In PSE";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateSBEfromOtherSource()
    {
        ViewData["Title"] = "Generate SBE from Other Source";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate SBE from Other Source";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateZipforAllDGDemand()
    {
        ViewData["Title"] = "Generate Zip for All DG Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate Zip for All DG Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult GenerateZipforAllSBEDemand()
    {
        ViewData["Title"] = "Generate Zip for All SBE Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / Generate Zip for All SBE Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Reports UBIS
    public IActionResult SBEReportinExcel()
    {
        ViewData["Title"] = "SBE Report in Excel";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Reports UBIS / SBE Report in Excel";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
