// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UBISInitializationController : Controller
{
    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult MinistryDepartmentDemand()
    {
        ViewData["Title"] = "Ministry/Department/Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Ministry/Department/Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult UserInitialization()
    {
        ViewData["Title"] = "User Initialization";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / User Initialization";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult UserDetailsInitialization()
    {
        ViewData["Title"] = "User Details Initialization";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / User Details Initialization";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult Master()
    {
        ViewData["Title"] = "Master";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Master";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult SBECaption()
    {
        ViewData["Title"] = "SBE Caption";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / SBE Caption";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult SBECaptiondata()
    {
        ViewData["Title"] = "SBE Caption data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / SBE Caption data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult SBENotes()
    {
        ViewData["Title"] = "SBE Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / SBE Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult SBEData()
    {
        ViewData["Title"] = "SBE Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / SBE Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult RecoveriesChargedData()
    {
        ViewData["Title"] = "Recoveries Charged Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Recoveries Charged Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult BudgetarySupportIEBRData()
    {
        ViewData["Title"] = "Budgetary SupportIEBR Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Budgetary SupportIEBR Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult DDG()
    {
        ViewData["Title"] = "DDG";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / DDG";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult Statement()
    {
        ViewData["Title"] = "Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Statement";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult PAAccount()
    {
        ViewData["Title"] = "PA Account";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / PA Account";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult Receipt()
    {
        ViewData["Title"] = "Receipt";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Receipt";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult ReceiptDataNotes()
    {
        ViewData["Title"] = "Receipt Data/Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Receipt Data/Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult ReceiptStatement()
    {
        ViewData["Title"] = "Receipt Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Receipt Statement";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult AssetRegister()
    {
        ViewData["Title"] = "Asset Register ";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / Asset Register ";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult NTRBudget()
    {
        ViewData["Title"] = "NTR Budget";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / NTR Budget";
        return View();
    }

    // App: Exp Budget(SBE) | Module: UBIS Initialization
    public IActionResult BAGData()
    {
        ViewData["Title"] = "BAG Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / UBIS Initialization / BAG Data";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
