// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UpdateNSSFMasterController : Controller
{
    // App: Exp Budget(SBE) | Module: Update NSSF Master
    public IActionResult EditNSSFGroup()
    {
        ViewData["Title"] = "Edit NSSF Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update NSSF Master / Edit NSSF Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update NSSF Master
    public IActionResult EditNSSFScheme()
    {
        ViewData["Title"] = "Edit NSSF Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update NSSF Master / Edit NSSF Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update NSSF Master
    public IActionResult EditNSSFSubScheme()
    {
        ViewData["Title"] = "Edit  NSSF SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update NSSF Master / Edit  NSSF SubScheme";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
