// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UpdateHindiPAReceiptController : Controller
{
    // App: Exp Budget(SBE) | Module: Update Hindi PA Receipt
    public IActionResult Group()
    {
        ViewData["Title"] = "Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi PA Receipt / Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi PA Receipt
    public IActionResult Scheme()
    {
        ViewData["Title"] = "Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi PA Receipt / Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi PA Receipt
    public IActionResult SubScheme()
    {
        ViewData["Title"] = "Sub Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi PA Receipt / Sub Scheme";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
