// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UpdateHindiStatementsController : Controller
{
    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult Group()
    {
        ViewData["Title"] = "Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult Scheme()
    {
        ViewData["Title"] = "Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult SubScheme()
    {
        ViewData["Title"] = "Sub Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Sub Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult SpecialSchemeStmt78and18()
    {
        ViewData["Title"] = "Special Scheme ( Stmt 7, 8 and 18 )";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Special Scheme ( Stmt 7, 8 and 18 )";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult StatementWiseGroup()
    {
        ViewData["Title"] = "Statement Wise Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Statement Wise Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult Statementwisescheme()
    {
        ViewData["Title"] = "Statement wise scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Statement wise scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult StatementWiseSubscheme()
    {
        ViewData["Title"] = "Statement Wise Subscheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Statement Wise Subscheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult _10A10Band10BBStatementwiseScheme()
    {
        ViewData["Title"] = "10A10B and 10BB Statement wise Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / 10A10B and 10BB Statement wise Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult _10A10Band10BBStatementwiseSubScheme()
    {
        ViewData["Title"] = "10A10B and 10BB Statement wise SubScheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / 10A10B and 10BB Statement wise SubScheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult Statement17()
    {
        ViewData["Title"] = "Statement 17";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Statement 17";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Statements
    public IActionResult Hindifor4A()
    {
        ViewData["Title"] = "Hindi for 4A";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Statements / Hindi for 4A";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
