// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UpdateHindiReceiptBudgetController : Controller
{
    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult Scheme()
    {
        ViewData["Title"] = "Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult SubScheme()
    {
        ViewData["Title"] = "Sub Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Sub Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult Group()
    {
        ViewData["Title"] = "Group";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Group";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult Program()
    {
        ViewData["Title"] = "Program";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Program";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult SubProgramme()
    {
        ViewData["Title"] = "Sub Programme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Sub Programme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi  Receipt Budget
    public IActionResult ReceiptNotes()
    {
        ViewData["Title"] = "Receipt Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi  Receipt Budget / Receipt Notes";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
