// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UpdateHindiBudgetMasterController : Controller
{
    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult Category()
    {
        ViewData["Title"] = "Category";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Category";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult SubCategory()
    {
        ViewData["Title"] = "SubCategory";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / SubCategory";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult UmbrellaScheme()
    {
        ViewData["Title"] = "Umbrella Scheme";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Umbrella Scheme";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult Schemes()
    {
        ViewData["Title"] = " Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master /  Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult SubSchemes()
    {
        ViewData["Title"] = "Sub Schemes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Sub Schemes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult MajorHead()
    {
        ViewData["Title"] = "Major Head";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Major Head";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult SBENotes()
    {
        ViewData["Title"] = "SBE Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / SBE Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult PSECategory()
    {
        ViewData["Title"] = "PSE Category";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / PSE Category";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult InvestmentPSEName()
    {
        ViewData["Title"] = "Investment PSE Name";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Investment PSE Name";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult AddMinistry()
    {
        ViewData["Title"] = "Add Ministry";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Add Ministry";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult AddDepartment()
    {
        ViewData["Title"] = "Add Department";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Add Department";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult AddDemand()
    {
        ViewData["Title"] = "Add Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Add Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult EditHindiHOA()
    {
        ViewData["Title"] = "Edit Hindi HOA";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Edit Hindi HOA";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult GenerateSBEInExcel()
    {
        ViewData["Title"] = "Generate SBE In Excel";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Generate SBE In Excel";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult MajorHeadGroupName()
    {
        ViewData["Title"] = "Major Head Group Name";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Major Head Group Name";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult EditHindiSBEData()
    {
        ViewData["Title"] = "Edit Hindi SBE Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Edit Hindi SBE Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: Update Hindi Budget Master
    public IActionResult ObjectHead()
    {
        ViewData["Title"] = "Object Head";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / Update Hindi Budget Master / Object Head";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
