// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class UserController : Controller
{
    // App: Exp Budget(SBE) | Module: User
    public IActionResult CreateUser()
    {
        ViewData["Title"] = "Create User";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Create User";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult EditUserDetails()
    {
        ViewData["Title"] = "Edit User Details";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Edit User Details";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult ResetPassword()
    {
        ViewData["Title"] = "Reset Password";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Reset Password";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult AppandUserWiseFreezeFunction()
    {
        ViewData["Title"] = "App and User Wise Freeze Function";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / App and User Wise Freeze Function";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult UserWiseChangeDemand()
    {
        ViewData["Title"] = "User Wise Change Demand";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / User Wise Change Demand";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult DeletePreviousYearLogData()
    {
        ViewData["Title"] = "Delete Previous Year Log Data";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Delete Previous Year Log Data";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult ChangeStatementsForUser()
    {
        ViewData["Title"] = "Change Statements For User";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Change Statements For User";
        return View();
    }

    // App: Exp Budget(SBE) | Module: User
    public IActionResult ActivateDeactivateUsers()
    {
        ViewData["Title"] = "Activate Deactivate Users";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / User / Activate Deactivate Users";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
