// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpBudgetSBE.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpBudgetSBE")]
[Authorize]
public class VOAController : Controller
{
    // App: Exp Budget(SBE) | Module: VOA
    public IActionResult CommitedLiablities()
    {
        ViewData["Title"] = "Commited Liablities";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / VOA / Commited Liablities";
        return View();
    }

    // App: Exp Budget(SBE) | Module: VOA
    public IActionResult SchemetobeExcludedfromVOA()
    {
        ViewData["Title"] = "Scheme to be Excluded from VOA";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / VOA / Scheme to be Excluded from VOA";
        return View();
    }

    // App: Exp Budget(SBE) | Module: VOA
    public IActionResult IntroNotes()
    {
        ViewData["Title"] = "Intro Notes";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / VOA / Intro Notes";
        return View();
    }

    // App: Exp Budget(SBE) | Module: VOA
    public IActionResult ControlStatement()
    {
        ViewData["Title"] = "Control Statement";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / VOA / Control Statement";
        return View();
    }

    // App: Exp Budget(SBE) | Module: VOA
    public IActionResult DemandAllocation()
    {
        ViewData["Title"] = "Demand Allocation";
        ViewData["Breadcrumb"] = "Exp Budget(SBE) / VOA / Demand Allocation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
