// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpProfile.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpProfile")]
[Authorize]
public class AllocationController : Controller
{
    // App: Exp Profile | Module: Allocation
    public IActionResult REMeetingAllocation()
    {
        ViewData["Title"] = "RE Meeting Allocation";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / RE Meeting Allocation";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult StatementAllocation()
    {
        ViewData["Title"] = "Statement Allocation";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Statement Allocation";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult UserAllocation()
    {
        ViewData["Title"] = "User  Allocation";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / User  Allocation";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult RailwayAllocation()
    {
        ViewData["Title"] = "Railway Allocation";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Railway Allocation";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult ActualsBECategoryChangePermission()
    {
        ViewData["Title"] = "Actuals/BE/Category Change Permission";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Actuals/BE/Category Change Permission";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult PermissionReport()
    {
        ViewData["Title"] = "Permission Report";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Permission Report";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult ApproveIPAddresses()
    {
        ViewData["Title"] = "Approve IP Addresses";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Approve IP Addresses";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult FreezeUnfreezeDemandStatementWise()
    {
        ViewData["Title"] = "Freeze/ Unfreeze Demand Statement Wise";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Freeze/ Unfreeze Demand Statement Wise";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult FreezeUnfreezeSBE()
    {
        ViewData["Title"] = "Freeze/Unfreeze SBE";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Freeze/Unfreeze SBE";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult EnableBEEditPermission()
    {
        ViewData["Title"] = "Enable BE Edit Permission";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / Enable BE Edit Permission";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / SBE Line Entry Delete Permission";
        return View();
    }

    // App: Exp Profile | Module: Allocation
    public IActionResult VoAAllocation()
    {
        ViewData["Title"] = "VoA Allocation";
        ViewData["Breadcrumb"] = "Exp Profile / Allocation / VoA Allocation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
