// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpProfile.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpProfile")]
[Authorize]
public class DashboardController : Controller
{
    // App: Exp Profile | Module: Dashboard
    public IActionResult CombinedDashboard()
    {
        ViewData["Title"] = "Combined Dashboard";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Combined Dashboard";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult Circular()
    {
        ViewData["Title"] = "Circular";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Circular";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult ListofCirculars()
    {
        ViewData["Title"] = "List of Circulars";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / List of Circulars";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult SelectDemand()
    {
        ViewData["Title"] = "Select Demand";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Select Demand";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult CreateCircularLetter()
    {
        ViewData["Title"] = "Create Circular/Letter";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Create Circular/Letter";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult CircularReport()
    {
        ViewData["Title"] = "Circular Report";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Circular Report";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult SBEStatusReport()
    {
        ViewData["Title"] = "SBE Status Report";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / SBE Status Report";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult DemIdDemNoMismatch()
    {
        ViewData["Title"] = "DemId DemNo Mismatch";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / DemId DemNo Mismatch";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult FileSharing()
    {
        ViewData["Title"] = "File Sharing";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / File Sharing";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult ViewFileSharing()
    {
        ViewData["Title"] = "View File Sharing";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / View File Sharing";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult SectionWiseDemandReport()
    {
        ViewData["Title"] = "Section Wise Demand Report";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Section Wise Demand Report";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult SelectDemandSectionWise()
    {
        ViewData["Title"] = "Select  Demand Section Wise";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / Select  Demand Section Wise";
        return View();
    }

    // App: Exp Profile | Module: Dashboard
    public IActionResult SBELineEntryDeletePermission()
    {
        ViewData["Title"] = "SBE Line Entry Delete Permission";
        ViewData["Breadcrumb"] = "Exp Profile / Dashboard / SBE Line Entry Delete Permission";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
