// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpProfile.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpProfile")]
[Authorize]
public class RailwaysController : Controller
{
    // App: Exp Profile | Module: Railways
    public IActionResult RailwaystatementEntry()
    {
        ViewData["Title"] = "Railway statement Entry";
        ViewData["Breadcrumb"] = "Exp Profile / Railways / Railway statement Entry";
        return View();
    }

    // App: Exp Profile | Module: Railways
    public IActionResult RailwayStatementsReport()
    {
        ViewData["Title"] = "Railway Statements Report";
        ViewData["Breadcrumb"] = "Exp Profile / Railways / Railway Statements Report";
        return View();
    }

    // App: Exp Profile | Module: Railways
    public IActionResult OperationRatio()
    {
        ViewData["Title"] = "Operation Ratio";
        ViewData["Breadcrumb"] = "Exp Profile / Railways / Operation Ratio";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
