// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpProfile.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpProfile")]
[Authorize]
public class StatementController : Controller
{
    // App: Exp Profile | Module: Statement
    public IActionResult StatementEntry()
    {
        ViewData["Title"] = "Statement Entry";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Statement Entry";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult AddStatementNotes()
    {
        ViewData["Title"] = "Add Statement Notes";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Add Statement Notes";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult ReceiptStatementEntry()
    {
        ViewData["Title"] = "Receipt Statement Entry";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Receipt Statement Entry";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult MappingofStatement78and18()
    {
        ViewData["Title"] = "Mapping of Statement 7, 8 and 18";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Mapping of Statement 7, 8 and 18";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult StatementLayout()
    {
        ViewData["Title"] = "Statement Layout";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Statement Layout";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult RenumberUmbrellaSrNo()
    {
        ViewData["Title"] = "Renumber Umbrella SrNo";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Renumber Umbrella SrNo";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult SchemesMasterForStmt78and18()
    {
        ViewData["Title"] = "Schemes Master For Stmt 7,8 and 18";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Schemes Master For Stmt 7,8 and 18";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult EditSubSchemeName()
    {
        ViewData["Title"] = "Edit SubScheme Name";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Edit SubScheme Name";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult EditSchemeName()
    {
        ViewData["Title"] = "Edit Scheme Name";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Edit Scheme Name";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult MappingforStatement4A()
    {
        ViewData["Title"] = "Mapping for Statement 4A";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Mapping for Statement 4A";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult EditDepictedSchemeNameHindifor4A()
    {
        ViewData["Title"] = "Edit Depicted Scheme Name/Hindi for 4A";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Edit Depicted Scheme Name/Hindi for 4A";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult MappingforStatement12and13()
    {
        ViewData["Title"] = "Mapping for Statement 12 and 13";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Mapping for Statement 12 and 13";
        return View();
    }

    // App: Exp Profile | Module: Statement
    public IActionResult ChangeActualsandPreviousBEforStmt12and13()
    {
        ViewData["Title"] = "Change Actuals and Previous BE for Stmt 12 and 13";
        ViewData["Breadcrumb"] = "Exp Profile / Statement / Change Actuals and Previous BE for Stmt 12 and 13";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
