// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ExpProfile.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ExpProfile")]
[Authorize]
public class StatementReportsController : Controller
{
    // App: Exp Profile | Module: Statement Reports
    public IActionResult StatementReport()
    {
        ViewData["Title"] = "Statement Report";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Statement Report";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult CheckBEDifferenceforStatement()
    {
        ViewData["Title"] = "Check BE Difference  for Statement";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Check BE Difference  for Statement";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult AdhocQueriesforStatement18()
    {
        ViewData["Title"] = "Adhoc Queries for Statement 18";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Adhoc Queries for Statement 18";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult AllStatementReports()
    {
        ViewData["Title"] = "All Statement Reports";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / All Statement Reports";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult StatementReportsDirectlyGeneratedFromDDG()
    {
        ViewData["Title"] = "Statement Reports Directly Generated From DDG";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Statement Reports Directly Generated From DDG";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult Statement2Aand2BinExcel()
    {
        ViewData["Title"] = "Statement 2A and 2B in Excel";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Statement 2A and 2B in Excel";
        return View();
    }

    // App: Exp Profile | Module: Statement Reports
    public IActionResult StatementInExcel()
    {
        ViewData["Title"] = "Statement In Excel";
        ViewData["Breadcrumb"] = "Exp Profile / Statement Reports / Statement In Excel";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
