// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.NSModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("NSModule")]
[Authorize]
public class NSEntryController : Controller
{
    // App: NSModule | Module: NS Entry
    public IActionResult NationalSmallSavingScheme()
    {
        ViewData["Title"] = "National Small Saving Scheme ";
        ViewData["Breadcrumb"] = "NSModule / NS Entry / National Small Saving Scheme ";
        return View();
    }

    // App: NSModule | Module: NS Entry
    public IActionResult Annex8SourcesapplicationofNSSF()
    {
        ViewData["Title"] = "Annex8-Sources & application of NSSF";
        ViewData["Breadcrumb"] = "NSModule / NS Entry / Annex8-Sources & application of NSSF";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
