// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.NSModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("NSModule")]
[Authorize]
public class NSReportsController : Controller
{
    // App: NSModule | Module: NS Reports
    public IActionResult NSSFAnnexVIIISSRS()
    {
        ViewData["Title"] = "NSSF Annex VIII(SSRS)";
        ViewData["Breadcrumb"] = "NSModule / NS Reports / NSSF Annex VIII(SSRS)";
        return View();
    }

    // App: NSModule | Module: NS Reports
    public IActionResult NSSFStmtNoThreeReport()
    {
        ViewData["Title"] = "NSSF(Stmt No Three) Report";
        ViewData["Breadcrumb"] = "NSModule / NS Reports / NSSF(Stmt No Three) Report";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
