// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
//
// DataToApprove (FunctionId 554) and DataForReapproval (FunctionId 557) below were filled in for
// the ECL DOE-approval front-end (Part 2, 2026-08-18). Both are DOE-only screens: gated here via
// session.HasPermission (menu-driven) AND independently rejected server-side by
// EclApprovalController's RequireDoeRoleFilter (DoeRoleIds 55/13) if a non-DOE caller somehow
// reaches the API directly — defense in depth, this controller is not the only gate. Every other
// action in this file is an unrelated HR/Autonomous-Grantee-Body feature, left untouched.
#nullable enable
namespace UBIS.Web.Areas.ECL.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UBIS.Web.Areas.ECL.Models;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("ECL")]
[Authorize]
public class ECLApproveController : Controller
{
    private const int DataToApproveFunctionId = 554;
    private const int DataForReapprovalFunctionId = 557;

    private readonly IEclClient _eclClient;
    private readonly IAimClient _aimClient;

    public ECLApproveController(IEclClient eclClient, IAimClient aimClient)
    {
        _eclClient = eclClient;
        _aimClient = aimClient;
    }

    // App: ECL | Module: ECL Approve (FunctionId 554, DOE-only)
    [HttpGet]
    public async Task<IActionResult> DataToApprove(int? demandId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data To Approve";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(DataToApproveFunctionId))
        {
            return Forbid();
        }

        var model = await BuildGridAsync(session, "ECL - Data To Approve", demandId, financialYear, reapprovalOnly: false, pendingOnly: true, ct, defaultToFirstDemandWhenUnset: true);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Approve(int rowId, int? demandId, string? financialYear, Dictionary<int, string>? remarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(DataToApproveFunctionId))
        {
            return Forbid();
        }

        string? doeRemarks = null;
        remarks?.TryGetValue(rowId, out doeRemarks);
        var result = await _eclClient.ApproveAsync(session.Token, rowId, doeRemarks, ct);

        var model = await BuildGridAsync(session, "ECL - Data To Approve", demandId, financialYear, reapprovalOnly: false, pendingOnly: true, ct, defaultToFirstDemandWhenUnset: true);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess ? "Row approved." : result.Error?.Message ?? "Could not approve this row.";
        model.IsSaveResult = true;

        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data To Approve";
        return View("DataToApprove", model);
    }

    /// <summary>Reject requires DOERemarks — mirrors the API's own RejectionRequiresRemarks
    /// validation (surfaced as a 400 from EclApprovalController.Reject when DoeRemarks is blank);
    /// ecl.js's initApprovalGrid() blocks the empty-remarks submit client-side first, but
    /// this server round trip still shows the API's own message if that's ever bypassed.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Reject(int rowId, int? demandId, string? financialYear, Dictionary<int, string>? remarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(DataToApproveFunctionId))
        {
            return Forbid();
        }

        string? doeRemarks = null;
        remarks?.TryGetValue(rowId, out doeRemarks);
        var result = await _eclClient.RejectAsync(session.Token, rowId, doeRemarks, ct);

        var model = await BuildGridAsync(session, "ECL - Data To Approve", demandId, financialYear, reapprovalOnly: false, pendingOnly: true, ct, defaultToFirstDemandWhenUnset: true);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess ? "Row rejected." : result.Error?.Message ?? "Could not reject this row.";
        model.IsSaveResult = true;

        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data To Approve";
        return View("DataToApprove", model);
    }

    /// <summary>Bulk Approve, driven by the checkbox column added to DataToApprove (client request
    /// 2026-08-21) — loops the same single-row ApproveAsync the per-row Approve button already uses,
    /// one call per selected rowId, rather than a new bulk API endpoint (ECL's API has no bulk
    /// approve/reject operation and this list is small enough that N sequential calls is fine).</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ApproveSelected(int[] rowIds, int? demandId, string? financialYear, Dictionary<int, string>? remarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var failures = new List<string>();
        foreach (var rowId in rowIds ?? Array.Empty<int>())
        {
            string? rowRemarks = null;
            remarks?.TryGetValue(rowId, out rowRemarks);
            var result = await _eclClient.ApproveAsync(session.Token, rowId, rowRemarks, ct);
            if (!result.IsSuccess)
            {
                failures.Add($"Row {rowId}: {result.Error?.Message ?? "Could not approve."}");
            }
        }

        var model = await BuildGridAsync(session, "ECL - Data To Approve", demandId, financialYear, reapprovalOnly: false, pendingOnly: true, ct, defaultToFirstDemandWhenUnset: true);
        model.StatusIsError = failures.Count > 0;
        model.StatusMessage = failures.Count > 0
            ? "Some rows could not be approved - " + string.Join("; ", failures)
            : $"{(rowIds ?? Array.Empty<int>()).Length} row(s) approved.";
        model.IsSaveResult = true;

        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data To Approve";
        return View("DataToApprove", model);
    }

    /// <summary>Bulk Reject counterpart to <see cref="ApproveSelected"/> — each selected row must
    /// have its own DOE Remarks filled in (same RejectionRequiresRemarks rule as the per-row Reject
    /// button) or that row is skipped and reported as a failure rather than silently rejected with
    /// no reason.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> RejectSelected(int[] rowIds, int? demandId, string? financialYear, Dictionary<int, string>? remarks, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        var failures = new List<string>();
        var rejectedCount = 0;
        foreach (var rowId in rowIds ?? Array.Empty<int>())
        {
            string? rowRemarks = null;
            remarks?.TryGetValue(rowId, out rowRemarks);
            if (string.IsNullOrWhiteSpace(rowRemarks))
            {
                failures.Add($"Row {rowId}: DOE Remarks are required to reject.");
                continue;
            }

            var result = await _eclClient.RejectAsync(session.Token, rowId, rowRemarks, ct);
            if (!result.IsSuccess)
            {
                failures.Add($"Row {rowId}: {result.Error?.Message ?? "Could not reject."}");
            }
            else
            {
                rejectedCount++;
            }
        }

        var model = await BuildGridAsync(session, "ECL - Data To Approve", demandId, financialYear, reapprovalOnly: false, pendingOnly: true, ct, defaultToFirstDemandWhenUnset: true);
        model.StatusIsError = failures.Count > 0;
        model.StatusMessage = failures.Count > 0
            ? "Some rows could not be rejected - " + string.Join("; ", failures)
            : $"{rejectedCount} row(s) rejected.";
        model.IsSaveResult = true;

        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data To Approve";
        return View("DataToApprove", model);
    }

    // App: ECL | Module: ECL Approve (FunctionId 557, DOE-only)
    [HttpGet]
    public async Task<IActionResult> DataForReapproval(int? demandId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Data For Reapproval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data For Reapproval";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(DataForReapprovalFunctionId))
        {
            return Forbid();
        }

        var model = await BuildGridAsync(session, "ECL - Approved Data (Re-approval)", demandId, financialYear, reapprovalOnly: false, pendingOnly: false, ct, defaultToFirstDemandWhenUnset: true);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Reapprove(int rowId, int? demandId, string? financialYear, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(DataForReapprovalFunctionId))
        {
            return Forbid();
        }

        var result = await _eclClient.RequestReapprovalAsync(session.Token, rowId, ct);

        var model = await BuildGridAsync(session, "ECL - Approved Data (Re-approval)", demandId, financialYear, reapprovalOnly: false, pendingOnly: false, ct, defaultToFirstDemandWhenUnset: true);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess ? "Re-approval requested." : result.Error?.Message ?? "Could not request re-approval for this row.";
        model.IsSaveResult = true;

        ViewData["Title"] = "Data For Reapproval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Data For Reapproval";
        return View("DataForReapproval", model);
    }

    private async Task<EclApprovalGridViewModel> BuildGridAsync(UbisSessionData session, string title, int? demandId, string? financialYear, bool reapprovalOnly, bool pendingOnly, CancellationToken ct, bool defaultToFirstDemandWhenUnset = false)
    {
        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        var demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();

        // DataToApprove no longer offers "All" in its Demand dropdown (client request 2026-08-27) -
        // a genuinely unfiltered query returns every outlay row across every demand the caller can
        // see (860KB+ of JSON for a broadly-permissioned role, confirmed directly against the ECL
        // WebApi) and was the root cause of an earlier "Could not load rows." timeout report. When
        // no demandId is on the query string (first-ever page load, no filter submitted yet), fall
        // back to the caller's first accessible Demand instead of leaving it unfiltered.
        var effectiveDemandId = demandId ?? (defaultToFirstDemandWhenUnset ? demands.FirstOrDefault()?.DemandId : null);

        var model = new EclApprovalGridViewModel
        {
            Title = title,
            SelectedDemandId = effectiveDemandId,
            FinancialYear = fy,
            Demands = demands
        };

        var yearsResult = await _eclClient.GetFinancialYearsAsync(session.Token, ct);
        model.FinancialYearOptions = yearsResult.Data?.FinancialYears ?? new List<string> { fy };
        model.OutlayYearColumns = model.FinancialYearOptions;

        var rowsResult = await _eclClient.GetOutlaysAsync(session.Token, effectiveDemandId, null, null, fy, ct);
        var rows = rowsResult.Data ?? new List<EclSchemeOutlayDto>();

        // EclOutlayController's list endpoint doesn't filter by SendToDoe/ApprovedByDoe itself — the
        // filtering below is done here so DataToApprove only ever shows rows sent for DOE action
        // (SendToDoe='Y') that haven't been rejected, and DataForReapproval shows both currently-
        // approved rows (candidates to request re-approval on) AND rows where re-approval was
        // already requested (ReapprovalByDoe='Y') — the latter clause matters because
        // EclSchemeOutlay.RequestReapproval() atomically flips ApprovedByDoe back to "N" in the same
        // operation that sets ReapprovalByDoe="Y", so without this OR clause a row would vanish from
        // this grid the instant "Reapprove" is clicked and the view's "Re-approval Requested"
        // badge/disabled-button state (row.IsReapprovalCase) could never actually be seen.
        //
        // DataToApprove keeps already-approved rows visible (client request 2026-08-21) rather than
        // dropping them the instant they're approved — the view renders them disabled with a light
        // green background so the DOE can see what they just actioned in this session/filter without
        // a rejected row (ApprovedByDoe='R') ever reappearing here; rejected rows move on to a
        // different workflow entirely and have no reason to stay in this list.
        var filteredRows = pendingOnly
            ? rows.Where(r => string.Equals(r.SendToDoe, "Y", StringComparison.OrdinalIgnoreCase)
                               && !string.Equals(r.ApprovedByDoe, "R", StringComparison.OrdinalIgnoreCase))
                .ToList()
            : rows.Where(r => string.Equals(r.ApprovedByDoe, "Y", StringComparison.OrdinalIgnoreCase)
                               || string.Equals(r.ReapprovalByDoe, "Y", StringComparison.OrdinalIgnoreCase))
                .ToList();

        // Client request 2026-08-27: rows still awaiting action should sort above ones that already
        // have nothing left to do, not be interleaved in whatever order the API happened to return
        // them. On DataToApprove that's "not yet approved" above "already approved" (kept on-screen
        // for reference, not for the DOE to act on next). On DataForReapproval (pendingOnly: false)
        // it's the equivalent: rows still eligible to request re-approval on above ones where
        // re-approval was already requested (Reapprove button disabled - see row.IsReapprovalCase
        // in the view).
        model.Rows = pendingOnly
            ? filteredRows.OrderBy(r => string.Equals(r.ApprovedByDoe, "Y", StringComparison.OrdinalIgnoreCase) ? 1 : 0).ToList()
            : filteredRows.OrderBy(r => string.Equals(r.ReapprovalByDoe, "Y", StringComparison.OrdinalIgnoreCase) ? 1 : 0).ToList();

        if (!rowsResult.IsSuccess)
        {
            model.StatusIsError = true;
            model.StatusMessage = rowsResult.Error?.Message ?? "Could not load rows.";
        }

        return model;
    }

    // Client requirement 2026-08-27 ("also make same changes for ECL and SBE modules" - see
    // PreBudgetMeetingController's matching IsAjaxRequest()/ExpiredSessionRedirectAsync): AJAX
    // requests now get a clean 401 instead of a redirect an XHR caller could mistake for real data.
    private bool IsAjaxRequest() =>
        string.Equals(Request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.OrdinalIgnoreCase);

    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (IsAjaxRequest())
        {
            return Unauthorized();
        }
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // App: ECL | Module: ECL Approve
    public IActionResult PensionersDataforApproval()
    {
        ViewData["Title"] = "Pensioners Data for Approval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Pensioners Data for Approval";
        return View();
    }

    // App: ECL | Module: ECL Approve
    public IActionResult EmployeeDataforApproval()
    {
        ViewData["Title"] = "Employee Data for Approval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Employee Data for Approval";
        return View();
    }

    // App: ECL | Module: ECL Approve
    public IActionResult AutonomousGranteeDataforApproval()
    {
        ViewData["Title"] = "Autonomous/Grantee Data for Approval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Autonomous/Grantee Data for Approval";
        return View();
    }

    // App: ECL | Module: ECL Approve
    public IActionResult PayandAllowancesDataforApproval()
    {
        ViewData["Title"] = "Pay and Allowances Data for Approval";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Pay and Allowances Data for Approval";
        return View();
    }

    // App: ECL | Module: ECL Approve
    public IActionResult ProvisionForReapprovalAutonomous()
    {
        ViewData["Title"] = "Provision For Reapproval Autonomous";
        ViewData["Breadcrumb"] = "ECL / ECL Approve / Provision For Reapproval Autonomous";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
