// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
//
// AddSchemeOutlay (FunctionId 555) and AddActuals (FunctionId 556) below were filled in for the
// ECL scheme-outlay/DOE-approval front-end (Part 2, 2026-08-18) against the already-built ECL
// microservice (Domain/ECL). Every other action in this file (AddPensionersData onward) is an
// unrelated HR/Autonomous-Grantee-Body feature scaffolded into this same controller purely because
// the live menu groups them together — left untouched.
#nullable enable
namespace UBIS.Web.Areas.ECL.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UBIS.Web.Areas.ECL.Models;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("ECL")]
[Authorize]
public class ECLDataEntryController : Controller
{
    private const int AddSchemeOutlayFunctionId = 555;
    private const int AddActualsFunctionId = 556;

    private readonly IEclClient _eclClient;
    private readonly IAimClient _aimClient;

    public ECLDataEntryController(IEclClient eclClient, IAimClient aimClient)
    {
        _eclClient = eclClient;
        _aimClient = aimClient;
    }

    // App: ECL | Module: ECL Data Entry (FunctionId 555)
    [HttpGet]
    public async Task<IActionResult> AddSchemeOutlay(int? demandId, int? categoryId, int? rowId, CancellationToken ct)
    {
        ViewData["Title"] = "Add Scheme Outlay";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Scheme Outlay";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemeOutlayFunctionId))
        {
            return Forbid();
        }

        var model = await BuildEntryViewModelAsync(session, demandId, categoryId, ct);

        // Saved grid's Edit column (added 2026-08-18) — reached via ?rowId=X, pre-populates the
        // entry form above from the real row instead of rendering blank. The row must belong to
        // whatever Category was resolved (categoryId, defaulted below if omitted) so the Scheme
        // dropdown already contains it.
        if (rowId.HasValue)
        {
            var outlayResult = await _eclClient.GetOutlayAsync(session.Token, rowId.Value, ct);
            if (outlayResult.IsSuccess && outlayResult.Data != null)
            {
                model.SelectedOutlay = outlayResult.Data;
                model.SelectedCategoryId = outlayResult.Data.CategoryId;
                model.SelectedSchemeId = outlayResult.Data.SchemeId;

                if (outlayResult.Data.DemandId.HasValue && outlayResult.Data.CategoryId.HasValue)
                {
                    var schemesResult = await _eclClient.GetSchemesAsync(session.Token, outlayResult.Data.DemandId.Value, outlayResult.Data.CategoryId.Value, ct);
                    model.Schemes = schemesResult.Data ?? new List<EclSchemeDto>();
                }
            }
        }

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddSchemeOutlay(EclOutlayFormModel form, CancellationToken ct)
    {
        ViewData["Title"] = "Add Scheme Outlay";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Scheme Outlay";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemeOutlayFunctionId))
        {
            return Forbid();
        }

        var request = ToSaveRequest(form, session.FinancialYear);
        var result = form.RowId is > 0
            ? await _eclClient.UpdateOutlayAsync(session.Token, form.RowId.Value, request, ct)
            : await _eclClient.CreateOutlayAsync(session.Token, request, ct);

        var model = await BuildEntryViewModelAsync(session, form.DemandId, form.CategoryId, ct);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? "Scheme outlay saved successfully."
            : result.Error?.Message ?? "Could not save the scheme outlay.";

        return View(model);
    }

    /// <summary>"Send For Approval" button on the saved-outlay grid — single-row action, since
    /// EclOutlayController only exposes a per-row POST {rowId}/submit-for-approval (no bulk
    /// endpoint); the grid posts one row at a time via a per-row form (appendix-actions.js's own
    /// row-scoped pattern), so this matches what the API actually offers rather than inventing a
    /// bulk call the service can't service.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SendForApproval(int rowId, int demandId, int? categoryId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemeOutlayFunctionId))
        {
            return Forbid();
        }

        var result = await _eclClient.SubmitForApprovalAsync(session.Token, rowId, ct);

        var model = await BuildEntryViewModelAsync(session, demandId, categoryId, ct);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? "Row sent for DOE approval."
            : result.Error?.Message ?? "Could not send this row for approval.";

        ViewData["Title"] = "Add Scheme Outlay";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Scheme Outlay";
        return View("AddSchemeOutlay", model);
    }

    /// <summary>Soft-deletes a saved outlay row (grid's Delete column, added 2026-08-18). Same
    /// FunctionId gate as the rest of this screen — deletion isn't a separate permission in this
    /// app's model, matching how Edit/Send-For-Approval on this same grid work.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteOutlay(int rowId, int demandId, int? categoryId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemeOutlayFunctionId))
        {
            return Forbid();
        }

        var result = await _eclClient.DeleteOutlayAsync(session.Token, rowId, ct);

        var model = await BuildEntryViewModelAsync(session, demandId, categoryId, ct);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? "Row deleted."
            : result.Error?.Message ?? "Could not delete this row.";

        ViewData["Title"] = "Add Scheme Outlay";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Scheme Outlay";
        return View("AddSchemeOutlay", model);
    }

    /// <summary>Streams the attached PDF back for the grid's File-icon popup (added 2026-08-18) —
    /// proxies EclOutlayController.GetDocument, same pattern as UploadDocument's proxy the other
    /// direction. GetDocumentAsync buffers into a byte[] (see its own doc comment), which drops the
    /// upstream response headers, so Content-Disposition: inline is set explicitly here rather than
    /// relying on the ECL API's header surviving the hop — the browser needs it to render the PDF
    /// inline in the iframe instead of downloading it, matching the "open in popup" requirement.</summary>
    [HttpGet]
    public async Task<IActionResult> ViewDocument(int rowId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemeOutlayFunctionId))
        {
            return Forbid();
        }

        var result = await _eclClient.GetDocumentAsync(session.Token, rowId, ct);
        if (!result.IsSuccess || result.Data == null)
        {
            return NotFound();
        }

        Response.Headers.ContentDisposition = "inline";
        return File(result.Data, "application/pdf");
    }

    /// <summary>Supporting-PDF upload, forwarded as-is to EclOutlayController's
    /// POST api/ecl/outlay/documents (IFormFile file, demandId, schemeId) — the API is the
    /// authoritative validator (magic-byte check, 5 MB limit); ecl.js's pre-check is UX only.
    /// Returns the StoredFileName as JSON so the entry form can carry it as a hidden field and
    /// submit it back on Save.</summary>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [RequestSizeLimit(6 * 1024 * 1024)]
    public async Task<IActionResult> UploadDocument(IFormFile file, int demandId, int schemeId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        if (file == null || file.Length == 0)
        {
            return BadRequest(new { message = "No file was supplied." });
        }

        await using var stream = file.OpenReadStream();
        var result = await _eclClient.UploadDocumentAsync(session.Token, stream, file.FileName, file.ContentType, demandId, schemeId, ct);

        return result.IsSuccess
            ? Json(new { success = true, fileName = result.Data!.StoredFileName })
            : Json(new { success = false, message = result.Error?.Message ?? "Upload failed." });
    }

    /// <summary>AJAX helper backing ecl.js's Category->Scheme cascade on AddSchemeOutlay. Client-
    /// corrected 2026-08-20: schemes are scoped by BOTH Demand and Category — Demand is a fixed
    /// hidden field on that page (not user-changeable), so demandId here is always that fixed value,
    /// while categoryId is whatever the user just picked.</summary>
    [HttpGet]
    public async Task<IActionResult> GetSchemes(int demandId, int categoryId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        var result = await _eclClient.GetSchemesAsync(session.Token, demandId, categoryId, ct);
        return Json(result.Data ?? new List<EclSchemeDto>());
    }

    // App: ECL | Module: ECL Data Entry (FunctionId 556)
    // Full-page form (matches the already-routed /ECL/ECLDataEntry/AddActuals URL and the mockup,
    // ECLActualsEntry.html, which is itself a full page) rather than a modal launched from
    // AddSchemeOutlay's grid — this app has no existing real modal/<dialog> pattern to reuse (only
    // Login.cshtml/VerifyOtp.cshtml use <dialog>, for an unrelated captcha/OTP flow), so a second
    // bespoke modal implementation would be new surface area for one screen. The saved-outlay grid
    // links here with ?rowId= to preselect the row instead.
    [HttpGet]
    public async Task<IActionResult> AddActuals(int? demandId, int? categoryId, int? rowId, CancellationToken ct)
    {
        ViewData["Title"] = "Add Actuals";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Actuals";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddActualsFunctionId))
        {
            return Forbid();
        }

        var model = await BuildActualsViewModelAsync(session, demandId, categoryId, rowId, ct);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddActuals(int rowId, int demandId, int? categoryId, decimal?[] actuals, CancellationToken ct)
    {
        ViewData["Title"] = "Add Actuals";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Actuals";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddActualsFunctionId))
        {
            return Forbid();
        }

        var padded = new decimal?[10];
        for (var i = 0; i < 10 && actuals != null && i < actuals.Length; i++)
        {
            padded[i] = actuals[i];
        }

        var result = await _eclClient.RecordActualsAsync(session.Token, rowId, padded, ct);

        var model = await BuildActualsViewModelAsync(session, demandId, categoryId, rowId, ct);
        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? "Actuals recorded successfully."
            : result.Error?.Message ?? "Could not record actuals.";

        return View(model);
    }

    /// <summary>
    /// JSON companion to the full-page AddActuals GET/POST above — used by the Add Actuals modal
    /// on AddSchemeOutlay's saved grid (client request 2026-08-18: "avoid unnecessary page
    /// navigation", styled/behaving like the login screen's #changePasswordDialog/
    /// #forgotPasswordDialog). The full-page actions stay as-is for anyone reaching this
    /// FunctionId's route directly (e.g. via the menu) without JS.
    /// </summary>
    [HttpGet]
    public async Task<IActionResult> GetActualsForRow(int rowId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        if (!session.HasPermission(AddActualsFunctionId))
        {
            return Forbid();
        }

        var result = await _eclClient.GetOutlayAsync(session.Token, rowId, ct);
        if (!result.IsSuccess || result.Data == null)
        {
            return NotFound();
        }

        var outlay = result.Data;
        var schemesResult = await _eclClient.GetSchemesAsync(session.Token, outlay.DemandId ?? 0, outlay.CategoryId ?? 0, ct);
        var schemeName = schemesResult.Data?.FirstOrDefault(s => s.SchemeId == outlay.SchemeId)?.SchemeName ?? $"Scheme #{outlay.SchemeId}";

        return Json(new
        {
            rowId = outlay.RowId,
            financialYear = outlay.FinancialYear,
            schemeName,
            doeApprovalStatusDisplay = outlay.DoeApprovalStatusDisplay,
            outlay = outlay.Outlay,
            actuals = outlay.Actuals
        });
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveActualsAjax(int rowId, decimal?[] actuals, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        if (!session.HasPermission(AddActualsFunctionId))
        {
            return Forbid();
        }

        var padded = new decimal?[10];
        for (var i = 0; i < 10 && actuals != null && i < actuals.Length; i++)
        {
            padded[i] = actuals[i];
        }

        var result = await _eclClient.RecordActualsAsync(session.Token, rowId, padded, ct);
        if (!result.IsSuccess)
        {
            return BadRequest(new { message = result.Error?.Message ?? "Could not record actuals." });
        }

        return Json(new { success = true });
    }

    private async Task<EclEntryViewModel> BuildEntryViewModelAsync(UbisSessionData session, int? demandId, int? categoryId, CancellationToken ct)
    {
        var model = new EclEntryViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedCategoryId = categoryId
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        var demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();
        var resolvedDemandId = demandId ?? demands.FirstOrDefault()?.DemandId ?? 0;
        var resolvedDemandNo = demandId ?? demands.FirstOrDefault()?.DemandNo ?? 0;

        model.DemandId = resolvedDemandId;
        model.DemandName = demands.FirstOrDefault(d => d.DemandId == resolvedDemandId)?.DemandName ?? string.Empty;
        model.DemandNo = resolvedDemandNo;

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, session.FinancialYear, ct);
        model.Categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        // Client-corrected 2026-08-20: schemes are scoped by BOTH Demand and Category. Demand is
        // always known by this point (resolvedDemandId above) but Category is still a real user
        // selection, so this still waits on it.
        if (categoryId.HasValue)
        {
            var schemesResult = await _eclClient.GetSchemesAsync(session.Token, resolvedDemandId, categoryId.Value, ct);
            model.Schemes = schemesResult.Data ?? new List<EclSchemeDto>();
        }

        var approvalAuthoritiesResult = await _eclClient.GetApprovalAuthoritiesAsync(session.Token, ct);
        model.ApprovalAuthorities = approvalAuthoritiesResult.Data ?? new List<EclApprovalAuthorityDto>();

        var appraiseAuthoritiesResult = await _eclClient.GetAppraiseAuthoritiesAsync(session.Token, ct);
        model.AppraiseAuthorities = appraiseAuthoritiesResult.Data ?? new List<EclAppraiseAuthorityDto>();

        var yearsResult = await _eclClient.GetFinancialYearsAsync(session.Token, ct);
        var years = yearsResult.Data?.FinancialYears ?? new List<string>();
        model.SchemeEndYearOptions = years;
        model.OutlayYearColumns = years;

        var savedResult = await _eclClient.GetOutlaysAsync(session.Token, resolvedDemandId, null, null, session.FinancialYear, ct);
        model.SavedRows = savedResult.Data ?? new List<EclSchemeOutlayDto>();

        return model;
    }

    private async Task<EclActualsViewModel> BuildActualsViewModelAsync(UbisSessionData session, int? demandId, int? categoryId, int? rowId, CancellationToken ct)
    {
        var model = new EclActualsViewModel
        {
            FinancialYear = session.FinancialYear,
            SelectedCategoryId = categoryId,
            SelectedRowId = rowId
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        var demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();
        var resolvedDemandId = demandId ?? demands.FirstOrDefault()?.DemandId ?? 0;
        model.DemandId = resolvedDemandId;
        model.DemandName = demands.FirstOrDefault(d => d.DemandId == resolvedDemandId)?.DemandName ?? string.Empty;

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, session.FinancialYear, ct);
        model.Categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        // Client-corrected 2026-08-20: schemes are scoped by both Demand and Category — see the
        // same fix/comment in BuildEntryViewModelAsync above.
        if (categoryId.HasValue)
        {
            var schemesResult = await _eclClient.GetSchemesAsync(session.Token, resolvedDemandId, categoryId.Value, ct);
            model.Schemes = schemesResult.Data ?? new List<EclSchemeDto>();
        }

        // Actuals can only be recorded against rows already submitted (SendToDoe='Y') — mirrors the
        // mockup's Category/Scheme pickers being read-only reference fields, not free entry.
        var submittedResult = await _eclClient.GetOutlaysAsync(session.Token, resolvedDemandId, null, null, session.FinancialYear, ct);
        model.SubmittedRows = (submittedResult.Data ?? new List<EclSchemeOutlayDto>())
            .Where(r => string.Equals(r.SendToDoe, "Y", StringComparison.OrdinalIgnoreCase))
            .ToList();

        if (rowId.HasValue)
        {
            model.SelectedOutlay = model.SubmittedRows.FirstOrDefault(r => r.RowId == rowId.Value)
                ?? (await _eclClient.GetOutlayAsync(session.Token, rowId.Value, ct)).Data;
        }

        return model;
    }

    private static SaveSchemeOutlayRequestDto ToSaveRequest(EclOutlayFormModel form, string financialYear)
    {
        var isYes = string.Equals(form.Is16Fc, "Y", StringComparison.OrdinalIgnoreCase);

        var appraisalAuth = string.Equals(form.AppraisalAuth, "Others", StringComparison.OrdinalIgnoreCase)
            ? form.AppraisalAuthOther
            : form.AppraisalAuth;
        var approveAuth = string.Equals(form.ApproveAuth, "Others", StringComparison.OrdinalIgnoreCase)
            ? form.ApproveAuthOther
            : form.ApproveAuth;

        return new SaveSchemeOutlayRequestDto
        {
            FinancialYear = financialYear,
            CategoryId = form.CategoryId,
            DemandId = form.DemandId,
            SchemeId = form.SchemeId,
            Is16Fc = form.Is16Fc,
            TotalOutlay = form.TotalOutlay,
            CentralShare = isYes ? form.CentralShare : null,
            SchemeEndYear = form.SchemeEndYear,
            AppraisalAuth = appraisalAuth,
            WhetherAppraised = form.WhetherAppraised,
            AppraisalStatusRemarks = form.AppraisalStatusRemarks,
            ApproveAuth = approveAuth,
            IsApproved = form.IsApproved,
            NotApprovedRem = form.NotApprovedRem,
            Outlay = form.Outlay ?? new decimal?[10],
            UserRemarks = form.UserRemarks,
            FileName = form.FileName
        };
    }

    // Client requirement 2026-08-27 ("also make same changes for ECL and SBE modules" - see
    // PreBudgetMeetingController's matching IsAjaxRequest()/ExpiredSessionRedirectAsync): a plain
    // RedirectToAction here was fine for a normal page navigation, but any of ecl.js's own fetch()
    // cascades (Scheme/UmbrellaScheme dropdowns, row lookups, exports) that hit an expired session
    // got a 200 OK with the full Login page's HTML instead of the JSON/blob they expected - caught
    // defensively by those callers' own res.ok/content-type checks (so this wasn't visibly breaking
    // the UI the way PreBudget's container-swap bug did), but still the wrong status code for what
    // actually happened. AJAX requests now get a clean 401 instead.
    private bool IsAjaxRequest() =>
        string.Equals(Request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.OrdinalIgnoreCase);

    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (IsAjaxRequest())
        {
            return Unauthorized();
        }
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AddPensionersData()
    {
        ViewData["Title"] = "Add Pensioners Data";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Pensioners Data";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AddEmployeesData()
    {
        ViewData["Title"] = "Add Employees Data";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Employees Data";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AddAutonomousGranteeData()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Data";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Autonomous/Grantee Data";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult PayandAllowancesExpenditure()
    {
        ViewData["Title"] = "Pay and Allowances Expenditure";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Pay and Allowances Expenditure";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AddAutonomousGranteeName()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Name";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Add Autonomous/Grantee Name";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AutonomousGranteeReports()
    {
        ViewData["Title"] = "Autonomous/Grantee Reports";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Autonomous/Grantee Reports";
        return View();
    }

    // App: ECL | Module: ECL Data Entry
    public IActionResult AutonomousGranteeBodiesStatus()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies Status";
        ViewData["Breadcrumb"] = "ECL / ECL Data Entry / Autonomous/Grantee Bodies Status";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
