// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
//
// AddSchemes (FunctionId 558) below was filled in for the ECL scheme-master front-end (Part 2,
// 2026-08-18), then wired up to a real create-scheme endpoint (POST api/ecl/outlay/schemes, added
// to Domain/ECL the same day) that persists to dbo.M_Scheme, next SchemeSrNo assigned server-side.
#nullable enable
namespace UBIS.Web.Areas.ECL.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UBIS.Web.Areas.ECL.Models;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("ECL")]
[Authorize]
public class ECLMasterController : Controller
{
    private const int AddSchemesFunctionId = 558;

    private readonly IEclClient _eclClient;
    private readonly IAimClient _aimClient;

    public ECLMasterController(IEclClient eclClient, IAimClient aimClient)
    {
        _eclClient = eclClient;
        _aimClient = aimClient;
    }

    // App: ECL | Module: ECL Master (FunctionId 558)
    [HttpGet]
    public async Task<IActionResult> AddSchemes(int? demandId, int? categoryId, CancellationToken ct)
    {
        ViewData["Title"] = "Add Schemes";
        ViewData["Breadcrumb"] = "ECL / ECL Master / Add Schemes";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemesFunctionId))
        {
            return Forbid();
        }

        var model = await BuildViewModelAsync(session, demandId, categoryId, ct);
        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> AddSchemes(int demandId, int categoryId, string? isUmbrella, int? umbrellaSchemeId, string? schemeNameEnglish, string? schemeNameHindi, CancellationToken ct)
    {
        ViewData["Title"] = "Add Schemes";
        ViewData["Breadcrumb"] = "ECL / ECL Master / Add Schemes";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return await ExpiredSessionRedirectAsync();
        }

        if (!session.HasPermission(AddSchemesFunctionId))
        {
            return Forbid();
        }

        var isUmbrellaYes = string.Equals(isUmbrella, "Y", StringComparison.OrdinalIgnoreCase);

        var model = await BuildViewModelAsync(session, demandId, categoryId, ct);

        if (string.IsNullOrWhiteSpace(schemeNameEnglish))
        {
            model.StatusIsError = true;
            model.StatusMessage = "Scheme Name (English) is required.";
            return View(model);
        }

        var result = await _eclClient.CreateSchemeAsync(session.Token, new CreateSchemeRequestDto
        {
            DemandId = demandId,
            CategoryId = categoryId,
            IsUmbrella = isUmbrellaYes,
            UmbrellaSchemeId = isUmbrellaYes ? null : umbrellaSchemeId,
            SchemeNameEnglish = schemeNameEnglish.Trim(),
            SchemeNameHindi = string.IsNullOrWhiteSpace(schemeNameHindi) ? null : schemeNameHindi.Trim()
        }, ct);

        if (result.IsSuccess)
        {
            // Rebuild so UmbrellaSchemeOptions picks up the just-created scheme.
            model = await BuildViewModelAsync(session, demandId, categoryId, ct);
        }

        model.StatusIsError = !result.IsSuccess;
        model.StatusMessage = result.IsSuccess
            ? $"Scheme '{result.Data?.SchemeName}' created successfully (SchemeId {result.Data?.SchemeId})."
            : result.Error?.Message ?? "Could not create the scheme.";

        return View(model);
    }

    /// <summary>AJAX helper backing ecl.js's Category/Demand->Umbrella-Scheme cascade — the Demand
    /// select had no wiring at all before (added 2026-08-19), so changing it never refreshed the
    /// Umbrella Scheme dropdown; it only ever reflected whatever demandId the page was originally
    /// loaded with. Requires BOTH categoryId and demandId (client-corrected 2026-08-19: the real
    /// source is dbo.M_UmbScheme, filtered by CategoryId AND DemandId, not just DemandId against
    /// dbo.M_Scheme.IsUmbrella as originally built). Mirrors ECLDataEntryController.GetSchemes's
    /// exact pattern.</summary>
    [HttpGet]
    public async Task<IActionResult> GetUmbrellaSchemes(int categoryId, int demandId, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null)
        {
            return Unauthorized();
        }

        var result = await _eclClient.GetUmbrellaSchemesAsync(session.Token, categoryId, demandId, ct);
        return Json(result.Data ?? new List<EclUmbSchemeDto>());
    }

    private async Task<EclSchemeMasterViewModel> BuildViewModelAsync(UbisSessionData session, int? demandId, int? categoryId, CancellationToken ct)
    {
        var model = new EclSchemeMasterViewModel
        {
            SelectedDemandId = demandId,
            SelectedCategoryId = categoryId,
            FinancialYear = session.FinancialYear
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        model.Demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, session.FinancialYear, ct);
        model.Categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        // Umbrella-scheme picker needs BOTH CategoryId and DemandId (client-corrected 2026-08-19:
        // "select * from M_UmbScheme where CategoryId = @Categoryid and Demandid=@DemandId") - the
        // real source is dbo.M_UmbScheme, a separate master table, not dbo.M_Scheme.IsUmbrella as
        // originally (wrongly) built.
        if (demandId.HasValue && categoryId.HasValue)
        {
            var umbrellaResult = await _eclClient.GetUmbrellaSchemesAsync(session.Token, categoryId.Value, demandId.Value, ct);
            model.UmbrellaSchemeOptions = umbrellaResult.Data ?? new List<EclUmbSchemeDto>();
        }

        return model;
    }

    // Client requirement 2026-08-27 ("also make same changes for ECL and SBE modules" - see
    // PreBudgetMeetingController's matching IsAjaxRequest()/ExpiredSessionRedirectAsync): AJAX
    // requests now get a clean 401 instead of a redirect an XHR caller could mistake for real data.
    private bool IsAjaxRequest() =>
        string.Equals(Request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.OrdinalIgnoreCase);

    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (IsAjaxRequest())
        {
            return Unauthorized();
        }
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // App: ECL | Module: ECL Master
    public IActionResult AddAutonomousGranteeName()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Name";
        ViewData["Breadcrumb"] = "ECL / ECL Master / Add Autonomous/Grantee Name";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
