// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
//
// DataAnalysis (561), DemandWiseECLStatus (563), DemandWiseECLStatusTopLine (575) and
// PendingDemand (564) below were filled in for the ECL reporting front-end (Part 2, 2026-08-18).
// GAP (noted, not worked around): Part 1 built no purpose-built reporting endpoints — every screen
// here reads off EclOutlayController's general GET api/ecl/outlay list (with demandId/categoryId/
// financialYear filters) and does the report-shaping (grouping/status summarizing) client-side in
// the controller. That's fine at current data volumes but a dedicated aggregate endpoint
// (e.g. GET api/ecl/reports/demand-wise-status) would scale better and avoid shipping every row's
// full 10-year outlay/actuals arrays to the browser just to summarize them — worth it if these
// reports get slow in practice. Every other action in this file (AutonomousGranteeBodies*) is
// unrelated and left untouched.
#nullable enable
namespace UBIS.Web.Areas.ECL.Controllers;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UBIS.Web.Areas.ECL.Models;
using UBIS.Web.Services.Clients;
using UBIS.Web.Services.Session;

[Area("ECL")]
[Authorize]
public class ECLReportController : Controller
{
    private const int DataAnalysisFunctionId = 561;
    private const int DemandWiseECLStatusFunctionId = 563;
    private const int DemandWiseECLStatusTopLineFunctionId = 575;
    private const int PendingDemandFunctionId = 564;

    private readonly IEclClient _eclClient;
    private readonly IAimClient _aimClient;
    private readonly IReportingClient _reportingClient;

    public ECLReportController(IEclClient eclClient, IAimClient aimClient, IReportingClient reportingClient)
    {
        _eclClient = eclClient;
        _aimClient = aimClient;
        _reportingClient = reportingClient;
    }

    // App: ECL | Module: ECL Report (FunctionId 561)
    // Client request 2026-08-20: page was slow to load because the GET itself fetched every
    // outlay row (GetOutlaysAsync, unfiltered by default = every demand) before rendering anything.
    // Now renders the shell (filters only, no rows) immediately - the grid loads separately via
    // DataAnalysisData below, called by JS with a loading spinner shown meanwhile.
    [HttpGet]
    public async Task<IActionResult> DataAnalysis(int? demandId, int? categoryId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Data Analysis";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Data Analysis";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(DataAnalysisFunctionId)) return Forbid();

        var model = await BuildFilterShellAsync(session, "ECL - Data Analysis", demandId, categoryId, financialYear, ct);
        model.ShowCategoryFilter = true;
        return View(model);
    }

    /// <summary>AJAX companion to DataAnalysis — does the actual (potentially slow) row fetch and
    /// groups it by Demand to match the client-supplied report format screenshot (2026-08-20): each
    /// Demand is a group header row, its Scheme rows underneath (Category, 10 year-outlay columns),
    /// then Total Outlay/Total Actual subtotal rows summed across that Demand's schemes. Skips the
    /// "C.Share / Remaining Year wise C.Share" column per that same instruction - CentralShare isn't
    /// included in the response at all. Returns the aggregation result as JSON; ecl.js renders it
    /// into the two side-by-side tables (financial data left, remarks/approval right).</summary>
    [HttpGet]
    public async Task<IActionResult> DataAnalysisData(int? demandId, int? categoryId, string? financialYear, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return Unauthorized();
        if (!session.HasPermission(DataAnalysisFunctionId)) return Forbid();

        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;
        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, fy, ct);
        var categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        var rowsResult = await _eclClient.GetOutlaysAsync(session.Token, demandId, categoryId, null, fy, ct);
        if (!rowsResult.IsSuccess)
        {
            return Json(new { success = false, message = rowsResult.Error?.Message ?? "Could not load report data." });
        }

        var rows = rowsResult.Data ?? new List<EclSchemeOutlayDto>();
        var groups = rows
            .GroupBy(r => r.DemandId)
            .OrderBy(g => rows.First(r => r.DemandId == g.Key).DemandNo)
            .Select(g =>
            {
                var first = g.First();
                var totalOutlay = new decimal[10];
                var totalActual = new decimal[10];
                var schemeRows = g.OrderBy(r => r.SchemeSrNo).Select(r =>
                {
                    for (var i = 0; i < 10; i++)
                    {
                        totalOutlay[i] += r.Outlay != null && i < r.Outlay.Length ? r.Outlay[i] ?? 0 : 0;
                        totalActual[i] += r.Actuals != null && i < r.Actuals.Length ? r.Actuals[i] ?? 0 : 0;
                    }

                    return new
                    {
                        rowId = r.RowId,
                        schemeLabel = !string.IsNullOrEmpty(r.SchemeName) ? $"{r.SchemeSrNo ?? 0} - {r.SchemeName}" : $"Scheme #{r.SchemeId}",
                        categoryLabel = categories.FirstOrDefault(c => c.CategoryId == r.CategoryId)?.CategoryName ?? "",
                        outlay = r.Outlay ?? new decimal?[10],
                        userRemarks = r.UserRemarks,
                        approverRemarks = r.DoeRemarks,
                        approvedByDoe = r.ApprovedByDoe
                    };
                }).ToList();

                return new
                {
                    demandLabel = !string.IsNullOrEmpty(first.DemandName) ? $"{first.DemandNo} - {first.DemandName}" : $"Demand #{first.DemandId}",
                    rows = schemeRows,
                    totalOutlay,
                    totalActual
                };
            })
            .ToList();

        return Json(new { success = true, groups });
    }

    /// <summary>Export buttons on DataAnalysis.cshtml — same filters, same grouping as
    /// DataAnalysisData above (re-fetched rather than shared, since this needs string-formatted
    /// cells and the JSON endpoint needs typed values for client-side rendering), handed to the
    /// generic Reporting microservice (Core/Reporting) rather than generated in-process — see that
    /// service's own doc comments for why (reused across 50+ future pages, not ECL-specific).</summary>
    [HttpGet]
    public async Task<IActionResult> ExportPdf(int? demandId, int? categoryId, string? financialYear, CancellationToken ct) =>
        await ExportAsync(demandId, categoryId, financialYear, isPdf: true, ct);

    [HttpGet]
    public async Task<IActionResult> ExportExcel(int? demandId, int? categoryId, string? financialYear, CancellationToken ct) =>
        await ExportAsync(demandId, categoryId, financialYear, isPdf: false, ct);

    private async Task<IActionResult> ExportAsync(int? demandId, int? categoryId, string? financialYear, bool isPdf, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(DataAnalysisFunctionId)) return Forbid();

        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;

        var yearsResult = await _eclClient.GetFinancialYearsAsync(session.Token, ct);
        var years = yearsResult.Data?.FinancialYears ?? new List<string> { fy };

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, fy, ct);
        var categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        var rowsResult = await _eclClient.GetOutlaysAsync(session.Token, demandId, categoryId, null, fy, ct);
        if (!rowsResult.IsSuccess)
        {
            TempData["ErrorMessage"] = rowsResult.Error?.Message ?? "Could not load report data.";
            return RedirectToAction("DataAnalysis", new { demandId, categoryId, financialYear });
        }

        var rows = rowsResult.Data ?? new List<EclSchemeOutlayDto>();

        var columns = new List<string> { "Demand / Scheme", "Category" };
        columns.AddRange(years);
        columns.Add("User Remarks");
        columns.Add("Approver Remarks");
        columns.Add("Approved By DOE");

        var groups = rows
            .GroupBy(r => r.DemandId)
            .OrderBy(g => rows.First(r => r.DemandId == g.Key).DemandNo)
            .Select(g =>
            {
                var first = g.First();
                var totalOutlay = new decimal[years.Count];
                var totalActual = new decimal[years.Count];

                var schemeRows = g.OrderBy(r => r.SchemeSrNo).Select(r =>
                {
                    var cells = new List<string>
                    {
                        !string.IsNullOrEmpty(r.SchemeName) ? $"{r.SchemeSrNo ?? 0} - {r.SchemeName}" : $"Scheme #{r.SchemeId}",
                        categories.FirstOrDefault(c => c.CategoryId == r.CategoryId)?.CategoryName ?? ""
                    };
                    for (var i = 0; i < years.Count; i++)
                    {
                        var outlay = r.Outlay != null && i < r.Outlay.Length ? r.Outlay[i] ?? 0 : 0;
                        var actual = r.Actuals != null && i < r.Actuals.Length ? r.Actuals[i] ?? 0 : 0;
                        totalOutlay[i] += outlay;
                        totalActual[i] += actual;
                        cells.Add(outlay.ToString("N2"));
                    }
                    cells.Add(r.UserRemarks ?? "");
                    cells.Add(r.DoeRemarks ?? "");
                    cells.Add(r.ApprovedByDoe ?? "");
                    return cells.ToArray();
                }).ToList();

                var totalOutlayCells = new List<string> { "Total Outlay", "" };
                totalOutlayCells.AddRange(totalOutlay.Select(v => v.ToString("N2")));
                totalOutlayCells.AddRange(new[] { "", "", "" });

                var totalActualCells = new List<string> { "Total Actual", "" };
                totalActualCells.AddRange(totalActual.Select(v => v.ToString("N2")));
                totalActualCells.AddRange(new[] { "", "", "" });

                return new ReportGroupDto
                {
                    Label = !string.IsNullOrEmpty(first.DemandName) ? $"{first.DemandNo} - {first.DemandName}" : $"Demand #{first.DemandId}",
                    Rows = schemeRows,
                    Totals = new List<ReportTotalRowDto>
                    {
                        new() { Cells = totalOutlayCells.ToArray() },
                        new() { Cells = totalActualCells.ToArray() }
                    }
                };
            })
            .ToList();

        var report = new TabularReportDto
        {
            Title = "Estimated Committed Liabilities",
            Subtitle = "(In Rs. Crores)",
            FileName = "ecl-data-analysis",
            Columns = columns,
            Groups = groups
        };

        var exportResult = isPdf
            ? await _reportingClient.ExportPdfAsync(session.Token, report, ct)
            : await _reportingClient.ExportExcelAsync(session.Token, report, ct);

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            TempData["ErrorMessage"] = exportResult.Error?.Message ?? "Could not generate the export.";
            return RedirectToAction("DataAnalysis", new { demandId, categoryId, financialYear });
        }

        var contentType = isPdf ? "application/pdf" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        var extension = isPdf ? "pdf" : "xlsx";
        return File(exportResult.Data, contentType, $"{report.FileName}.{extension}");
    }

    private async Task<EclReportViewModel> BuildFilterShellAsync(UbisSessionData session, string title, int? demandId, int? categoryId, string? financialYear, CancellationToken ct)
    {
        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;

        var model = new EclReportViewModel
        {
            Title = title,
            SelectedDemandId = demandId,
            SelectedCategoryId = categoryId,
            FinancialYear = fy
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        model.Demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, fy, ct);
        model.Categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        var yearsResult = await _eclClient.GetFinancialYearsAsync(session.Token, ct);
        model.FinancialYearOptions = yearsResult.Data?.FinancialYears ?? new List<string> { fy };

        if (TempData["ErrorMessage"] is string exportError)
        {
            model.StatusIsError = true;
            model.StatusMessage = exportError;
        }

        return model;
    }

    // App: ECL | Module: ECL Report (FunctionId 563)
    [HttpGet]
    public async Task<IActionResult> DemandWiseECLStatus(int? demandId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Demand Wise ECL Status";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Demand Wise ECL Status";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(DemandWiseECLStatusFunctionId)) return Forbid();

        var model = await BuildReportAsync(session, "ECL - Demand Wise ECL Status", demandId, categoryId: null, financialYear, rowFilter: null, ct);
        return View(model);
    }

    // App: ECL | Module: ECL Report (FunctionId 575) — top-line/summary variant of the same status report
    [HttpGet]
    public async Task<IActionResult> DemandWiseECLStatusTopLine(int? demandId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Demand Wise ECL Status Top Line";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Demand Wise ECL Status Top Line";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(DemandWiseECLStatusTopLineFunctionId)) return Forbid();

        var model = await BuildReportAsync(session, "ECL - Demand Wise ECL Status (Top Line)", demandId, categoryId: null, financialYear, rowFilter: null, ct);
        return View(model);
    }

    // App: ECL | Module: ECL Report (FunctionId 564) — rows still awaiting DOE decision
    [HttpGet]
    public async Task<IActionResult> PendingDemand(int? demandId, string? financialYear, CancellationToken ct)
    {
        ViewData["Title"] = "Pending Demand";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Pending Demand";

        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(PendingDemandFunctionId)) return Forbid();

        var model = await BuildReportAsync(session, "ECL - Pending Demand Report", demandId, categoryId: null, financialYear,
            rowFilter: r => string.Equals(r.SendToDoe, "Y", StringComparison.OrdinalIgnoreCase)
                             && !string.Equals(r.ApprovedByDoe, "Y", StringComparison.OrdinalIgnoreCase),
            ct);
        return View(model);
    }

    // Export buttons for the three status-family reports above — same permission gate and rowFilter
    // as each report's own screen action, just handed to the generic Reporting microservice instead
    // of rendered as HTML. Action names follow "{ScreenAction}ExportPdf"/"...ExportExcel" so
    // _EclReportGrid.cshtml can compute the right link purely from its own actionName variable,
    // without each parent view needing to say which export action applies to it.
    [HttpGet]
    public Task<IActionResult> DemandWiseECLStatusExportPdf(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(DemandWiseECLStatusFunctionId, nameof(DemandWiseECLStatus), "Demand Wise ECL Status", "ecl-demand-wise-status", demandId, financialYear, rowFilter: null, isPdf: true, ct);

    [HttpGet]
    public Task<IActionResult> DemandWiseECLStatusExportExcel(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(DemandWiseECLStatusFunctionId, nameof(DemandWiseECLStatus), "Demand Wise ECL Status", "ecl-demand-wise-status", demandId, financialYear, rowFilter: null, isPdf: false, ct);

    [HttpGet]
    public Task<IActionResult> DemandWiseECLStatusTopLineExportPdf(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(DemandWiseECLStatusTopLineFunctionId, nameof(DemandWiseECLStatusTopLine), "Demand Wise ECL Status (Top Line)", "ecl-demand-wise-status-topline", demandId, financialYear, rowFilter: null, isPdf: true, ct);

    [HttpGet]
    public Task<IActionResult> DemandWiseECLStatusTopLineExportExcel(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(DemandWiseECLStatusTopLineFunctionId, nameof(DemandWiseECLStatusTopLine), "Demand Wise ECL Status (Top Line)", "ecl-demand-wise-status-topline", demandId, financialYear, rowFilter: null, isPdf: false, ct);

    [HttpGet]
    public Task<IActionResult> PendingDemandExportPdf(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(PendingDemandFunctionId, nameof(PendingDemand), "Pending Demand Report", "ecl-pending-demand", demandId, financialYear,
            r => string.Equals(r.SendToDoe, "Y", StringComparison.OrdinalIgnoreCase) && !string.Equals(r.ApprovedByDoe, "Y", StringComparison.OrdinalIgnoreCase),
            isPdf: true, ct);

    [HttpGet]
    public Task<IActionResult> PendingDemandExportExcel(int? demandId, string? financialYear, CancellationToken ct) =>
        ExportStatusReportAsync(PendingDemandFunctionId, nameof(PendingDemand), "Pending Demand Report", "ecl-pending-demand", demandId, financialYear,
            r => string.Equals(r.SendToDoe, "Y", StringComparison.OrdinalIgnoreCase) && !string.Equals(r.ApprovedByDoe, "Y", StringComparison.OrdinalIgnoreCase),
            isPdf: false, ct);

    private async Task<IActionResult> ExportStatusReportAsync(int functionId, string screenActionName, string title, string fileName, int? demandId, string? financialYear, Func<EclSchemeOutlayDto, bool>? rowFilter, bool isPdf, CancellationToken ct)
    {
        var session = HttpContext.Session.GetUbisSession();
        if (session == null) return await ExpiredSessionRedirectAsync();
        if (!session.HasPermission(functionId)) return Forbid();

        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;

        var rowsResult = await _eclClient.GetOutlaysAsync(session.Token, demandId, null, null, fy, ct);
        if (!rowsResult.IsSuccess)
        {
            TempData["ErrorMessage"] = rowsResult.Error?.Message ?? "Could not load report data.";
            return RedirectToAction(screenActionName, new { demandId, financialYear });
        }

        var rows = rowsResult.Data ?? new List<EclSchemeOutlayDto>();
        if (rowFilter != null)
        {
            rows = rows.Where(rowFilter).ToList();
        }

        var dataRows = rows.Select((r, i) => new[]
        {
            (i + 1).ToString(),
            r.FinancialYear ?? "",
            !string.IsNullOrEmpty(r.DemandName) ? $"{r.DemandNo} - {r.DemandName}" : $"Demand #{r.DemandId}",
            !string.IsNullOrEmpty(r.SchemeName) ? $"{r.SchemeSrNo ?? 0} - {r.SchemeName}" : $"Scheme #{r.SchemeId}",
            r.TotalOutlay?.ToString("N2") ?? "",
            r.CentralShare?.ToString("N2") ?? "",
            r.DoeApprovalStatusDisplay
        }).ToList();

        var report = new TabularReportDto
        {
            Title = title,
            Subtitle = "Amount in Crores of Rupees",
            FileName = fileName,
            Columns = new List<string> { "Sr. No.", "Financial Year", "Demand", "Scheme", "Total Outlay", "Central Share", "Status" },
            Groups = new List<ReportGroupDto> { new() { Rows = dataRows } }
        };

        var exportResult = isPdf
            ? await _reportingClient.ExportPdfAsync(session.Token, report, ct)
            : await _reportingClient.ExportExcelAsync(session.Token, report, ct);

        if (!exportResult.IsSuccess || exportResult.Data == null)
        {
            TempData["ErrorMessage"] = exportResult.Error?.Message ?? "Could not generate the export.";
            return RedirectToAction(screenActionName, new { demandId, financialYear });
        }

        var contentType = isPdf ? "application/pdf" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        var extension = isPdf ? "pdf" : "xlsx";
        return File(exportResult.Data, contentType, $"{fileName}.{extension}");
    }

    private async Task<EclReportViewModel> BuildReportAsync(UbisSessionData session, string title, int? demandId, int? categoryId, string? financialYear, Func<EclSchemeOutlayDto, bool>? rowFilter, CancellationToken ct)
    {
        var fy = string.IsNullOrWhiteSpace(financialYear) ? session.FinancialYear : financialYear;

        var model = new EclReportViewModel
        {
            Title = title,
            SelectedDemandId = demandId,
            SelectedCategoryId = categoryId,
            FinancialYear = fy
        };

        var demandsResult = await _aimClient.GetMyDemandsAsync(session.Token, session.FinancialYear, ct);
        model.Demands = demandsResult.IsSuccess ? demandsResult.Data?.Demands ?? new List<DemandDto>() : new List<DemandDto>();

        var categoriesResult = await _eclClient.GetCategoriesAsync(session.Token, fy, ct);
        model.Categories = categoriesResult.Data ?? new List<EclCategoryDto>();

        var yearsResult = await _eclClient.GetFinancialYearsAsync(session.Token, ct);
        model.FinancialYearOptions = yearsResult.Data?.FinancialYears ?? new List<string> { fy };

        var rowsResult = await _eclClient.GetOutlaysAsync(session.Token, demandId, categoryId, null, fy, ct);
        var rows = rowsResult.Data ?? new List<EclSchemeOutlayDto>();
        model.Rows = rowFilter == null ? rows : rows.Where(rowFilter).ToList();

        if (!rowsResult.IsSuccess)
        {
            model.StatusIsError = true;
            model.StatusMessage = rowsResult.Error?.Message ?? "Could not load report data.";
        }
        else if (TempData["ErrorMessage"] is string exportError)
        {
            // Surfaces the export-failure message set by ExportStatusReportAsync's RedirectToAction —
            // without this, a failed PDF/Excel export would silently bounce back to this screen with
            // no visible feedback at all.
            model.StatusIsError = true;
            model.StatusMessage = exportError;
        }

        return model;
    }

    // Client requirement 2026-08-27 ("also make same changes for ECL and SBE modules" - see
    // PreBudgetMeetingController's matching IsAjaxRequest()/ExpiredSessionRedirectAsync): AJAX
    // requests now get a clean 401 instead of a redirect an XHR caller could mistake for real data.
    private bool IsAjaxRequest() =>
        string.Equals(Request.Headers["X-Requested-With"], "XMLHttpRequest", StringComparison.OrdinalIgnoreCase);

    private async Task<IActionResult> ExpiredSessionRedirectAsync()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        if (IsAjaxRequest())
        {
            return Unauthorized();
        }
        return RedirectToAction("Login", "User", new { area = "" });
    }

    // App: ECL | Module: ECL Report
    public IActionResult AutonomousGranteeBodies()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Autonomous/Grantee Bodies";
        return View();
    }

    // App: ECL | Module: ECL Report
    public IActionResult AutonomousGranteeBodiesStatus()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies Status";
        ViewData["Breadcrumb"] = "ECL / ECL Report / Autonomous/Grantee Bodies Status";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
