// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DebtModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DebtModule")]
[Authorize]
public class DataVisualizationController : Controller
{
    // App: Debt Module | Module: Data Visualization
    public IActionResult DCPMonthlyChart()
    {
        ViewData["Title"] = "DCP Monthly Chart";
        ViewData["Breadcrumb"] = "Debt Module / Data Visualization / DCP Monthly Chart";
        return View();
    }

    // App: Debt Module | Module: Data Visualization
    public IActionResult WeightedAverageGraph()
    {
        ViewData["Title"] = " Weighted  Average Graph";
        ViewData["Breadcrumb"] = "Debt Module / Data Visualization /  Weighted  Average Graph";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
