// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DebtModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DebtModule")]
[Authorize]
public class DataEntryController : Controller
{
    // App: Debt Module | Module: Data Entry
    public IActionResult TreasuryBills()
    {
        ViewData["Title"] = "Treasury Bills";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / Treasury Bills";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult DCPExcelFileImport()
    {
        ViewData["Title"] = "DCP Excel File Import";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / DCP Excel File Import";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult DCPDetails()
    {
        ViewData["Title"] = "DCP Details";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / DCP Details";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult IntermediateLiability()
    {
        ViewData["Title"] = "Intermediate Liability";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / Intermediate Liability";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult HistoricDataonLiability()
    {
        ViewData["Title"] = "Historic Data on Liability";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / Historic Data on Liability";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult DatedSecurityAuctionDetails()
    {
        ViewData["Title"] = "Dated Security Auction Details";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / Dated Security Auction Details";
        return View();
    }

    // App: Debt Module | Module: Data Entry
    public IActionResult OtherLiability()
    {
        ViewData["Title"] = "Other Liability";
        ViewData["Breadcrumb"] = "Debt Module / Data Entry / Other Liability";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
