// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DebtModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DebtModule")]
[Authorize]
public class MastersController : Controller
{
    // App: Debt Module | Module: Masters
    public IActionResult DebtLiability()
    {
        ViewData["Title"] = "Debt   Liability";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Debt   Liability";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult SBELayout()
    {
        ViewData["Title"] = "SBE Layout";
        ViewData["Breadcrumb"] = "Debt Module / Masters / SBE Layout";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult PublicDebt()
    {
        ViewData["Title"] = "Public Debt";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Public Debt";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult Securities()
    {
        ViewData["Title"] = "Securities";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Securities";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddCategory()
    {
        ViewData["Title"] = "Add Category";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add Category";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddSubCategory()
    {
        ViewData["Title"] = "Add SubCategory";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add SubCategory";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddSchemes()
    {
        ViewData["Title"] = "Add Schemes";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add Schemes";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddSubSchemes()
    {
        ViewData["Title"] = "Add Sub Schemes";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add Sub Schemes";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddUmbrellaSchemes()
    {
        ViewData["Title"] = "Add Umbrella Schemes";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add Umbrella Schemes";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult AddMajorHead()
    {
        ViewData["Title"] = "Add Major Head";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Add Major Head";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult DemandMajorHeadMapping()
    {
        ViewData["Title"] = "Demand MajorHead Mapping";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Demand MajorHead Mapping";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult DemandContactDetails()
    {
        ViewData["Title"] = "Demand Contact Details";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Demand Contact Details";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult Category()
    {
        ViewData["Title"] = "Category";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Category";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult Group()
    {
        ViewData["Title"] = "Group";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Group";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult Scheme()
    {
        ViewData["Title"] = "Scheme";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Scheme";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult SubScheme()
    {
        ViewData["Title"] = "SubScheme";
        ViewData["Breadcrumb"] = "Debt Module / Masters / SubScheme";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult MajorHead()
    {
        ViewData["Title"] = "Major Head";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Major Head";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult ReissuedSecurities()
    {
        ViewData["Title"] = "Reissued Securities";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Reissued Securities";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult DCPReceiptPaymentSource()
    {
        ViewData["Title"] = "DCP Receipt Payment Source";
        ViewData["Breadcrumb"] = "Debt Module / Masters / DCP Receipt Payment Source";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult DCPReceiptandPaymentDetails()
    {
        ViewData["Title"] = "DCP Receipt and Payment Details";
        ViewData["Breadcrumb"] = "Debt Module / Masters / DCP Receipt and Payment Details";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult InterestRateOfWMAOD()
    {
        ViewData["Title"] = "Interest Rate Of WMA & OD";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Interest Rate Of WMA & OD";
        return View();
    }

    // App: Debt Module | Module: Masters
    public IActionResult DatedSecurities()
    {
        ViewData["Title"] = "Dated Securities";
        ViewData["Breadcrumb"] = "Debt Module / Masters / Dated Securities";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
