// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DebtModule.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DebtModule")]
[Authorize]
public class ReportsController : Controller
{
    // App: Debt Module | Module: Reports
    public IActionResult Liability()
    {
        ViewData["Title"] = "Liability";
        ViewData["Breadcrumb"] = "Debt Module / Reports / Liability";
        return View();
    }

    // App: Debt Module | Module: Reports
    public IActionResult DetailedMonthlyLiabilityStatement()
    {
        ViewData["Title"] = "Detailed Monthly Liability Statement";
        ViewData["Breadcrumb"] = "Debt Module / Reports / Detailed Monthly Liability Statement";
        return View();
    }

    // App: Debt Module | Module: Reports
    public IActionResult SummarizedLiabilityStatement()
    {
        ViewData["Title"] = "Summarized Liability Statement";
        ViewData["Breadcrumb"] = "Debt Module / Reports / Summarized Liability Statement";
        return View();
    }

    // App: Debt Module | Module: Reports
    public IActionResult DailyCashPosition()
    {
        ViewData["Title"] = "Daily Cash Position";
        ViewData["Breadcrumb"] = "Debt Module / Reports / Daily Cash Position";
        return View();
    }

    // App: Debt Module | Module: Reports
    public IActionResult DailyInterestOnSurplusCashInvst()
    {
        ViewData["Title"] = "Daily Interest On Surplus Cash Invst";
        ViewData["Breadcrumb"] = "Debt Module / Reports / Daily Interest On Surplus Cash Invst";
        return View();
    }

    // App: Debt Module | Module: Reports
    public IActionResult WMAODInterest()
    {
        ViewData["Title"] = "WMA/OD Interest";
        ViewData["Breadcrumb"] = "Debt Module / Reports / WMA/OD Interest";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
