<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>UBIS.Services.PreBudget.Domain</RootNamespace>
    <AssemblyName>PreBudget.Domain</AssemblyName>
  </PropertyGroup>

</Project>
