// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.AutonomousGranteeBodies.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("AutonomousGranteeBodies")]
[Authorize]
public class ECLApproveController : Controller
{
    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult DataToApprove()
    {
        ViewData["Title"] = "Data To Approve";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Data To Approve";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult DataForReapproval()
    {
        ViewData["Title"] = "Data For Reapproval";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Data For Reapproval";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult PensionersDataforApproval()
    {
        ViewData["Title"] = "Pensioners Data for Approval";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Pensioners Data for Approval";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult EmployeeDataforApproval()
    {
        ViewData["Title"] = "Employee Data for Approval";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Employee Data for Approval";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult AutonomousGranteeDataforApproval()
    {
        ViewData["Title"] = "Autonomous/Grantee Data for Approval";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Autonomous/Grantee Data for Approval";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult PayandAllowancesDataforApproval()
    {
        ViewData["Title"] = "Pay and Allowances Data for Approval";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Pay and Allowances Data for Approval";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Approve
    public IActionResult ProvisionForReapprovalAutonomous()
    {
        ViewData["Title"] = "Provision For Reapproval Autonomous";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Approve / Provision For Reapproval Autonomous";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
