// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.AutonomousGranteeBodies.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("AutonomousGranteeBodies")]
[Authorize]
public class ECLDataEntryController : Controller
{
    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddSchemeOutlay()
    {
        ViewData["Title"] = "Add Scheme Outlay";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Scheme Outlay";
        return View();



    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddActuals()
    {
        ViewData["Title"] = "Add Actuals";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Actuals";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddPensionersData()
    {
        ViewData["Title"] = "Add Pensioners Data";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Pensioners Data";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddEmployeesData()
    {
        ViewData["Title"] = "Add Employees Data";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Employees Data";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddAutonomousGranteeData()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Data";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Autonomous/Grantee Data";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult PayandAllowancesExpenditure()
    {
        ViewData["Title"] = "Pay and Allowances Expenditure";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Pay and Allowances Expenditure";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AddAutonomousGranteeName()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Name";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Add Autonomous/Grantee Name";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AutonomousGranteeReports()
    {
        ViewData["Title"] = "Autonomous/Grantee Reports";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Autonomous/Grantee Reports";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Data Entry
    public IActionResult AutonomousGranteeBodiesStatus()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies Status";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Data Entry / Autonomous/Grantee Bodies Status";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
