// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.AutonomousGranteeBodies.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("AutonomousGranteeBodies")]
[Authorize]
public class ECLMasterController : Controller
{
    // App: Autonomous/Grantee Bodies | Module: ECL Master
    public IActionResult AddAutonomousGranteeName()
    {
        ViewData["Title"] = "Add Autonomous/Grantee Name";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Master / Add Autonomous/Grantee Name";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Master
    public IActionResult AddSchemes()
    {
        ViewData["Title"] = "Add Schemes";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Master / Add Schemes";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
