// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.AutonomousGranteeBodies.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("AutonomousGranteeBodies")]
[Authorize]
public class ECLReportController : Controller
{
    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult DataAnalysis()
    {
        ViewData["Title"] = "Data Analysis";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Data Analysis";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult DemandWiseECLStatus()
    {
        ViewData["Title"] = "Demand Wise ECL Status ";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Demand Wise ECL Status ";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult PendingDemand()
    {
        ViewData["Title"] = "Pending Demand";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Pending Demand";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult AutonomousGranteeBodies()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Autonomous/Grantee Bodies";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult AutonomousGranteeBodiesStatus()
    {
        ViewData["Title"] = "Autonomous/Grantee Bodies Status";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Autonomous/Grantee Bodies Status";
        return View();
    }

    // App: Autonomous/Grantee Bodies | Module: ECL Report
    public IActionResult DemandWiseECLStatusTopLine()
    {
        ViewData["Title"] = "Demand Wise ECL Status Top Line";
        ViewData["Breadcrumb"] = "Autonomous/Grantee Bodies / ECL Report / Demand Wise ECL Status Top Line";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
