// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.MTEF.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("MTEF")]
[Authorize]
public class FinalizationController : Controller
{
    // App: MTEF | Module: Finalization
    public IActionResult MTEF()
    {
        ViewData["Title"] = "MTEF";
        ViewData["Breadcrumb"] = "MTEF / Finalization / MTEF";
        return View();
    }

    // App: MTEF | Module: Finalization
    public IActionResult ObjectHeadDataFinalization()
    {
        ViewData["Title"] = "Object Head Data Finalization";
        ViewData["Breadcrumb"] = "MTEF / Finalization / Object Head Data Finalization";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
