// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.MTEF.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("MTEF")]
[Authorize]
public class MasterController : Controller
{
    // App: MTEF | Module: Master
    public IActionResult AddMTEFCategory()
    {
        ViewData["Title"] = "Add MTEF  Category";
        ViewData["Breadcrumb"] = "MTEF / Master / Add MTEF  Category";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult AddObjectHeadName()
    {
        ViewData["Title"] = "Add ObjectHead Name";
        ViewData["Breadcrumb"] = "MTEF / Master / Add ObjectHead Name";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult MappingMTEFCategory()
    {
        ViewData["Title"] = "Mapping MTEF Category";
        ViewData["Breadcrumb"] = "MTEF / Master / Mapping MTEF Category";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult MappingObjectHead()
    {
        ViewData["Title"] = "Mapping Object Head";
        ViewData["Breadcrumb"] = "MTEF / Master / Mapping Object Head";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult MTEFUmbrellaSchemes()
    {
        ViewData["Title"] = "MTEF Umbrella Schemes";
        ViewData["Breadcrumb"] = "MTEF / Master / MTEF Umbrella Schemes";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult MTEFSchemeMapping()
    {
        ViewData["Title"] = "MTEF Scheme Mapping";
        ViewData["Breadcrumb"] = "MTEF / Master / MTEF Scheme Mapping";
        return View();
    }

    // App: MTEF | Module: Master
    public IActionResult MTEFSubSchemeMapping()
    {
        ViewData["Title"] = "MTEFSub Scheme Mapping";
        ViewData["Breadcrumb"] = "MTEF / Master / MTEFSub Scheme Mapping";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
