// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.MTEF.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("MTEF")]
[Authorize]
public class MTEFAllocationController : Controller
{
    // App: MTEF | Module: MTEF Allocation
    public IActionResult MTEFDemandAllocation()
    {
        ViewData["Title"] = "MTEF Demand Allocation";
        ViewData["Breadcrumb"] = "MTEF / MTEF Allocation / MTEF Demand Allocation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
