// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.MTEF.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("MTEF")]
[Authorize]
public class MTEFReportsController : Controller
{
    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureIIMTEFDemandWiseForDepartment()
    {
        ViewData["Title"] = "Annexure II (MTEF Demand Wise) For Department";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure II (MTEF Demand Wise) For Department";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult SchemeWiseProjection()
    {
        ViewData["Title"] = "SchemeWise Projection";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / SchemeWise Projection";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureICategoryWise()
    {
        ViewData["Title"] = "Annexure I (Category Wise)";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure I (Category Wise)";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureIDetailed()
    {
        ViewData["Title"] = "Annexure I Detailed";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure I Detailed";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureIIMTEFDemandWise()
    {
        ViewData["Title"] = "Annexure II (MTEF Demand Wise)";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure II (MTEF Demand Wise)";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult MTEFProjection()
    {
        ViewData["Title"] = "MTEF Projection";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / MTEF Projection";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult MTEFStatus()
    {
        ViewData["Title"] = "MTEF Status";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / MTEF Status";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult MTFPProjection()
    {
        ViewData["Title"] = "MTFP Projection";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / MTFP Projection";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult FinalProjection()
    {
        ViewData["Title"] = "Final Projection";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Final Projection";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult DemandWiseProjectionLogReport()
    {
        ViewData["Title"] = "Demand Wise Projection Log Report";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Demand Wise Projection Log Report";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult MTEFProjectionLog()
    {
        ViewData["Title"] = "MTEF Projection Log";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / MTEF Projection Log";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult MTEFProjectionsSubmittedbyUsers()
    {
        ViewData["Title"] = "MTEF Projections Submitted by Users";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / MTEF Projections Submitted by Users";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult SchemeWiseProjectionLog()
    {
        ViewData["Title"] = "Scheme Wise Projection Log";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Scheme Wise Projection Log";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureIIListOfMajorSchemes()
    {
        ViewData["Title"] = "Annexure II (List Of Major Schemes)";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure II (List Of Major Schemes)";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult AnnexureIIListOfMajorSchemesDetails()
    {
        ViewData["Title"] = "Annexure II (List Of Major Schemes Details)	";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / Annexure II (List Of Major Schemes Details)	";
        return View();
    }

    // App: MTEF | Module: MTEF Reports
    public IActionResult SchemeWiseRevenueCapital()
    {
        ViewData["Title"] = "SchemeWise Revenue/Capital";
        ViewData["Breadcrumb"] = "MTEF / MTEF Reports / SchemeWise Revenue/Capital";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
