// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.MTEF.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("MTEF")]
[Authorize]
public class ProjectionsController : Controller
{
    // App: MTEF | Module: Projections
    public IActionResult AddMTEFData()
    {
        ViewData["Title"] = "Add MTEF Data";
        ViewData["Breadcrumb"] = "MTEF / Projections / Add MTEF Data";
        return View();
    }

    // App: MTEF | Module: Projections
    public IActionResult AddSchemeWiseProjection()
    {
        ViewData["Title"] = "Add SchemeWise Projection";
        ViewData["Breadcrumb"] = "MTEF / Projections / Add SchemeWise Projection";
        return View();
    }

    // App: MTEF | Module: Projections
    public IActionResult AddMTEFObjectheadData()
    {
        ViewData["Title"] = "Add MTEF Object head Data";
        ViewData["Breadcrumb"] = "MTEF / Projections / Add MTEF Object head Data";
        return View();
    }

    // App: MTEF | Module: Projections
    public IActionResult AddMTFPData()
    {
        ViewData["Title"] = "Add MTFP Data";
        ViewData["Breadcrumb"] = "MTEF / Projections / Add MTFP Data";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
