namespace UBIS.Services.MenuGenerator.Infrastructure.Persistence.DevSeed.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UBIS.Services.MenuGenerator.Domain.Entities;

/// <summary>
/// Dev/test-seed-only configuration for Function - creates and seeds "M_Function"
/// in the standalone dev/test database (separate from the production, read-only legacy tables).
/// </summary>
public class FunctionSeedConfiguration : IEntityTypeConfiguration<Function>
{
    public void Configure(EntityTypeBuilder<Function> builder)
    {
        builder.ToTable("M_Function", "dbo");
        builder.HasKey(x => x.FunctionId);
        builder.Property(x => x.FunctionId).HasColumnName("FunctionId").ValueGeneratedNever();
        builder.Property(x => x.FunctionName).HasColumnName("FunctionName");

        builder.HasData(
            new Function { FunctionId = 21, FunctionName = "Role" },
            new Function { FunctionId = 26, FunctionName = "SMS Email Template" },
            new Function { FunctionId = 27, FunctionName = "Module" },
            new Function { FunctionId = 28, FunctionName = "Function" },
            new Function { FunctionId = 29, FunctionName = "Role Module Mapping" },
            new Function { FunctionId = 30, FunctionName = "Role Function Mapping" },
            new Function { FunctionId = 58, FunctionName = "Audit Log" },
            new Function { FunctionId = 65, FunctionName = "FAQ" },
            new Function { FunctionId = 69, FunctionName = "Change Password" },
            new Function { FunctionId = 70, FunctionName = "Logout" },
            new Function { FunctionId = 71, FunctionName = "Add MTEF  Category" },
            new Function { FunctionId = 72, FunctionName = "Form  Label" },
            new Function { FunctionId = 73, FunctionName = "Add MTEF Data" },
            new Function { FunctionId = 74, FunctionName = "MTEF" },
            new Function { FunctionId = 79, FunctionName = "Create User" },
            new Function { FunctionId = 84, FunctionName = "MTEF Annexure II" },
            new Function { FunctionId = 86, FunctionName = "Mapping Object Head" },
            new Function { FunctionId = 87, FunctionName = "Mapping MTEF Category" },
            new Function { FunctionId = 88, FunctionName = "Object Head Data Finalization" },
            new Function { FunctionId = 89, FunctionName = "MTEF Major Expenditure Category" },
            new Function { FunctionId = 90, FunctionName = "Add MTFP Data" },
            new Function { FunctionId = 91, FunctionName = "MTFP Projection" },
            new Function { FunctionId = 92, FunctionName = "Annexure I (Category Wise)" },
            new Function { FunctionId = 95, FunctionName = "Select Demand" },
            new Function { FunctionId = 96, FunctionName = "MTEF Projection Log" },
            new Function { FunctionId = 99, FunctionName = "Create Circular/Letter" },
            new Function { FunctionId = 100, FunctionName = "List of Circulars" },
            new Function { FunctionId = 101, FunctionName = "Circular" },
            new Function { FunctionId = 102, FunctionName = "MTEF Projection" },
            new Function { FunctionId = 103, FunctionName = "Add MTFP Data" },
            new Function { FunctionId = 104, FunctionName = "Add MTEF Object head Data" },
            new Function { FunctionId = 105, FunctionName = "MTEF Object Head" },
            new Function { FunctionId = 106, FunctionName = "MTEF Status" },
            new Function { FunctionId = 107, FunctionName = "MTFP Projection" },
            new Function { FunctionId = 108, FunctionName = "MTEF Projection Log" },
            new Function { FunctionId = 109, FunctionName = "User  Allocation" },
            new Function { FunctionId = 110, FunctionName = "Final Projection" },
            new Function { FunctionId = 111, FunctionName = "Annexure II (MTEF Demand Wise) For Department" },
            new Function { FunctionId = 112, FunctionName = "Nodal Officer" },
            new Function { FunctionId = 113, FunctionName = "Demand Wise Projection Log Report" },
            new Function { FunctionId = 114, FunctionName = "Circular Report" },
            new Function { FunctionId = 115, FunctionName = "Annexure II (MTEF Demand Wise)" },
            new Function { FunctionId = 116, FunctionName = "Layout Master" },
            new Function { FunctionId = 117, FunctionName = "Add Category" },
            new Function { FunctionId = 118, FunctionName = "Add SubCategory" },
            new Function { FunctionId = 119, FunctionName = "Add Schemes" },
            new Function { FunctionId = 120, FunctionName = "Add CSS Schemes" },
            new Function { FunctionId = 121, FunctionName = "Add CSS SubSchemes" },
            new Function { FunctionId = 122, FunctionName = "Add Ministry" },
            new Function { FunctionId = 123, FunctionName = "Add Department" },
            new Function { FunctionId = 124, FunctionName = "Add Demand" },
            new Function { FunctionId = 125, FunctionName = "Add Umbrella Schemes" },
            new Function { FunctionId = 126, FunctionName = "Add Sub Schemes" },
            new Function { FunctionId = 127, FunctionName = "Add PSE Category" },
            new Function { FunctionId = 128, FunctionName = "Investment in PSE" },
            new Function { FunctionId = 129, FunctionName = "Demand  Wise  Scheme/SubScheme" },
            new Function { FunctionId = 130, FunctionName = "Demand Wise Scheme/SubScheme" },
            new Function { FunctionId = 131, FunctionName = "Add Receipt Budget" },
            new Function { FunctionId = 132, FunctionName = "User Initialization" },
            new Function { FunctionId = 133, FunctionName = "Demand Change by single user" },
            new Function { FunctionId = 134, FunctionName = "Add SBE" },
            new Function { FunctionId = 135, FunctionName = "Add Major Head" },
            new Function { FunctionId = 136, FunctionName = "Demand MajorHead Mapping" },
            new Function { FunctionId = 137, FunctionName = "Select  Demand Section Wise" },
            new Function { FunctionId = 138, FunctionName = "Add SBE Notes" },
            new Function { FunctionId = 139, FunctionName = "Renumber SBE Notes" },
            new Function { FunctionId = 140, FunctionName = "Add Group" },
            new Function { FunctionId = 141, FunctionName = "Generate SBE" },
            new Function { FunctionId = 142, FunctionName = "Generate DG" },
            new Function { FunctionId = 143, FunctionName = "MajorHead Wise Difference" },
            new Function { FunctionId = 144, FunctionName = "Major Head Wise BE  Difference" },
            new Function { FunctionId = 145, FunctionName = "Category" },
            new Function { FunctionId = 146, FunctionName = "SubCategory" },
            new Function { FunctionId = 147, FunctionName = " Schemes" },
            new Function { FunctionId = 148, FunctionName = "Sub Schemes" },
            new Function { FunctionId = 149, FunctionName = "Umbrella Scheme" },
            new Function { FunctionId = 150, FunctionName = "Major Head" },
            new Function { FunctionId = 151, FunctionName = "SBE Notes" },
            new Function { FunctionId = 152, FunctionName = "SBE Layout" },
            new Function { FunctionId = 153, FunctionName = "SBE Notes" },
            new Function { FunctionId = 154, FunctionName = "Renumber SBE Notes" },
            new Function { FunctionId = 155, FunctionName = "MTEF Finalization" },
            new Function { FunctionId = 156, FunctionName = "ObjectHead Finalization" },
            new Function { FunctionId = 157, FunctionName = "Demand Wise Scheme/SubScheme" },
            new Function { FunctionId = 158, FunctionName = "Category Wise Scheme/Subscheme" },
            new Function { FunctionId = 159, FunctionName = "Renumber Scheme SrNo" },
            new Function { FunctionId = 160, FunctionName = "Renumber SubScheme SrNo" },
            new Function { FunctionId = 161, FunctionName = "Add Charged/Recoveries" },
            new Function { FunctionId = 162, FunctionName = "Add Charged " },
            new Function { FunctionId = 163, FunctionName = "Receipt Budget Notes" },
            new Function { FunctionId = 164, FunctionName = "Statement Layout" },
            new Function { FunctionId = 165, FunctionName = "Statement Entry" },
            new Function { FunctionId = 166, FunctionName = "Add Scheme" },
            new Function { FunctionId = 167, FunctionName = "Add SubScheme" },
            new Function { FunctionId = 168, FunctionName = "Add Program" },
            new Function { FunctionId = 169, FunctionName = "Renumber SchemeSrNo" },
            new Function { FunctionId = 170, FunctionName = "Renumber SubScheme SrNo" },
            new Function { FunctionId = 171, FunctionName = "Renumber Program SrNo" },
            new Function { FunctionId = 172, FunctionName = "Renumber SubProgramSrNo" },
            new Function { FunctionId = 173, FunctionName = "Scheme" },
            new Function { FunctionId = 174, FunctionName = "Sub Scheme" },
            new Function { FunctionId = 175, FunctionName = "Program" },
            new Function { FunctionId = 176, FunctionName = "Group" },
            new Function { FunctionId = 177, FunctionName = "Import Actuals From DDG" },
            new Function { FunctionId = 178, FunctionName = "Generate SBE UserWise" },
            new Function { FunctionId = 179, FunctionName = "Recovery Report" },
            new Function { FunctionId = 180, FunctionName = "Generate SBE MajorHeadWise" },
            new Function { FunctionId = 181, FunctionName = "DG Summary" },
            new Function { FunctionId = 182, FunctionName = "Receipt MajorHeadWise" },
            new Function { FunctionId = 183, FunctionName = "Combined A Part Top Lines" },
            new Function { FunctionId = 184, FunctionName = "Receipt/Recovery/Charged Report" },
            new Function { FunctionId = 185, FunctionName = "Add Statement Notes" },
            new Function { FunctionId = 186, FunctionName = "Customized Report" },
            new Function { FunctionId = 187, FunctionName = "Charged Report" },
            new Function { FunctionId = 188, FunctionName = "Add SpecialSchemeName" },
            new Function { FunctionId = 189, FunctionName = "Mapping of Statement 7, 8 and 18" },
            new Function { FunctionId = 190, FunctionName = "Generate Statements" },
            new Function { FunctionId = 191, FunctionName = "Assistance Given To Autonomous/Grantee Bodies" },
            new Function { FunctionId = 192, FunctionName = "Statement Report" },
            new Function { FunctionId = 193, FunctionName = "Statement Page Detail" },
            new Function { FunctionId = 194, FunctionName = "Generate DG For All Demands" },
            new Function { FunctionId = 195, FunctionName = "Add AFS For UT" },
            new Function { FunctionId = 196, FunctionName = "Receipt" },
            new Function { FunctionId = 197, FunctionName = "Add Group" },
            new Function { FunctionId = 198, FunctionName = "Add Scheme" },
            new Function { FunctionId = 199, FunctionName = "Add SubScheme" },
            new Function { FunctionId = 200, FunctionName = "Add  Data for Public Account" },
            new Function { FunctionId = 201, FunctionName = "Add Cash for Public Account" },
            new Function { FunctionId = 202, FunctionName = "Report for RECEIPTS" },
            new Function { FunctionId = 203, FunctionName = "Report for DISBURSMENTS" },
            new Function { FunctionId = 204, FunctionName = "Expenditure " },
            new Function { FunctionId = 205, FunctionName = "SBE Page Break" },
            new Function { FunctionId = 206, FunctionName = "Renumber Notes" },
            new Function { FunctionId = 207, FunctionName = "PSE Category" },
            new Function { FunctionId = 208, FunctionName = "Investment PSE Name" },
            new Function { FunctionId = 209, FunctionName = "Statement Union Territories Report" },
            new Function { FunctionId = 210, FunctionName = "Genearate DG (Plan/NonPlan  Breakup)" },
            new Function { FunctionId = 211, FunctionName = "Generate DG (Plan/NonPlan)" },
            new Function { FunctionId = 212, FunctionName = "Add SchemeWise Projection" },
            new Function { FunctionId = 213, FunctionName = "MTEF" },
            new Function { FunctionId = 214, FunctionName = "Add Supplementary MajorHeadWise" },
            new Function { FunctionId = 215, FunctionName = "Add ObjectHead Name" },
            new Function { FunctionId = 216, FunctionName = "SchemeWise Projection" },
            new Function { FunctionId = 217, FunctionName = "test function" },
            new Function { FunctionId = 218, FunctionName = "MTEF Scheme Mapping" },
            new Function { FunctionId = 219, FunctionName = "MTEF Umbrella Schemes" },
            new Function { FunctionId = 220, FunctionName = "MTEFSub Scheme Mapping" },
            new Function { FunctionId = 221, FunctionName = "Add DemandWise Page No" },
            new Function { FunctionId = 222, FunctionName = "Add NoteCode" },
            new Function { FunctionId = 223, FunctionName = "Freeze Supplementary" },
            new Function { FunctionId = 224, FunctionName = "Generate Supplementary (Approved by SD)" },
            new Function { FunctionId = 225, FunctionName = "Generate Reports" },
            new Function { FunctionId = 226, FunctionName = "Annexure II (List Of Major Schemes)" },
            new Function { FunctionId = 227, FunctionName = "Freeze Status Report" },
            new Function { FunctionId = 228, FunctionName = "Add Annexure" },
            new Function { FunctionId = 229, FunctionName = "Update Hindi Notes" },
            new Function { FunctionId = 230, FunctionName = "Log Report" },
            new Function { FunctionId = 231, FunctionName = "Annexure I" },
            new Function { FunctionId = 232, FunctionName = "UnFreeze Supplementary" },
            new Function { FunctionId = 233, FunctionName = "Add Vet Status" },
            new Function { FunctionId = 234, FunctionName = "Allocate Vet Date" },
            new Function { FunctionId = 235, FunctionName = "Vet Status Report" },
            new Function { FunctionId = 236, FunctionName = "Check Sheet" },
            new Function { FunctionId = 237, FunctionName = "MTEF Projections Submitted by Users" },
            new Function { FunctionId = 238, FunctionName = "Scheme Wise Projection Log" },
            new Function { FunctionId = 239, FunctionName = "Annexure II (List Of Major Schemes Details) " },
            new Function { FunctionId = 240, FunctionName = "Mapping of SBE Schemes/SubSchemes" },
            new Function { FunctionId = 241, FunctionName = "Data Entry For New Head of Accounts" },
            new Function { FunctionId = 242, FunctionName = "Edit DDG" },
            new Function { FunctionId = 243, FunctionName = "Generate DDG" },
            new Function { FunctionId = 244, FunctionName = "Mismatch Summary of DDG with SBE" },
            new Function { FunctionId = 245, FunctionName = "Generate DDG(Old Format)" },
            new Function { FunctionId = 246, FunctionName = "Add HOA in ACTDRX" },
            new Function { FunctionId = 247, FunctionName = "DDG Head of Accounts not mapped" },
            new Function { FunctionId = 248, FunctionName = "SBE Schemes not mapped" },
            new Function { FunctionId = 249, FunctionName = "Status of Demand (SBE Vs DDG)" },
            new Function { FunctionId = 250, FunctionName = "Combined Dashboard" },
            new Function { FunctionId = 251, FunctionName = "Ministry/Department/Demand" },
            new Function { FunctionId = 252, FunctionName = "Master" },
            new Function { FunctionId = 253, FunctionName = "Sub Category" },
            new Function { FunctionId = 254, FunctionName = "Umbrella Scheme" },
            new Function { FunctionId = 255, FunctionName = "Scheme" },
            new Function { FunctionId = 256, FunctionName = "Sub Scheme " },
            new Function { FunctionId = 257, FunctionName = "SBE Data" },
            new Function { FunctionId = 258, FunctionName = "Recoveries Charged Data" },
            new Function { FunctionId = 259, FunctionName = "PSE Category" },
            new Function { FunctionId = 260, FunctionName = "Budgetary SupportIEBR Data" },
            new Function { FunctionId = 261, FunctionName = "SBE Notes" },
            new Function { FunctionId = 262, FunctionName = "Demand Major Head" },
            new Function { FunctionId = 263, FunctionName = "SBE/Stmt Layout" },
            new Function { FunctionId = 264, FunctionName = "SBE Caption" },
            new Function { FunctionId = 265, FunctionName = "SBE Caption data" },
            new Function { FunctionId = 266, FunctionName = "Statement" },
            new Function { FunctionId = 267, FunctionName = "Statement Group" },
            new Function { FunctionId = 268, FunctionName = "Statement Scheme" },
            new Function { FunctionId = 269, FunctionName = "Statement  SubScheme" },
            new Function { FunctionId = 270, FunctionName = "Statement Data" },
            new Function { FunctionId = 271, FunctionName = "Receipt" },
            new Function { FunctionId = 272, FunctionName = "Scheme" },
            new Function { FunctionId = 273, FunctionName = "SubScheme" },
            new Function { FunctionId = 274, FunctionName = "Statement SC/ST" },
            new Function { FunctionId = 275, FunctionName = "Control Status" },
            new Function { FunctionId = 276, FunctionName = "RE Data and Report" },
            new Function { FunctionId = 277, FunctionName = "Merge Demand No" },
            new Function { FunctionId = 278, FunctionName = "PSE Template" },
            new Function { FunctionId = 279, FunctionName = "RE Consolidated" },
            new Function { FunctionId = 280, FunctionName = "RE Data Remarks" },
            new Function { FunctionId = 281, FunctionName = "Supp Demand Allocation" },
            new Function { FunctionId = 282, FunctionName = "Group" },
            new Function { FunctionId = 283, FunctionName = "Sub Scheme" },
            new Function { FunctionId = 284, FunctionName = "Scheme" },
            new Function { FunctionId = 285, FunctionName = "DDG" },
            new Function { FunctionId = 286, FunctionName = "HOA not In DDG" },
            new Function { FunctionId = 287, FunctionName = "HOA not In PFMS" },
            new Function { FunctionId = 288, FunctionName = "MTEF Demand Allocation" },
            new Function { FunctionId = 289, FunctionName = "Generate Statement" },
            new Function { FunctionId = 290, FunctionName = "Cash Outflow Log" },
            new Function { FunctionId = 291, FunctionName = "Add Debt/Deficit " },
            new Function { FunctionId = 292, FunctionName = "Add BAG Notes" },
            new Function { FunctionId = 293, FunctionName = "Add BAG Data" },
            new Function { FunctionId = 294, FunctionName = "Special  Scheme" },
            new Function { FunctionId = 295, FunctionName = "Subsidy  Group" },
            new Function { FunctionId = 296, FunctionName = "Program" },
            new Function { FunctionId = 297, FunctionName = "SubProgram" },
            new Function { FunctionId = 298, FunctionName = "Budget Data" },
            new Function { FunctionId = 299, FunctionName = "Adhoc Queries Report" },
            new Function { FunctionId = 300, FunctionName = "Generate DG" },
            new Function { FunctionId = 301, FunctionName = "DG Summary" },
            new Function { FunctionId = 302, FunctionName = "AFS" },
            new Function { FunctionId = 303, FunctionName = "Group" },
            new Function { FunctionId = 304, FunctionName = "Scheme" },
            new Function { FunctionId = 305, FunctionName = "Sub Scheme" },
            new Function { FunctionId = 306, FunctionName = "Select  Receipt Demand" },
            new Function { FunctionId = 307, FunctionName = "Edit User Details" },
            new Function { FunctionId = 308, FunctionName = "Reset Password" },
            new Function { FunctionId = 309, FunctionName = "Actuals/BE/Category Change Permission" },
            new Function { FunctionId = 310, FunctionName = "Receipts" },
            new Function { FunctionId = 311, FunctionName = "Receipt  SBE Notes" },
            new Function { FunctionId = 312, FunctionName = "Edit Hindi HOA" },
            new Function { FunctionId = 313, FunctionName = "DG Summary before transfer to PFMS" },
            new Function { FunctionId = 314, FunctionName = "DG MH wise  before transfer to PFMS" },
            new Function { FunctionId = 315, FunctionName = "DDG Data before transfer to PFMS" },
            new Function { FunctionId = 316, FunctionName = "Add Supplementary Number" },
            new Function { FunctionId = 317, FunctionName = "Transfer to States Mapping" },
            new Function { FunctionId = 318, FunctionName = "Deactive Supplementary Number" },
            new Function { FunctionId = 319, FunctionName = "Export DG Summary to PFMS" },
            new Function { FunctionId = 320, FunctionName = "Export DG MajorHead Wise to PFMS" },
            new Function { FunctionId = 321, FunctionName = "Export DDG Data to PFMS" },
            new Function { FunctionId = 322, FunctionName = "Merge/Renumber/update Demand" },
            new Function { FunctionId = 323, FunctionName = "Demand Wise  ObjectHead" },
            new Function { FunctionId = 324, FunctionName = "Object HeadData" },
            new Function { FunctionId = 325, FunctionName = "Financial Year" },
            new Function { FunctionId = 326, FunctionName = "User Demand Initialisation" },
            new Function { FunctionId = 327, FunctionName = "SBE Notes" },
            new Function { FunctionId = 328, FunctionName = "SBE Notes" },
            new Function { FunctionId = 329, FunctionName = "PA Account" },
            new Function { FunctionId = 330, FunctionName = "Receipt Data/Notes" },
            new Function { FunctionId = 331, FunctionName = "PA Sub Scheme" },
            new Function { FunctionId = 332, FunctionName = "User Wise Function Freez" },
            new Function { FunctionId = 333, FunctionName = "MTEF Delete/ Renum/update" },
            new Function { FunctionId = 334, FunctionName = "Sector/SubSector Mapping" },
            new Function { FunctionId = 335, FunctionName = "Customized Sector Report" },
            new Function { FunctionId = 336, FunctionName = "Sector/Subsector Report" },
            new Function { FunctionId = 337, FunctionName = "Trend In Receipt" },
            new Function { FunctionId = 338, FunctionName = "Freeze DDG" },
            new Function { FunctionId = 339, FunctionName = "Add Sector" },
            new Function { FunctionId = 340, FunctionName = "Add SubSector" },
            new Function { FunctionId = 341, FunctionName = "Delete MTEF Initilization" },
            new Function { FunctionId = 342, FunctionName = "Scheme wise Mapping Report" },
            new Function { FunctionId = 343, FunctionName = "Trend in Expenditure" },
            new Function { FunctionId = 344, FunctionName = "Annexure I Detailed" },
            new Function { FunctionId = 345, FunctionName = "SchemeWise Revenue/Capital" },
            new Function { FunctionId = 346, FunctionName = "User Wise Module Freez " },
            new Function { FunctionId = 347, FunctionName = "Autonomous Master for Appendix VI C and VI E" },
            new Function { FunctionId = 348, FunctionName = "Receipt Budget NTR" },
            new Function { FunctionId = 349, FunctionName = "Import Actuals from CGA to DDG" },
            new Function { FunctionId = 350, FunctionName = "Add Notes NTR" },
            new Function { FunctionId = 351, FunctionName = "Notes for NTR" },
            new Function { FunctionId = 352, FunctionName = "Receipt Budget NTR" },
            new Function { FunctionId = 353, FunctionName = "Rupees Chart" },
            new Function { FunctionId = 354, FunctionName = "Deficit Trends" },
            new Function { FunctionId = 355, FunctionName = "Composition Of Expenditure" },
            new Function { FunctionId = 356, FunctionName = "Composition Of Transfers To States" },
            new Function { FunctionId = 357, FunctionName = "Net Receipt Of Centre" },
            new Function { FunctionId = 358, FunctionName = "Total Transfers To States" },
            new Function { FunctionId = 359, FunctionName = "TrendIn Tax Receipts" },
            new Function { FunctionId = 360, FunctionName = "Trend Of Capital Expenditure" },
            new Function { FunctionId = 361, FunctionName = "Sector" },
            new Function { FunctionId = 362, FunctionName = "SubSector" },
            new Function { FunctionId = 363, FunctionName = "Sector wise Mapping" },
            new Function { FunctionId = 364, FunctionName = "Add Notes" },
            new Function { FunctionId = 365, FunctionName = "Sources of Deficit Financing" },
            new Function { FunctionId = 366, FunctionName = "Economic Parameter for 15 to 18 of BAAG " },
            new Function { FunctionId = 367, FunctionName = "Mapping for Major Items" },
            new Function { FunctionId = 368, FunctionName = "All Budget at a Glance Report" },
            new Function { FunctionId = 369, FunctionName = "Graphical Chart" },
            new Function { FunctionId = 370, FunctionName = "Deficit Statistics and Source of Financial Fiscal " },
            new Function { FunctionId = 371, FunctionName = "Receipts" },
            new Function { FunctionId = 372, FunctionName = "Expenditure and Effective Capital Expenditure " },
            new Function { FunctionId = 373, FunctionName = "Transfer of Resources to States and UTs" },
            new Function { FunctionId = 374, FunctionName = "Vote on Account (Interim)" },
            new Function { FunctionId = 375, FunctionName = "NTR" },
            new Function { FunctionId = 376, FunctionName = "NTR" },
            new Function { FunctionId = 377, FunctionName = "Commited Liablities" },
            new Function { FunctionId = 378, FunctionName = "Commited Liablities" },
            new Function { FunctionId = 379, FunctionName = "Control Statement" },
            new Function { FunctionId = 380, FunctionName = "Railway Statements Report" },
            new Function { FunctionId = 381, FunctionName = "Capital Expenditure for Railways" },
            new Function { FunctionId = 382, FunctionName = "Trend of Major" },
            new Function { FunctionId = 383, FunctionName = "Outlay on Major Schemes " },
            new Function { FunctionId = 384, FunctionName = "Investment In PSE Report" },
            new Function { FunctionId = 385, FunctionName = "Single Demand Charged Report" },
            new Function { FunctionId = 386, FunctionName = "Single Demand Receipt Report" },
            new Function { FunctionId = 387, FunctionName = "Single Demand Recovery Report" },
            new Function { FunctionId = 388, FunctionName = "Intro Notes" },
            new Function { FunctionId = 389, FunctionName = "Renumber Umbrella SrNo" },
            new Function { FunctionId = 390, FunctionName = "Scheme to be Excluded from VOA" },
            new Function { FunctionId = 391, FunctionName = "Add Receipt Budget Note" },
            new Function { FunctionId = 392, FunctionName = "Major Scheme Mapping" },
            new Function { FunctionId = 393, FunctionName = "Statement wise scheme" },
            new Function { FunctionId = 394, FunctionName = "Statement Wise Subscheme" },
            new Function { FunctionId = 395, FunctionName = "Receipt NTR" },
            new Function { FunctionId = 396, FunctionName = "Statement Wise Group" },
            new Function { FunctionId = 397, FunctionName = "10A10B and 10BB Statement wise SubScheme" },
            new Function { FunctionId = 398, FunctionName = "10A10B and 10BB Statement wise Scheme" },
            new Function { FunctionId = 399, FunctionName = "Receipt Budget NTR Group Wise" },
            new Function { FunctionId = 400, FunctionName = "Add Notes NTR" },
            new Function { FunctionId = 401, FunctionName = "NTR" },
            new Function { FunctionId = 402, FunctionName = "SBE" },
            new Function { FunctionId = 403, FunctionName = "Statement" },
            new Function { FunctionId = 404, FunctionName = "Revised SBE Demand No" },
            new Function { FunctionId = 405, FunctionName = "Revised STMT Demand No" },
            new Function { FunctionId = 406, FunctionName = "Schemes Master For Stmt 7,8 and 18" },
            new Function { FunctionId = 407, FunctionName = "SBE Status Report" },
            new Function { FunctionId = 408, FunctionName = "Receipt Budget NTR MH Wise" },
            new Function { FunctionId = 409, FunctionName = "User Wise Change Demand" },
            new Function { FunctionId = 410, FunctionName = "Special Scheme ( Stmt 7, 8 and 18 )" },
            new Function { FunctionId = 411, FunctionName = "Add Demand" },
            new Function { FunctionId = 412, FunctionName = "Add Department" },
            new Function { FunctionId = 413, FunctionName = "Add Ministry" },
            new Function { FunctionId = 414, FunctionName = " MajorHead/Demand/Category Wise Scheme/SubScheme" },
            new Function { FunctionId = 415, FunctionName = "Add MajorHead Scheme Name" },
            new Function { FunctionId = 416, FunctionName = "MajorHead Demand Scheme Map" },
            new Function { FunctionId = 417, FunctionName = "HOA Sector Wise Report" },
            new Function { FunctionId = 418, FunctionName = "Sub Programme" },
            new Function { FunctionId = 419, FunctionName = "Statement 17" },
            new Function { FunctionId = 420, FunctionName = "Sector Wise Central Sector Report" },
            new Function { FunctionId = 421, FunctionName = "Demand Wise Expenditures" },
            new Function { FunctionId = 422, FunctionName = "Edit Hindi HOA" },
            new Function { FunctionId = 423, FunctionName = "Receipt Layout" },
            new Function { FunctionId = 424, FunctionName = "Receipt Statement Entry" },
            new Function { FunctionId = 425, FunctionName = "Receipt Layout" },
            new Function { FunctionId = 426, FunctionName = "Receipt Statement Entry" },
            new Function { FunctionId = 427, FunctionName = "Major Sector" },
            new Function { FunctionId = 428, FunctionName = "Major Subsector" },
            new Function { FunctionId = 429, FunctionName = "Add Sector" },
            new Function { FunctionId = 430, FunctionName = "Add SubSector" },
            new Function { FunctionId = 431, FunctionName = "Scheme wise Mapping Report" },
            new Function { FunctionId = 432, FunctionName = "Sector/SubSector Report" },
            new Function { FunctionId = 433, FunctionName = "Scheme wise Mapping Report" },
            new Function { FunctionId = 434, FunctionName = "Sector/SubSector Mapping" },
            new Function { FunctionId = 435, FunctionName = "Export Actuals From DDG to SBE" },
            new Function { FunctionId = 437, FunctionName = "Transfer DDG Data to SBE" },
            new Function { FunctionId = 438, FunctionName = "Add Head of Account for Receipt" },
            new Function { FunctionId = 439, FunctionName = "Permission Report" },
            new Function { FunctionId = 440, FunctionName = "NTR Budget" },
            new Function { FunctionId = 441, FunctionName = "Renumber DemandNo" },
            new Function { FunctionId = 442, FunctionName = "UBIS DemandNo" },
            new Function { FunctionId = 443, FunctionName = "Demand Split" },
            new Function { FunctionId = 444, FunctionName = "RE Report For All Demand " },
            new Function { FunctionId = 445, FunctionName = "Request for IP Change" },
            new Function { FunctionId = 446, FunctionName = "IP Change Request" },
            new Function { FunctionId = 447, FunctionName = "Approve IP Addresses" },
            new Function { FunctionId = 448, FunctionName = "Approve IP Addresses" },
            new Function { FunctionId = 449, FunctionName = "Receipt Layout" },
            new Function { FunctionId = 450, FunctionName = "Assest Register Allocation" },
            new Function { FunctionId = 451, FunctionName = "Asset Notes" },
            new Function { FunctionId = 452, FunctionName = "Group" },
            new Function { FunctionId = 453, FunctionName = "Scheme" },
            new Function { FunctionId = 454, FunctionName = "Asset Register" },
            new Function { FunctionId = 455, FunctionName = "Statement In Excel" },
            new Function { FunctionId = 456, FunctionName = "Receipt NTR Layout" },
            new Function { FunctionId = 457, FunctionName = "Arrears of NTR" },
            new Function { FunctionId = 458, FunctionName = "DemId DemNo Mismatch" },
            new Function { FunctionId = 459, FunctionName = "Receipt Notes" },
            new Function { FunctionId = 460, FunctionName = "Generate SBE(SSRS)" },
            new Function { FunctionId = 461, FunctionName = "Generate SBE (SSRS)" },
            new Function { FunctionId = 462, FunctionName = "Generate SBE In Excel" },
            new Function { FunctionId = 463, FunctionName = "Generate Supplementary (SSRS)" },
            new Function { FunctionId = 464, FunctionName = "Annexure  SchemeWise" },
            new Function { FunctionId = 465, FunctionName = "Annexure SchemeWise" },
            new Function { FunctionId = 466, FunctionName = "Annexure SchemeWise" },
            new Function { FunctionId = 467, FunctionName = "User Wise Module Freeze" },
            new Function { FunctionId = 468, FunctionName = "User Wise Function Freeze" },
            new Function { FunctionId = 469, FunctionName = "Sub Scheme" },
            new Function { FunctionId = 470, FunctionName = "Asset Register Analytics" },
            new Function { FunctionId = 471, FunctionName = "Asset Register" },
            new Function { FunctionId = 472, FunctionName = "Asset Register" },
            new Function { FunctionId = 473, FunctionName = "Arrears Of NTR" },
            new Function { FunctionId = 474, FunctionName = "Arrears Of NTR Analytics Report" },
            new Function { FunctionId = 475, FunctionName = "Operation Ratio" },
            new Function { FunctionId = 476, FunctionName = "BAG Data" },
            new Function { FunctionId = 477, FunctionName = "Asset Register " },
            new Function { FunctionId = 478, FunctionName = "User Details Initialization" },
            new Function { FunctionId = 479, FunctionName = "File Sharing" },
            new Function { FunctionId = 480, FunctionName = "View File Sharing" },
            new Function { FunctionId = 481, FunctionName = "File Sharing" },
            new Function { FunctionId = 482, FunctionName = "Change Statements For User" },
            new Function { FunctionId = 483, FunctionName = "Receipts(SSRS)" },
            new Function { FunctionId = 484, FunctionName = "Organization Name" },
            new Function { FunctionId = 485, FunctionName = "Adhoc Queries Report" },
            new Function { FunctionId = 486, FunctionName = "Adhoc Queries for Statement Eighteen" },
            new Function { FunctionId = 487, FunctionName = "Renumber Department" },
            new Function { FunctionId = 488, FunctionName = "Renumber Ministry" },
            new Function { FunctionId = 489, FunctionName = "Renumber Receipt Notes" },
            new Function { FunctionId = 490, FunctionName = "Machine Readable Data" },
            new Function { FunctionId = 491, FunctionName = "Mapping for Statement 4A" },
            new Function { FunctionId = 492, FunctionName = "Railway statement Entry" },
            new Function { FunctionId = 493, FunctionName = "Railway Allocation" },
            new Function { FunctionId = 494, FunctionName = "Previous Supplementary DemandWise" },
            new Function { FunctionId = 495, FunctionName = "Debt   Liability" },
            new Function { FunctionId = 496, FunctionName = "Public Debt" },
            new Function { FunctionId = 497, FunctionName = "Internal  Debt  Category" },
            new Function { FunctionId = 498, FunctionName = "Securities" },
            new Function { FunctionId = 499, FunctionName = "Reissued Securities" },
            new Function { FunctionId = 500, FunctionName = "Treasury Bills from RBI" },
            new Function { FunctionId = 501, FunctionName = "Treasury Bills" },
            new Function { FunctionId = 502, FunctionName = "Liability" },
            new Function { FunctionId = 503, FunctionName = "National Small Saving Scheme " },
            new Function { FunctionId = 504, FunctionName = "NSSF(Stmt No Three) Report" },
            new Function { FunctionId = 505, FunctionName = "Annex8-Sources & application of NSSF" },
            new Function { FunctionId = 506, FunctionName = "DCP Receipt Payment Source" },
            new Function { FunctionId = 507, FunctionName = "DCP Receipt and Payment Details" },
            new Function { FunctionId = 508, FunctionName = "DCP Details" },
            new Function { FunctionId = 509, FunctionName = "NSSF Annex VIII(SSRS)" },
            new Function { FunctionId = 510, FunctionName = "Other Liability" },
            new Function { FunctionId = 511, FunctionName = "External Debt" },
            new Function { FunctionId = 512, FunctionName = "Other liability/External " },
            new Function { FunctionId = 513, FunctionName = "Additional CRL Details" },
            new Function { FunctionId = 514, FunctionName = "Category" },
            new Function { FunctionId = 515, FunctionName = "Group" },
            new Function { FunctionId = 516, FunctionName = "Scheme" },
            new Function { FunctionId = 517, FunctionName = "SubScheme" },
            new Function { FunctionId = 518, FunctionName = "Intermediate Liability" },
            new Function { FunctionId = 519, FunctionName = "Intermediate liability" },
            new Function { FunctionId = 520, FunctionName = "Detailed Monthly Liability Statement" },
            new Function { FunctionId = 521, FunctionName = "DCP Excel File Import" },
            new Function { FunctionId = 522, FunctionName = "Summarized Liability Statement" },
            new Function { FunctionId = 523, FunctionName = "Historic Data on Liability" },
            new Function { FunctionId = 524, FunctionName = "Daily Cash Position" },
            new Function { FunctionId = 525, FunctionName = "Major Head" },
            new Function { FunctionId = 526, FunctionName = "Interest Rate Of WMA & OD" },
            new Function { FunctionId = 527, FunctionName = "Statement Allocation" },
            new Function { FunctionId = 528, FunctionName = "RE Meeting Allocation" },
            new Function { FunctionId = 529, FunctionName = "WMA/OD Interest" },
            new Function { FunctionId = 530, FunctionName = "Machine Readable Data" },
            new Function { FunctionId = 531, FunctionName = "GOVERNMENT BORROWINGS FROM RBI" },
            new Function { FunctionId = 532, FunctionName = "Import Actuals From CGA" },
            new Function { FunctionId = 533, FunctionName = "Daily Interest On Surplus Cash Invst" },
            new Function { FunctionId = 534, FunctionName = "Change Statement Type for Report" },
            new Function { FunctionId = 535, FunctionName = "Actdrx  with Null Data" },
            new Function { FunctionId = 536, FunctionName = "SBE Line Entry Delete Permission" },
            new Function { FunctionId = 537, FunctionName = "SBE Line Entry Delete Permission" },
            new Function { FunctionId = 538, FunctionName = "SBE Line Entry Delete Permission" },
            new Function { FunctionId = 539, FunctionName = "Adhoc Queries for Statement 18" },
            new Function { FunctionId = 540, FunctionName = "Check BE Difference  for Statement" },
            new Function { FunctionId = 541, FunctionName = "BE Difference For SBE" },
            new Function { FunctionId = 542, FunctionName = "SBE BE Difference " },
            new Function { FunctionId = 543, FunctionName = "File Sharing" },
            new Function { FunctionId = 544, FunctionName = "Major Head Mapping" },
            new Function { FunctionId = 545, FunctionName = "Tax Value" },
            new Function { FunctionId = 546, FunctionName = "Tax Value" },
            new Function { FunctionId = 547, FunctionName = "State Master" },
            new Function { FunctionId = 548, FunctionName = "State Value" },
            new Function { FunctionId = 549, FunctionName = "Edit Annex Data" },
            new Function { FunctionId = 550, FunctionName = "Edit Sanction Data" },
            new Function { FunctionId = 551, FunctionName = "Annex Report" },
            new Function { FunctionId = 552, FunctionName = "Sanction Report" },
            new Function { FunctionId = 553, FunctionName = "Demand  Scheme Ceiling" },
            new Function { FunctionId = 554, FunctionName = "Data To Approve" },
            new Function { FunctionId = 555, FunctionName = "Add Scheme Outlay" },
            new Function { FunctionId = 556, FunctionName = "Add Actuals" },
            new Function { FunctionId = 557, FunctionName = "Data For Reapproval" },
            new Function { FunctionId = 558, FunctionName = "Add Schemes" },
            new Function { FunctionId = 559, FunctionName = "Add Sub Schemes" },
            new Function { FunctionId = 560, FunctionName = "Add Umbrella Schemes" },
            new Function { FunctionId = 561, FunctionName = "Data Analysis" },
            new Function { FunctionId = 562, FunctionName = "Add Subscheme Outlay" },
            new Function { FunctionId = 563, FunctionName = "Demand Wise ECL Status " },
            new Function { FunctionId = 564, FunctionName = "Pending Demand" },
            new Function { FunctionId = 565, FunctionName = "Cumalative Sanction Devolution Report" },
            new Function { FunctionId = 566, FunctionName = "DCP Monthly Chart" },
            new Function { FunctionId = 567, FunctionName = "Edit Unit" },
            new Function { FunctionId = 568, FunctionName = "Budget at a Glance Values" },
            new Function { FunctionId = 569, FunctionName = "Receipt Statement" },
            new Function { FunctionId = 570, FunctionName = " Weighted  Average Graph" },
            new Function { FunctionId = 571, FunctionName = "Dated Securities" },
            new Function { FunctionId = 572, FunctionName = "Dated Security Auction Details" },
            new Function { FunctionId = 573, FunctionName = "Demand Scheme Ceiling" },
            new Function { FunctionId = 574, FunctionName = "SBE Report Without Data" },
            new Function { FunctionId = 575, FunctionName = "Demand Wise ECL Status Top Line" },
            new Function { FunctionId = 576, FunctionName = "SBE Freeze" },
            new Function { FunctionId = 577, FunctionName = "Adhoc Queries Statement 18/Transfer of Resources" },
            new Function { FunctionId = 578, FunctionName = "Edit Scheme Name" },
            new Function { FunctionId = 579, FunctionName = "Edit SubScheme Name" },
            new Function { FunctionId = 580, FunctionName = "Freeze/ Unfreeze Demand Statement Wise" },
            new Function { FunctionId = 581, FunctionName = "Statement In Excel" },
            new Function { FunctionId = 582, FunctionName = "Adhoc Queries Report" },
            new Function { FunctionId = 583, FunctionName = "SBE Report In Excel" },
            new Function { FunctionId = 584, FunctionName = "Statement IVA Details" },
            new Function { FunctionId = 585, FunctionName = "Add Calculated Cash for Public Account" },
            new Function { FunctionId = 586, FunctionName = "Statement In Excel" },
            new Function { FunctionId = 587, FunctionName = "User Allocation" },
            new Function { FunctionId = 588, FunctionName = "Import Account Code Directory to UBIS" },
            new Function { FunctionId = 589, FunctionName = "Status of DDG Demand" },
            new Function { FunctionId = 590, FunctionName = "Adhoc Queries for Statement 18" },
            new Function { FunctionId = 591, FunctionName = "Freeze/Unfreeze For All Demand" },
            new Function { FunctionId = 592, FunctionName = "Enable BE Edit Permission" },
            new Function { FunctionId = 593, FunctionName = "Investment In PSE" },
            new Function { FunctionId = 594, FunctionName = "RE and NBE mismatch for transferring data" },
            new Function { FunctionId = 595, FunctionName = "Directory Mismatch Before Pushing  to  PFMS" },
            new Function { FunctionId = 596, FunctionName = "Freeze/Unfreeze SBE" },
            new Function { FunctionId = 597, FunctionName = "Add Scheme" },
            new Function { FunctionId = 598, FunctionName = "Add SubScheme" },
            new Function { FunctionId = 599, FunctionName = "Add Group" },
            new Function { FunctionId = 600, FunctionName = "Data Initialisation" },
            new Function { FunctionId = 601, FunctionName = "Section Wise Demand Report" },
            new Function { FunctionId = 602, FunctionName = "Transfer Actual for All Demands" },
            new Function { FunctionId = 603, FunctionName = "Demand Contact Details" },
            new Function { FunctionId = 604, FunctionName = "Hindi for 4A" },
            new Function { FunctionId = 605, FunctionName = "Edit Depicted Scheme Name/Hindi for 4A" },
            new Function { FunctionId = 606, FunctionName = "Generate SBE from Other Source" },
            new Function { FunctionId = 607, FunctionName = "Print Sequence Number for 4A" },
            new Function { FunctionId = 608, FunctionName = "App And Role Wise Freeze Function" },
            new Function { FunctionId = 609, FunctionName = "Adhoc Queries for BAAG Details" },
            new Function { FunctionId = 610, FunctionName = "Sonata Template" },
            new Function { FunctionId = 611, FunctionName = "Vote on Account" },
            new Function { FunctionId = 612, FunctionName = "Demand Allocation" },
            new Function { FunctionId = 613, FunctionName = "VoA Allocation" },
            new Function { FunctionId = 614, FunctionName = "Edit NSSF Group" },
            new Function { FunctionId = 615, FunctionName = "Edit NSSF Scheme" },
            new Function { FunctionId = 616, FunctionName = "Edit  NSSF SubScheme" },
            new Function { FunctionId = 617, FunctionName = "Glance Category Mapping" },
            new Function { FunctionId = 618, FunctionName = "All Statement Reports" },
            new Function { FunctionId = 619, FunctionName = "App and User Wise Freeze Function" },
            new Function { FunctionId = 620, FunctionName = "AFS" },
            new Function { FunctionId = 621, FunctionName = "Receipts" },
            new Function { FunctionId = 622, FunctionName = "Receipts(SSRS)" },
            new Function { FunctionId = 623, FunctionName = "All Budget at a Glance Report" },
            new Function { FunctionId = 624, FunctionName = "Graphical Chart" },
            new Function { FunctionId = 625, FunctionName = "Generate DDG(Old Format)" },
            new Function { FunctionId = 626, FunctionName = "Mismatch Summary of DDG with SBE" },
            new Function { FunctionId = 627, FunctionName = "SBE Schemes not mapped" },
            new Function { FunctionId = 628, FunctionName = "DDG Head of Accounts not mapped" },
            new Function { FunctionId = 629, FunctionName = "HOA not In DDG" },
            new Function { FunctionId = 630, FunctionName = "HOA not In PFMS" },
            new Function { FunctionId = 631, FunctionName = "Generate DDG" },
            new Function { FunctionId = 632, FunctionName = "Status of DDG Demand" },
            new Function { FunctionId = 633, FunctionName = "Data Analysis" },
            new Function { FunctionId = 634, FunctionName = "Demand Wise ECL Status " },
            new Function { FunctionId = 635, FunctionName = "Pending Demand" },
            new Function { FunctionId = 636, FunctionName = "Demand Wise ECL Status Top Line" },
            new Function { FunctionId = 637, FunctionName = "RE Data and Report" },
            new Function { FunctionId = 638, FunctionName = "RE Consolidated" },
            new Function { FunctionId = 639, FunctionName = "RE Report For All Demand " },
            new Function { FunctionId = 640, FunctionName = "Asset Register" },
            new Function { FunctionId = 641, FunctionName = "Asset Register Analytics" },
            new Function { FunctionId = 642, FunctionName = "Arrears Of NTR" },
            new Function { FunctionId = 643, FunctionName = "Arrears Of NTR Analytics Report" },
            new Function { FunctionId = 644, FunctionName = "Statement Report" },
            new Function { FunctionId = 645, FunctionName = "Check BE Difference  for Statement" },
            new Function { FunctionId = 646, FunctionName = "Adhoc Queries for Statement 18" },
            new Function { FunctionId = 647, FunctionName = "All Statement Reports" },
            new Function { FunctionId = 648, FunctionName = "Generate Supplementary (Approved by SD)" },
            new Function { FunctionId = 649, FunctionName = "Generate Supplementary Report" },
            new Function { FunctionId = 650, FunctionName = "Supplementary Reports (Miscellaneous)" },
            new Function { FunctionId = 651, FunctionName = "Annexure I" },
            new Function { FunctionId = 652, FunctionName = "Log Report" },
            new Function { FunctionId = 653, FunctionName = "Generate Supplementary With Line Break" },
            new Function { FunctionId = 654, FunctionName = "Check Sheet" },
            new Function { FunctionId = 655, FunctionName = "Cash Outflow Log" },
            new Function { FunctionId = 656, FunctionName = "Generate Supplementary (SSRS)" },
            new Function { FunctionId = 657, FunctionName = "Report to Parliament Annexure" },
            new Function { FunctionId = 658, FunctionName = "Previous Supplementary DemandWise" },
            new Function { FunctionId = 659, FunctionName = "Vote on Account (Interim)" },
            new Function { FunctionId = 660, FunctionName = "Generate SBE" },
            new Function { FunctionId = 661, FunctionName = "Combined A Part Top Lines" },
            new Function { FunctionId = 662, FunctionName = "Receipt Report" },
            new Function { FunctionId = 663, FunctionName = "Recovery Report" },
            new Function { FunctionId = 664, FunctionName = "Demand Wise Scheme/SubScheme" },
            new Function { FunctionId = 665, FunctionName = "Category Wise Scheme/Subscheme" },
            new Function { FunctionId = 666, FunctionName = "DG Summary" },
            new Function { FunctionId = 667, FunctionName = "Generate DG" },
            new Function { FunctionId = 668, FunctionName = "Charged Report" },
            new Function { FunctionId = 669, FunctionName = "MajorHeadWise Scheme/SubScheme" },
            new Function { FunctionId = 670, FunctionName = "Generate SBE (SSRS)" },
            new Function { FunctionId = 671, FunctionName = "SBE Line Entry Delete Permission" },
            new Function { FunctionId = 672, FunctionName = "SBE BE Difference " },
            new Function { FunctionId = 673, FunctionName = "SBE Report Without Data" },
            new Function { FunctionId = 674, FunctionName = "Investment In PSE" },
            new Function { FunctionId = 675, FunctionName = "Generate SBE from Other Source" },
            new Function { FunctionId = 676, FunctionName = "RE and NBE sum mismatch for transferring data" },
            new Function { FunctionId = 677, FunctionName = "Update Consumed Status" },
            new Function { FunctionId = 678, FunctionName = "Allow Updation of Consumed Data" },
            new Function { FunctionId = 679, FunctionName = "Update Consumed Status" },
            new Function { FunctionId = 680, FunctionName = "Sum Mismatch of DDG with DG" },
            new Function { FunctionId = 681, FunctionName = "QEP Data" },
            new Function { FunctionId = 682, FunctionName = "ReAppropriation New" },
            new Function { FunctionId = 683, FunctionName = "Pending Reappropriations" },
            new Function { FunctionId = 684, FunctionName = "MEP/QEP Report" },
            new Function { FunctionId = 685, FunctionName = "Add Pensioners Data" },
            new Function { FunctionId = 686, FunctionName = "Add Employees Data" },
            new Function { FunctionId = 687, FunctionName = "Add Autonomous/Grantee Data" },
            new Function { FunctionId = 688, FunctionName = "Autonomous/Grantee Reports" },
            new Function { FunctionId = 689, FunctionName = "Autonomous/Grantee Bodies" },
            new Function { FunctionId = 690, FunctionName = "Add Autonomous/Grantee Name" },
            new Function { FunctionId = 691, FunctionName = "Date Time Stamp for SBE Report" },
            new Function { FunctionId = 692, FunctionName = "Pay and Allowances Expenditure" },
            new Function { FunctionId = 693, FunctionName = "Autonomous/Grantee Data for Approval" },
            new Function { FunctionId = 694, FunctionName = "Pensioners Data for Approval" },
            new Function { FunctionId = 695, FunctionName = "Employee Data for Approval" },
            new Function { FunctionId = 696, FunctionName = "SBE Data not mapped with Statement4A" },
            new Function { FunctionId = 697, FunctionName = "Mapping for Statement 12 and 13" },
            new Function { FunctionId = 698, FunctionName = "Vote on Account (Regular)" },
            new Function { FunctionId = 699, FunctionName = "Add Autonomous/Grantee Name" },
            new Function { FunctionId = 700, FunctionName = "Vote on Account (Regular)" },
            new Function { FunctionId = 701, FunctionName = "Railway Statements Report" },
            new Function { FunctionId = 702, FunctionName = "NSSF(Stmt No Three) Report" },
            new Function { FunctionId = 703, FunctionName = "NSSF Annex VIII(SSRS)" },
            new Function { FunctionId = 704, FunctionName = "Major Head Group Name" },
            new Function { FunctionId = 705, FunctionName = "Reappropriation Status" },
            new Function { FunctionId = 706, FunctionName = "ReAppropriation Details" },
            new Function { FunctionId = 707, FunctionName = "Edit Hindi SBE Data" },
            new Function { FunctionId = 708, FunctionName = "Export Reappropriation to PFMS" },
            new Function { FunctionId = 709, FunctionName = "Prepare Data  for Pushing to PFMS" },
            new Function { FunctionId = 710, FunctionName = "Pay and Allowances Data for Approval" },
            new Function { FunctionId = 711, FunctionName = "Autonomous/Grantee Bodies Status" },
            new Function { FunctionId = 712, FunctionName = "Autonomous/Grantee Bodies Status" },
            new Function { FunctionId = 713, FunctionName = "Reject Self Approved Reappropriation" },
            new Function { FunctionId = 714, FunctionName = "Actuals Change Permission" },
            new Function { FunctionId = 715, FunctionName = "Demand Scheme Ceiling Allocation" },
            new Function { FunctionId = 716, FunctionName = "Provision For Reapproval Autonomous" },
            new Function { FunctionId = 717, FunctionName = "Old Temporarily saved Reappropriation" },
            new Function { FunctionId = 718, FunctionName = "Demand Scheme Ceiling Relaxation" },
            new Function { FunctionId = 719, FunctionName = "ReAppropriation Miscellaneous Queries" },
            new Function { FunctionId = 720, FunctionName = "Demand Ceiling Validations Checklist" },
            new Function { FunctionId = 721, FunctionName = "Demand Scheme Ceilling Allocation" },
            new Function { FunctionId = 722, FunctionName = "QEP Unfreeze" },
            new Function { FunctionId = 723, FunctionName = "Relaxed Schemes Under ECL " },
            new Function { FunctionId = 724, FunctionName = "Sum Mismatch of DDG with DG" },
            new Function { FunctionId = 725, FunctionName = "Demand Ceiling Validations Checklist" },
            new Function { FunctionId = 726, FunctionName = "RE and NBE sum mismatch for transferring data" },
            new Function { FunctionId = 727, FunctionName = "Renumber PSE SrNo" },
            new Function { FunctionId = 728, FunctionName = "Statement Reports Directly Generated From DDG" },
            new Function { FunctionId = 729, FunctionName = "Change Previous Year BE" },
            new Function { FunctionId = 730, FunctionName = "RE and NBE sum mismatch for transferring data" },
            new Function { FunctionId = 731, FunctionName = "Demand Ceiling Validations Checklist" },
            new Function { FunctionId = 732, FunctionName = "Sum Mismatch of DDG with DG" },
            new Function { FunctionId = 733, FunctionName = "Statement Reports Directly Generated From DDG" },
            new Function { FunctionId = 734, FunctionName = "Add Supplementary Data HOA Wise" },
            new Function { FunctionId = 735, FunctionName = "Generate HOA Wise Report" },
            new Function { FunctionId = 736, FunctionName = "Add Supplementary Balance" },
            new Function { FunctionId = 737, FunctionName = "Delete Audit/Error Log Data" },
            new Function { FunctionId = 738, FunctionName = "Contingency Advance Proposal" },
            new Function { FunctionId = 739, FunctionName = "CFI Initialization" },
            new Function { FunctionId = 740, FunctionName = "CFI New Minor Head" },
            new Function { FunctionId = 741, FunctionName = "CFI Data for Approval" },
            new Function { FunctionId = 742, FunctionName = "CFI Data for Approval by SD" },
            new Function { FunctionId = 743, FunctionName = "Approved CFI Sanctions" },
            new Function { FunctionId = 744, FunctionName = "CFI Resumption" },
            new Function { FunctionId = 745, FunctionName = "Issued CFI Proposals" },
            new Function { FunctionId = 746, FunctionName = "Add Supplementary Data" },
            new Function { FunctionId = 747, FunctionName = "Report to Parliament Annexure" },
            new Function { FunctionId = 748, FunctionName = "Generate Supplementary Report" },
            new Function { FunctionId = 749, FunctionName = "Report to Parliament Annexure" },
            new Function { FunctionId = 750, FunctionName = "Recoup Amount Mismatch" },
            new Function { FunctionId = 751, FunctionName = "Proposal Status" },
            new Function { FunctionId = 752, FunctionName = "Supplementary Introduction" },
            new Function { FunctionId = 753, FunctionName = "Supplementary Reports (Miscellaneous)" },
            new Function { FunctionId = 754, FunctionName = "View Supplementary" },
            new Function { FunctionId = 755, FunctionName = "CFI Data for Surrender Amount" },
            new Function { FunctionId = 756, FunctionName = "Data Entry DDG (New)" },
            new Function { FunctionId = 757, FunctionName = "Mapping percentage for Stmt 12 and 13 from DDG" },
            new Function { FunctionId = 758, FunctionName = "Reopen after Approval" },
            new Function { FunctionId = 759, FunctionName = "Delete Previous Year Log Data" },
            new Function { FunctionId = 760, FunctionName = "Freeze UnFreeze Annexure" },
            new Function { FunctionId = 761, FunctionName = "Generate Supplementary With Line Break" },
            new Function { FunctionId = 762, FunctionName = "Update Hindi Intro" },
            new Function { FunctionId = 763, FunctionName = "Update Hindi for Report to Parliament" },
            new Function { FunctionId = 764, FunctionName = "Export Supplementary Data to PFMS" },
            new Function { FunctionId = 765, FunctionName = "Category Wise Schemes" },
            new Function { FunctionId = 766, FunctionName = "Token Reappr Relaxation" },
            new Function { FunctionId = 767, FunctionName = "Change Actuals and Previous BE for Stmt 12 and 13" },
            new Function { FunctionId = 768, FunctionName = "Change Actuals and Previous BE for Stmt 10A10B " },
            new Function { FunctionId = 769, FunctionName = "Statement 2A and 2B in Excel" },
            new Function { FunctionId = 770, FunctionName = "Activate Deactivate Users" },
            new Function { FunctionId = 771, FunctionName = "Object Head" },
            new Function { FunctionId = 772, FunctionName = "Receipt / Recovery for Technical Supp" },
            new Function { FunctionId = 1772, FunctionName = "Generate Zip for All DG Demand" },
            new Function { FunctionId = 1773, FunctionName = "Generate Zip for All SBE Demand" },
            new Function { FunctionId = 1774, FunctionName = "Generate Zip for All Statement" },
            new Function { FunctionId = 1775, FunctionName = "Report to Parliament Time Period " },
            new Function { FunctionId = 1776, FunctionName = "Status of Report to Parliament Data" },
            new Function { FunctionId = 1777, FunctionName = "SBE Report in Excel" },
            new Function { FunctionId = 1778, FunctionName = "Supplementary Details HOA Wise" },
            new Function { FunctionId = 1779, FunctionName = "Token Supplementary Report" },
            new Function { FunctionId = 1780, FunctionName = "Cancellation of ROs From PFMS" }
        );
    }
}
