namespace UBIS.Services.MenuGenerator.Infrastructure.Persistence.DevSeed.Configurations;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UBIS.Services.MenuGenerator.Domain.Entities;

/// <summary>
/// Dev/test-seed-only configuration for RoleModuleMapping - creates and seeds "M_MapRoleModule"
/// (renamed 2026-08-04 from M_RoleModuleMapping) in the standalone dev/test database (separate
/// from the production, read-only legacy tables).
/// </summary>
public class RoleModuleMappingSeedConfiguration : IEntityTypeConfiguration<RoleModuleMapping>
{
    public void Configure(EntityTypeBuilder<RoleModuleMapping> builder)
    {
        builder.ToTable("M_MapRoleModule", "dbo");
        builder.HasKey(x => x.RModuleMappingId);
        builder.Property(x => x.RModuleMappingId).HasColumnName("RModuleMappingId").ValueGeneratedNever();
        builder.Property(x => x.AppId).HasColumnName("AppId");
        builder.Property(x => x.RoleId).HasColumnName("RoleId");
        builder.Property(x => x.ModuleId).HasColumnName("ModuleId");
        builder.Property(x => x.Active).HasColumnName("Active");
        builder.Property(x => x.RmSequenceNo).HasColumnName("RM_SequenceNo");

        builder.HasData(
            new RoleModuleMapping { RModuleMappingId = 2, AppId = 1, RoleId = 13, ModuleId = 1, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 8, AppId = 1, RoleId = 13, ModuleId = 8, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 27, AppId = 1, RoleId = 13, ModuleId = 22, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 36, AppId = 2, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 40, AppId = 1, RoleId = 13, ModuleId = 31, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 41, AppId = 2, RoleId = 23, ModuleId = 32, Active = "Y", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 43, AppId = 2, RoleId = 23, ModuleId = 34, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 49, AppId = 2, RoleId = 23, ModuleId = 29, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 51, AppId = 2, RoleId = 23, ModuleId = 38, Active = "N", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 63, AppId = 1, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 64, AppId = 1, RoleId = 25, ModuleId = 29, Active = "N", RmSequenceNo = 8 },
            new RoleModuleMapping { RModuleMappingId = 65, AppId = 1, RoleId = 25, ModuleId = 32, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 69, AppId = 1, RoleId = 18, ModuleId = 42, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 71, AppId = 1, RoleId = 23, ModuleId = 42, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 73, AppId = 1, RoleId = 25, ModuleId = 41, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 76, AppId = 1, RoleId = 25, ModuleId = 43, Active = "N", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 78, AppId = 1, RoleId = 25, ModuleId = 45, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 79, AppId = 1, RoleId = 25, ModuleId = 38, Active = "Y", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 80, AppId = 1, RoleId = 25, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 83, AppId = 1, RoleId = 27, ModuleId = 46, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 85, AppId = 6, RoleId = 25, ModuleId = 47, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 88, AppId = 1, RoleId = 27, ModuleId = 48, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 91, AppId = 1, RoleId = 23, ModuleId = 50, Active = "N", RmSequenceNo = 9 },
            new RoleModuleMapping { RModuleMappingId = 92, AppId = 1, RoleId = 29, ModuleId = 49, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 93, AppId = 1, RoleId = 29, ModuleId = 43, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 94, AppId = 2, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 95, AppId = 2, RoleId = 18, ModuleId = 34, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 96, AppId = 2, RoleId = 18, ModuleId = 29, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 97, AppId = 2, RoleId = 18, ModuleId = 30, Active = "N", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 98, AppId = 2, RoleId = 18, ModuleId = 32, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 99, AppId = 2, RoleId = 19, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 100, AppId = 2, RoleId = 19, ModuleId = 34, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 101, AppId = 2, RoleId = 19, ModuleId = 29, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 102, AppId = 2, RoleId = 19, ModuleId = 30, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 103, AppId = 2, RoleId = 19, ModuleId = 32, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 104, AppId = 2, RoleId = 23, ModuleId = 30, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 105, AppId = 2, RoleId = 22, ModuleId = 30, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 106, AppId = 2, RoleId = 24, ModuleId = 30, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 107, AppId = 2, RoleId = 30, ModuleId = 30, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 108, AppId = 2, RoleId = 19, ModuleId = 51, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 109, AppId = 1, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 110, AppId = 6, RoleId = 18, ModuleId = 47, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 111, AppId = 1, RoleId = 18, ModuleId = 42, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 112, AppId = 1, RoleId = 18, ModuleId = 39, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 113, AppId = 1, RoleId = 18, ModuleId = 45, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 114, AppId = 1, RoleId = 18, ModuleId = 29, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 115, AppId = 1, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 116, AppId = 1, RoleId = 23, ModuleId = 41, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 118, AppId = 1, RoleId = 23, ModuleId = 45, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 119, AppId = 6, RoleId = 23, ModuleId = 47, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 120, AppId = 1, RoleId = 23, ModuleId = 38, Active = "Y", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 121, AppId = 1, RoleId = 23, ModuleId = 43, Active = "N", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 122, AppId = 1, RoleId = 23, ModuleId = 49, Active = "N", RmSequenceNo = 8 },
            new RoleModuleMapping { RModuleMappingId = 124, AppId = 1, RoleId = 23, ModuleId = 52, Active = "N", RmSequenceNo = 10 },
            new RoleModuleMapping { RModuleMappingId = 125, AppId = 2, RoleId = 32, ModuleId = 53, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 126, AppId = 1, RoleId = 32, ModuleId = 53, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 127, AppId = 2, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 128, AppId = 2, RoleId = 25, ModuleId = 34, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 129, AppId = 2, RoleId = 25, ModuleId = 29, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 130, AppId = 2, RoleId = 25, ModuleId = 30, Active = "N", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 131, AppId = 2, RoleId = 25, ModuleId = 32, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 132, AppId = 2, RoleId = 25, ModuleId = 41, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 133, AppId = 2, RoleId = 30, ModuleId = 51, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 134, AppId = 3, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 135, AppId = 3, RoleId = 25, ModuleId = 52, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 136, AppId = 3, RoleId = 25, ModuleId = 45, Active = "N", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 137, AppId = 3, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 138, AppId = 3, RoleId = 18, ModuleId = 52, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 139, AppId = 3, RoleId = 18, ModuleId = 45, Active = "N", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 140, AppId = 3, RoleId = 25, ModuleId = 54, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 141, AppId = 3, RoleId = 18, ModuleId = 54, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 142, AppId = 3, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 143, AppId = 3, RoleId = 23, ModuleId = 52, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 144, AppId = 3, RoleId = 23, ModuleId = 54, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 145, AppId = 3, RoleId = 27, ModuleId = 55, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 146, AppId = 3, RoleId = 27, ModuleId = 54, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 147, AppId = 5, RoleId = 23, ModuleId = 92, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 148, AppId = 5, RoleId = 23, ModuleId = 56, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 149, AppId = 5, RoleId = 23, ModuleId = 57, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 150, AppId = 5, RoleId = 25, ModuleId = 92, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 151, AppId = 5, RoleId = 25, ModuleId = 56, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 152, AppId = 5, RoleId = 25, ModuleId = 57, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 153, AppId = 5, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 154, AppId = 5, RoleId = 25, ModuleId = 8, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 155, AppId = 5, RoleId = 18, ModuleId = 8, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 156, AppId = 5, RoleId = 18, ModuleId = 41, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 157, AppId = 5, RoleId = 18, ModuleId = 56, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 158, AppId = 5, RoleId = 18, ModuleId = 57, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 166, AppId = 4, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 167, AppId = 4, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 168, AppId = 4, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 169, AppId = 1, RoleId = 13, ModuleId = 58, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 170, AppId = 1, RoleId = 13, ModuleId = 59, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 171, AppId = 1, RoleId = 23, ModuleId = 60, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 172, AppId = 1, RoleId = 25, ModuleId = 60, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 173, AppId = 1, RoleId = 18, ModuleId = 60, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 174, AppId = 1, RoleId = 13, ModuleId = 41, Active = "N", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 175, AppId = 3, RoleId = 23, ModuleId = 61, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 176, AppId = 1, RoleId = 27, ModuleId = 62, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 177, AppId = 2, RoleId = 23, ModuleId = 63, Active = "Y", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 179, AppId = 3, RoleId = 25, ModuleId = 61, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 180, AppId = 1, RoleId = 27, ModuleId = 65, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 181, AppId = 1, RoleId = 29, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 182, AppId = 1, RoleId = 36, ModuleId = 41, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 183, AppId = 1, RoleId = 36, ModuleId = 42, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 184, AppId = 1, RoleId = 36, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 185, AppId = 1, RoleId = 39, ModuleId = 46, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 186, AppId = 1, RoleId = 39, ModuleId = 48, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 187, AppId = 1, RoleId = 39, ModuleId = 62, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 188, AppId = 1, RoleId = 39, ModuleId = 65, Active = "N", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 189, AppId = 1, RoleId = 29, ModuleId = 57, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 190, AppId = 1, RoleId = 23, ModuleId = 66, Active = "N", RmSequenceNo = 9 },
            new RoleModuleMapping { RModuleMappingId = 191, AppId = 5, RoleId = 18, ModuleId = 92, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 192, AppId = 1, RoleId = 19, ModuleId = 66, Active = "N", RmSequenceNo = 15 },
            new RoleModuleMapping { RModuleMappingId = 193, AppId = 1, RoleId = 13, ModuleId = 66, Active = "Y", RmSequenceNo = 9 },
            new RoleModuleMapping { RModuleMappingId = 194, AppId = 1, RoleId = 13, ModuleId = 51, Active = "Y", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 195, AppId = 1, RoleId = 13, ModuleId = 67, Active = "N", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 196, AppId = 1, RoleId = 13, ModuleId = 68, Active = "N", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 197, AppId = 2, RoleId = 19, ModuleId = 63, Active = "Y", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 198, AppId = 5, RoleId = 42, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 199, AppId = 5, RoleId = 42, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 200, AppId = 5, RoleId = 43, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 201, AppId = 1, RoleId = 43, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 202, AppId = 1, RoleId = 43, ModuleId = 69, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 203, AppId = 1, RoleId = 42, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 204, AppId = 1, RoleId = 42, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 205, AppId = 1, RoleId = 42, ModuleId = 66, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 206, AppId = 2, RoleId = 25, ModuleId = 63, Active = "Y", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 207, AppId = 1, RoleId = 44, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 208, AppId = 1, RoleId = 44, ModuleId = 72, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 209, AppId = 1, RoleId = 44, ModuleId = 71, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 210, AppId = 1, RoleId = 46, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 211, AppId = 1, RoleId = 46, ModuleId = 42, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 212, AppId = 1, RoleId = 46, ModuleId = 45, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 213, AppId = 1, RoleId = 25, ModuleId = 71, Active = "N", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 214, AppId = 1, RoleId = 25, ModuleId = 70, Active = "N", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 215, AppId = 1, RoleId = 18, ModuleId = 70, Active = "Y", RmSequenceNo = 6 },
            new RoleModuleMapping { RModuleMappingId = 216, AppId = 1, RoleId = 45, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 217, AppId = 1, RoleId = 45, ModuleId = 70, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 218, AppId = 1, RoleId = 45, ModuleId = 57, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 219, AppId = 1, RoleId = 18, ModuleId = 74, Active = "N", RmSequenceNo = 7 },
            new RoleModuleMapping { RModuleMappingId = 220, AppId = 3, RoleId = 22, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 221, AppId = 1, RoleId = 47, ModuleId = 75, Active = "Y", RmSequenceNo = 10 },
            new RoleModuleMapping { RModuleMappingId = 222, AppId = 1, RoleId = 47, ModuleId = 76, Active = "Y", RmSequenceNo = 10 },
            new RoleModuleMapping { RModuleMappingId = 223, AppId = 1, RoleId = 13, ModuleId = 77, Active = "Y", RmSequenceNo = 10 },
            new RoleModuleMapping { RModuleMappingId = 224, AppId = 1, RoleId = 32, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 225, AppId = 1, RoleId = 32, ModuleId = 47, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 226, AppId = 6, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 227, AppId = 6, RoleId = 25, ModuleId = 47, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 228, AppId = 1, RoleId = 48, ModuleId = 78, Active = "Y", RmSequenceNo = 11 },
            new RoleModuleMapping { RModuleMappingId = 229, AppId = 1, RoleId = 48, ModuleId = 79, Active = "Y", RmSequenceNo = 11 },
            new RoleModuleMapping { RModuleMappingId = 230, AppId = 7, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 231, AppId = 7, RoleId = 23, ModuleId = 60, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 232, AppId = 7, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 233, AppId = 7, RoleId = 25, ModuleId = 60, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 234, AppId = 7, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 235, AppId = 7, RoleId = 18, ModuleId = 60, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 236, AppId = 7, RoleId = 23, ModuleId = 38, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 237, AppId = 7, RoleId = 25, ModuleId = 38, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 238, AppId = 8, RoleId = 49, ModuleId = 80, Active = "Y", RmSequenceNo = 12 },
            new RoleModuleMapping { RModuleMappingId = 239, AppId = 8, RoleId = 49, ModuleId = 81, Active = "Y", RmSequenceNo = 12 },
            new RoleModuleMapping { RModuleMappingId = 240, AppId = 8, RoleId = 49, ModuleId = 82, Active = "Y", RmSequenceNo = 12 },
            new RoleModuleMapping { RModuleMappingId = 241, AppId = 8, RoleId = 49, ModuleId = 45, Active = "Y", RmSequenceNo = 12 },
            new RoleModuleMapping { RModuleMappingId = 242, AppId = 1, RoleId = 48, ModuleId = 47, Active = "Y", RmSequenceNo = 12 },
            new RoleModuleMapping { RModuleMappingId = 243, AppId = 8, RoleId = 18, ModuleId = 81, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 244, AppId = 8, RoleId = 25, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 245, AppId = 8, RoleId = 25, ModuleId = 81, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 246, AppId = 8, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 247, AppId = 8, RoleId = 49, ModuleId = 38, Active = "Y", RmSequenceNo = 13 },
            new RoleModuleMapping { RModuleMappingId = 248, AppId = 8, RoleId = 49, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 249, AppId = 8, RoleId = 18, ModuleId = 82, Active = "N", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 250, AppId = 8, RoleId = 18, ModuleId = 45, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 251, AppId = 1, RoleId = 44, ModuleId = 84, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 252, AppId = 1, RoleId = 44, ModuleId = 85, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 253, AppId = 6, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 254, AppId = 6, RoleId = 18, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 255, AppId = 6, RoleId = 23, ModuleId = 38, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 256, AppId = 6, RoleId = 18, ModuleId = 86, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 257, AppId = 6, RoleId = 23, ModuleId = 86, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 258, AppId = 9, RoleId = 23, ModuleId = 41, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 259, AppId = 9, RoleId = 23, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 260, AppId = 9, RoleId = 50, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 261, AppId = 9, RoleId = 50, ModuleId = 41, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 262, AppId = 9, RoleId = 50, ModuleId = 42, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 263, AppId = 9, RoleId = 50, ModuleId = 57, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 264, AppId = 10, RoleId = 51, ModuleId = 87, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 265, AppId = 10, RoleId = 51, ModuleId = 89, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 266, AppId = 10, RoleId = 51, ModuleId = 88, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 267, AppId = 9, RoleId = 52, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 268, AppId = 9, RoleId = 52, ModuleId = 42, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 269, AppId = 9, RoleId = 53, ModuleId = 8, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 270, AppId = 9, RoleId = 53, ModuleId = 90, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 271, AppId = 9, RoleId = 50, ModuleId = 91, Active = "N", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 272, AppId = 6, RoleId = 25, ModuleId = 38, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 273, AppId = 6, RoleId = 25, ModuleId = 86, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 274, AppId = 6, RoleId = 25, ModuleId = 83, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 275, AppId = 6, RoleId = 23, ModuleId = 83, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 276, AppId = 6, RoleId = 18, ModuleId = 83, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 277, AppId = 1, RoleId = 56, ModuleId = 93, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 278, AppId = 11, RoleId = 18, ModuleId = 95, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 279, AppId = 11, RoleId = 54, ModuleId = 97, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 280, AppId = 11, RoleId = 54, ModuleId = 96, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 281, AppId = 11, RoleId = 54, ModuleId = 94, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 282, AppId = 11, RoleId = 22, ModuleId = 97, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 283, AppId = 11, RoleId = 23, ModuleId = 97, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 284, AppId = 11, RoleId = 25, ModuleId = 97, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 285, AppId = 11, RoleId = 23, ModuleId = 95, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 286, AppId = 11, RoleId = 23, ModuleId = 95, Active = "N", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 287, AppId = 11, RoleId = 23, ModuleId = 96, Active = "N", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 288, AppId = 11, RoleId = 23, ModuleId = 94, Active = "N", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 289, AppId = 11, RoleId = 55, ModuleId = 95, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 290, AppId = 11, RoleId = 55, ModuleId = 96, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 291, AppId = 11, RoleId = 55, ModuleId = 94, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 292, AppId = 11, RoleId = 55, ModuleId = 97, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 293, AppId = 9, RoleId = 50, ModuleId = 98, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 294, AppId = 1, RoleId = 23, ModuleId = 84, Active = "Y", RmSequenceNo = 10 },
            new RoleModuleMapping { RModuleMappingId = 295, AppId = 5, RoleId = 23, ModuleId = 99, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 296, AppId = 5, RoleId = 25, ModuleId = 99, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 297, AppId = 1, RoleId = 27, ModuleId = 100, Active = "Y", RmSequenceNo = 5 },
            new RoleModuleMapping { RModuleMappingId = 298, AppId = 1, RoleId = 23, ModuleId = 101, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 299, AppId = 1, RoleId = 23, ModuleId = 102, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 300, AppId = 1, RoleId = 23, ModuleId = 103, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 301, AppId = 1, RoleId = 23, ModuleId = 104, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 302, AppId = 1, RoleId = 23, ModuleId = 105, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 303, AppId = 1, RoleId = 23, ModuleId = 106, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 304, AppId = 1, RoleId = 23, ModuleId = 107, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 305, AppId = 1, RoleId = 23, ModuleId = 108, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 306, AppId = 1, RoleId = 23, ModuleId = 109, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 307, AppId = 1, RoleId = 23, ModuleId = 110, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 308, AppId = 1, RoleId = 56, ModuleId = 45, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 309, AppId = 8, RoleId = 49, ModuleId = 87, Active = "Y", RmSequenceNo = 14 },
            new RoleModuleMapping { RModuleMappingId = 310, AppId = 8, RoleId = 49, ModuleId = 89, Active = "Y", RmSequenceNo = 15 },
            new RoleModuleMapping { RModuleMappingId = 311, AppId = 8, RoleId = 49, ModuleId = 88, Active = "Y", RmSequenceNo = 16 },
            new RoleModuleMapping { RModuleMappingId = 312, AppId = 12, RoleId = 23, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 313, AppId = 12, RoleId = 18, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 314, AppId = 12, RoleId = 25, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 315, AppId = 12, RoleId = 23, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 316, AppId = 12, RoleId = 18, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 317, AppId = 12, RoleId = 25, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 318, AppId = 13, RoleId = 55, ModuleId = 97, Active = "Y", RmSequenceNo = 4 },
            new RoleModuleMapping { RModuleMappingId = 319, AppId = 13, RoleId = 55, ModuleId = 96, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 320, AppId = 13, RoleId = 55, ModuleId = 95, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 321, AppId = 13, RoleId = 25, ModuleId = 97, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 322, AppId = 13, RoleId = 23, ModuleId = 97, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 323, AppId = 13, RoleId = 22, ModuleId = 97, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 324, AppId = 13, RoleId = 54, ModuleId = 96, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 325, AppId = 13, RoleId = 54, ModuleId = 97, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 326, AppId = 13, RoleId = 18, ModuleId = 95, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 327, AppId = 13, RoleId = 54, ModuleId = 94, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 328, AppId = 11, RoleId = 18, ModuleId = 97, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 329, AppId = 14, RoleId = 18, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 330, AppId = 14, RoleId = 18, ModuleId = 57, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 331, AppId = 14, RoleId = 25, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 332, AppId = 14, RoleId = 25, ModuleId = 111, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 333, AppId = 14, RoleId = 25, ModuleId = 57, Active = "Y", RmSequenceNo = 3 },
            new RoleModuleMapping { RModuleMappingId = 334, AppId = 14, RoleId = 23, ModuleId = 42, Active = "Y", RmSequenceNo = 1 },
            new RoleModuleMapping { RModuleMappingId = 335, AppId = 14, RoleId = 23, ModuleId = 111, Active = "Y", RmSequenceNo = 2 },
            new RoleModuleMapping { RModuleMappingId = 336, AppId = 14, RoleId = 23, ModuleId = 57, Active = "Y", RmSequenceNo = 3 }
        );
    }
}
