// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.ContingencyAdvance.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("ContingencyAdvance")]
[Authorize]
public class CFIApproveController : Controller
{
    // App: Contingency Advance | Module: CFI Approve
    public IActionResult CFIDataforApproval()
    {
        ViewData["Title"] = "CFI Data for Approval";
        ViewData["Breadcrumb"] = "Contingency Advance / CFI Approve / CFI Data for Approval";
        return View();
    }

    // App: Contingency Advance | Module: CFI Approve
    public IActionResult CFIDataforApprovalbySD()
    {
        ViewData["Title"] = "CFI Data for Approval by SD";
        ViewData["Breadcrumb"] = "Contingency Advance / CFI Approve / CFI Data for Approval by SD";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
