// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DDG.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DDG")]
[Authorize]
public class DDGAllocationController : Controller
{
    // App: DDG | Module: DDG Allocation
    public IActionResult UserAllocation()
    {
        ViewData["Title"] = "User Allocation";
        ViewData["Breadcrumb"] = "DDG / DDG Allocation / User Allocation";
        return View();
    }

    // App: DDG | Module: DDG Allocation
    public IActionResult FreezeUnfreezeForAllDemand()
    {
        ViewData["Title"] = "Freeze/Unfreeze For All Demand";
        ViewData["Breadcrumb"] = "DDG / DDG Allocation / Freeze/Unfreeze For All Demand";
        return View();
    }

    // App: DDG | Module: DDG Allocation
    public IActionResult AllowUpdationofConsumedData()
    {
        ViewData["Title"] = "Allow Updation of Consumed Data";
        ViewData["Breadcrumb"] = "DDG / DDG Allocation / Allow Updation of Consumed Data";
        return View();
    }

    // App: DDG | Module: DDG Allocation
    public IActionResult ActualsChangePermission()
    {
        ViewData["Title"] = "Actuals Change Permission";
        ViewData["Breadcrumb"] = "DDG / DDG Allocation / Actuals Change Permission";
        return View();
    }

    // App: DDG | Module: DDG Allocation
    public IActionResult QEPUnfreeze()
    {
        ViewData["Title"] = "QEP Unfreeze";
        ViewData["Breadcrumb"] = "DDG / DDG Allocation / QEP Unfreeze";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
