// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DDG.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DDG")]
[Authorize]
public class DDGController : Controller
{
    // App: DDG | Module: DDG
    public IActionResult DataEntryDDGNew()
    {
        ViewData["Title"] = "Data Entry DDG (New)";
        ViewData["Breadcrumb"] = "DDG / DDG / Data Entry DDG (New)";
        return View();
    }

    // App: DDG | Module: DDG
    public IActionResult EditHindiHOA()
    {
        ViewData["Title"] = "Edit Hindi HOA";
        ViewData["Breadcrumb"] = "DDG / DDG / Edit Hindi HOA";
        return View();
    }

    // App: DDG | Module: DDG
    public IActionResult TransferDDGDatatoSBE()
    {
        ViewData["Title"] = "Transfer DDG Data to SBE";
        ViewData["Breadcrumb"] = "DDG / DDG / Transfer DDG Data to SBE";
        return View();
    }

    // App: DDG | Module: DDG
    public IActionResult FreezeDDG()
    {
        ViewData["Title"] = "Freeze DDG";
        ViewData["Breadcrumb"] = "DDG / DDG / Freeze DDG";
        return View();
    }

    // App: DDG | Module: DDG
    public IActionResult QEPData()
    {
        ViewData["Title"] = "QEP Data";
        ViewData["Breadcrumb"] = "DDG / DDG / QEP Data";
        return View();
    }

    // App: DDG | Module: DDG
    public IActionResult TransferActualforAllDemands()
    {
        ViewData["Title"] = "Transfer Actual for All Demands";
        ViewData["Breadcrumb"] = "DDG / DDG / Transfer Actual for All Demands";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
