// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DDG.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DDG")]
[Authorize]
public class DDGMastersController : Controller
{
    // App: DDG | Module: DDG  Masters
    public IActionResult AddHOAinACTDRX()
    {
        ViewData["Title"] = "Add HOA in ACTDRX";
        ViewData["Breadcrumb"] = "DDG / DDG  Masters / Add HOA in ACTDRX";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
