// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.DDG.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("DDG")]
[Authorize]
public class ReportsController : Controller
{
    // App: DDG | Module: Reports
    public IActionResult ReappropriationStatus()
    {
        ViewData["Title"] = "Reappropriation Status";
        ViewData["Breadcrumb"] = "DDG / Reports / Reappropriation Status";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult GenerateDDG()
    {
        ViewData["Title"] = "Generate DDG";
        ViewData["Breadcrumb"] = "DDG / Reports / Generate DDG";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult ApprovedCFISanctions()
    {
        ViewData["Title"] = "Approved CFI Sanctions";
        ViewData["Breadcrumb"] = "DDG / Reports / Approved CFI Sanctions";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult MEPQEPReport()
    {
        ViewData["Title"] = "MEP/QEP Report";
        ViewData["Breadcrumb"] = "DDG / Reports / MEP/QEP Report";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult ReAppropriationDetails()
    {
        ViewData["Title"] = "ReAppropriation Details";
        ViewData["Breadcrumb"] = "DDG / Reports / ReAppropriation Details";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult MismatchSummaryofDDGwithSBE()
    {
        ViewData["Title"] = "Mismatch Summary of DDG with SBE";
        ViewData["Breadcrumb"] = "DDG / Reports / Mismatch Summary of DDG with SBE";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult ReAppropriationMiscellaneousQueries()
    {
        ViewData["Title"] = "ReAppropriation Miscellaneous Queries";
        ViewData["Breadcrumb"] = "DDG / Reports / ReAppropriation Miscellaneous Queries";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult SBESchemesnotmapped()
    {
        ViewData["Title"] = "SBE Schemes not mapped";
        ViewData["Breadcrumb"] = "DDG / Reports / SBE Schemes not mapped";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult DDGHeadofAccountsnotmapped()
    {
        ViewData["Title"] = "DDG Head of Accounts not mapped";
        ViewData["Breadcrumb"] = "DDG / Reports / DDG Head of Accounts not mapped";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult HOAnotInDDG()
    {
        ViewData["Title"] = "HOA not In DDG";
        ViewData["Breadcrumb"] = "DDG / Reports / HOA not In DDG";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult HOAnotInPFMS()
    {
        ViewData["Title"] = "HOA not In PFMS";
        ViewData["Breadcrumb"] = "DDG / Reports / HOA not In PFMS";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult StatusofDDGDemand()
    {
        ViewData["Title"] = "Status of DDG Demand";
        ViewData["Breadcrumb"] = "DDG / Reports / Status of DDG Demand";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult SumMismatchofDDGwithDG()
    {
        ViewData["Title"] = "Sum Mismatch of DDG with DG";
        ViewData["Breadcrumb"] = "DDG / Reports / Sum Mismatch of DDG with DG";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult REandNBEsummismatchfortransferringdata()
    {
        ViewData["Title"] = "RE and NBE sum mismatch for transferring data";
        ViewData["Breadcrumb"] = "DDG / Reports / RE and NBE sum mismatch for transferring data";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult DemandCeilingValidationsChecklist()
    {
        ViewData["Title"] = "Demand Ceiling Validations Checklist";
        ViewData["Breadcrumb"] = "DDG / Reports / Demand Ceiling Validations Checklist";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult CFIResumption()
    {
        ViewData["Title"] = "CFI Resumption";
        ViewData["Breadcrumb"] = "DDG / Reports / CFI Resumption";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult IssuedCFIProposals()
    {
        ViewData["Title"] = "Issued CFI Proposals";
        ViewData["Breadcrumb"] = "DDG / Reports / Issued CFI Proposals";
        return View();
    }

    // App: DDG | Module: Reports
    public IActionResult TokenSupplementaryReport()
    {
        ViewData["Title"] = "Token Supplementary Report";
        ViewData["Breadcrumb"] = "DDG / Reports / Token Supplementary Report";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
