// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.SupplementaryBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("SupplementaryBudget")]
[Authorize]
public class SuppReportsController : Controller
{
    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult GenerateSupplementaryReport()
    {
        ViewData["Title"] = "Generate Supplementary Report";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Generate Supplementary Report";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult ReporttoParliamentAnnexure()
    {
        ViewData["Title"] = "Report to Parliament Annexure";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Report to Parliament Annexure";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult RecoupAmountMismatch()
    {
        ViewData["Title"] = "Recoup Amount Mismatch";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Recoup Amount Mismatch";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult ProposalStatus()
    {
        ViewData["Title"] = "Proposal Status";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Proposal Status";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult GenerateSupplementaryApprovedbySD()
    {
        ViewData["Title"] = "Generate Supplementary (Approved by SD)";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Generate Supplementary (Approved by SD)";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult GenerateSupplementaryWithLineBreak()
    {
        ViewData["Title"] = "Generate Supplementary With Line Break";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Generate Supplementary With Line Break";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult CheckSheet()
    {
        ViewData["Title"] = "Check Sheet";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Check Sheet";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult SupplementaryReportsMiscellaneous()
    {
        ViewData["Title"] = "Supplementary Reports (Miscellaneous)";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Supplementary Reports (Miscellaneous)";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult StatusofReporttoParliamentData()
    {
        ViewData["Title"] = "Status of Report to Parliament Data";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Status of Report to Parliament Data";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult SupplementaryDetailsHOAWise()
    {
        ViewData["Title"] = "Supplementary Details HOA Wise";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Supplementary Details HOA Wise";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Reports
    public IActionResult PreviousSupplementaryDemandWise()
    {
        ViewData["Title"] = "Previous Supplementary DemandWise";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Reports / Previous Supplementary DemandWise";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
