// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.SupplementaryBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("SupplementaryBudget")]
[Authorize]
public class SuppAllocationController : Controller
{
    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult SuppDemandAllocation()
    {
        ViewData["Title"] = "Supp Demand Allocation";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Supp Demand Allocation";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult AddSupplementaryNumber()
    {
        ViewData["Title"] = "Add Supplementary Number";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Add Supplementary Number";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult DeactiveSupplementaryNumber()
    {
        ViewData["Title"] = "Deactive Supplementary Number";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Deactive Supplementary Number";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult MajorHeadMapping()
    {
        ViewData["Title"] = "Major Head Mapping";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Major Head Mapping";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult ReopenafterApproval()
    {
        ViewData["Title"] = "Reopen after Approval";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Reopen after Approval";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult FreezeUnFreezeAnnexure()
    {
        ViewData["Title"] = "Freeze UnFreeze Annexure";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Freeze UnFreeze Annexure";
        return View();
    }

    // App: Supplementary Budget | Module: Supp Allocation
    public IActionResult TokenReapprRelaxation()
    {
        ViewData["Title"] = "Token Reappr Relaxation";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supp Allocation / Token Reappr Relaxation";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
