// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.SupplementaryBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("SupplementaryBudget")]
[Authorize]
public class SupplementaryHindiNotesController : Controller
{
    // App: Supplementary Budget | Module: Supplementary Hindi Notes
    public IActionResult UpdateHindiNotes()
    {
        ViewData["Title"] = "Update Hindi Notes";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supplementary Hindi Notes / Update Hindi Notes";
        return View();
    }

    // App: Supplementary Budget | Module: Supplementary Hindi Notes
    public IActionResult UpdateHindiIntro()
    {
        ViewData["Title"] = "Update Hindi Intro";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supplementary Hindi Notes / Update Hindi Intro";
        return View();
    }

    // App: Supplementary Budget | Module: Supplementary Hindi Notes
    public IActionResult UpdateHindiforReporttoParliament()
    {
        ViewData["Title"] = "Update Hindi for Report to Parliament";
        ViewData["Breadcrumb"] = "Supplementary Budget / Supplementary Hindi Notes / Update Hindi for Report to Parliament";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
