// <auto-generated-by-menu-scaffolder>
// Re-running MenuScaffolder only appends new actions below the marker comment near
// the bottom of this class; it never rewrites an existing method body. Remove the
// marker to opt this file out of future auto-appends entirely.
namespace UBIS.Web.Areas.SupplementaryBudget.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

[Area("SupplementaryBudget")]
[Authorize]
public class SuppbudgetController : Controller
{
    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult AddSupplementaryData()
    {
        ViewData["Title"] = "Add Supplementary Data";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Add Supplementary Data";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult ReporttoParliamentAnnexure()
    {
        ViewData["Title"] = "Report to Parliament Annexure";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Report to Parliament Annexure";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult ReceiptRecoveryforTechnicalSupp()
    {
        ViewData["Title"] = "Receipt / Recovery for Technical Supp";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Receipt / Recovery for Technical Supp";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult ReporttoParliamentTimePeriod()
    {
        ViewData["Title"] = "Report to Parliament Time Period ";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Report to Parliament Time Period ";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult ViewSupplementary()
    {
        ViewData["Title"] = "View Supplementary";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / View Supplementary";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult AddDemandWisePageNo()
    {
        ViewData["Title"] = "Add DemandWise Page No";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Add DemandWise Page No";
        return View();
    }

    // App: Supplementary Budget | Module: Suppbudget
    public IActionResult SupplementaryIntroduction()
    {
        ViewData["Title"] = "Supplementary Introduction";
        ViewData["Breadcrumb"] = "Supplementary Budget / Suppbudget / Supplementary Introduction";
        return View();
    }

    // SCAFFOLD:APPEND-ACTIONS-ABOVE-THIS-LINE
}
